// Code generated by ent, DO NOT EDIT.

package cafecampaignuse

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldLTE(FieldID, id))
}

// CampaignID applies equality check predicate on the "campaign_id" field. It's identical to CampaignIDEQ.
func CampaignID(v int64) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldEQ(FieldCampaignID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldEQ(FieldUserID, v))
}

// OrderID applies equality check predicate on the "order_id" field. It's identical to OrderIDEQ.
func OrderID(v int64) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldEQ(FieldOrderID, v))
}

// UsedAt applies equality check predicate on the "used_at" field. It's identical to UsedAtEQ.
func UsedAt(v time.Time) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldEQ(FieldUsedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldEQ(FieldUpdatedAt, v))
}

// CampaignIDEQ applies the EQ predicate on the "campaign_id" field.
func CampaignIDEQ(v int64) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldEQ(FieldCampaignID, v))
}

// CampaignIDNEQ applies the NEQ predicate on the "campaign_id" field.
func CampaignIDNEQ(v int64) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldNEQ(FieldCampaignID, v))
}

// CampaignIDIn applies the In predicate on the "campaign_id" field.
func CampaignIDIn(vs ...int64) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldIn(FieldCampaignID, vs...))
}

// CampaignIDNotIn applies the NotIn predicate on the "campaign_id" field.
func CampaignIDNotIn(vs ...int64) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldNotIn(FieldCampaignID, vs...))
}

// CampaignIDGT applies the GT predicate on the "campaign_id" field.
func CampaignIDGT(v int64) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldGT(FieldCampaignID, v))
}

// CampaignIDGTE applies the GTE predicate on the "campaign_id" field.
func CampaignIDGTE(v int64) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldGTE(FieldCampaignID, v))
}

// CampaignIDLT applies the LT predicate on the "campaign_id" field.
func CampaignIDLT(v int64) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldLT(FieldCampaignID, v))
}

// CampaignIDLTE applies the LTE predicate on the "campaign_id" field.
func CampaignIDLTE(v int64) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldLTE(FieldCampaignID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldLTE(FieldUserID, v))
}

// OrderIDEQ applies the EQ predicate on the "order_id" field.
func OrderIDEQ(v int64) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldEQ(FieldOrderID, v))
}

// OrderIDNEQ applies the NEQ predicate on the "order_id" field.
func OrderIDNEQ(v int64) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldNEQ(FieldOrderID, v))
}

// OrderIDIn applies the In predicate on the "order_id" field.
func OrderIDIn(vs ...int64) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldIn(FieldOrderID, vs...))
}

// OrderIDNotIn applies the NotIn predicate on the "order_id" field.
func OrderIDNotIn(vs ...int64) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldNotIn(FieldOrderID, vs...))
}

// OrderIDGT applies the GT predicate on the "order_id" field.
func OrderIDGT(v int64) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldGT(FieldOrderID, v))
}

// OrderIDGTE applies the GTE predicate on the "order_id" field.
func OrderIDGTE(v int64) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldGTE(FieldOrderID, v))
}

// OrderIDLT applies the LT predicate on the "order_id" field.
func OrderIDLT(v int64) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldLT(FieldOrderID, v))
}

// OrderIDLTE applies the LTE predicate on the "order_id" field.
func OrderIDLTE(v int64) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldLTE(FieldOrderID, v))
}

// UsedAtEQ applies the EQ predicate on the "used_at" field.
func UsedAtEQ(v time.Time) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldEQ(FieldUsedAt, v))
}

// UsedAtNEQ applies the NEQ predicate on the "used_at" field.
func UsedAtNEQ(v time.Time) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldNEQ(FieldUsedAt, v))
}

// UsedAtIn applies the In predicate on the "used_at" field.
func UsedAtIn(vs ...time.Time) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldIn(FieldUsedAt, vs...))
}

// UsedAtNotIn applies the NotIn predicate on the "used_at" field.
func UsedAtNotIn(vs ...time.Time) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldNotIn(FieldUsedAt, vs...))
}

// UsedAtGT applies the GT predicate on the "used_at" field.
func UsedAtGT(v time.Time) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldGT(FieldUsedAt, v))
}

// UsedAtGTE applies the GTE predicate on the "used_at" field.
func UsedAtGTE(v time.Time) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldGTE(FieldUsedAt, v))
}

// UsedAtLT applies the LT predicate on the "used_at" field.
func UsedAtLT(v time.Time) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldLT(FieldUsedAt, v))
}

// UsedAtLTE applies the LTE predicate on the "used_at" field.
func UsedAtLTE(v time.Time) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldLTE(FieldUsedAt, v))
}

// UsedAtIsNil applies the IsNil predicate on the "used_at" field.
func UsedAtIsNil() predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldIsNull(FieldUsedAt))
}

// UsedAtNotNil applies the NotNil predicate on the "used_at" field.
func UsedAtNotNil() predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldNotNull(FieldUsedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CafeCampaignUse) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CafeCampaignUse) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CafeCampaignUse) predicate.CafeCampaignUse {
	return predicate.CafeCampaignUse(sql.NotPredicates(p))
}
