// Code generated by ent, DO NOT EDIT.

package cafecoupon

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldLTE(FieldID, id))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldEQ(FieldCode, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldEQ(FieldUserID, v))
}

// MembershipLevel applies equality check predicate on the "membership_level" field. It's identical to MembershipLevelEQ.
func MembershipLevel(v int) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldEQ(FieldMembershipLevel, v))
}

// CouponType applies equality check predicate on the "coupon_type" field. It's identical to CouponTypeEQ.
func CouponType(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldEQ(FieldCouponType, v))
}

// Value applies equality check predicate on the "value" field. It's identical to ValueEQ.
func Value(v float64) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldEQ(FieldValue, v))
}

// Period applies equality check predicate on the "period" field. It's identical to PeriodEQ.
func Period(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldEQ(FieldPeriod, v))
}

// PeriodStart applies equality check predicate on the "period_start" field. It's identical to PeriodStartEQ.
func PeriodStart(v time.Time) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldEQ(FieldPeriodStart, v))
}

// PeriodEnd applies equality check predicate on the "period_end" field. It's identical to PeriodEndEQ.
func PeriodEnd(v time.Time) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldEQ(FieldPeriodEnd, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldEQ(FieldStatus, v))
}

// OrderID applies equality check predicate on the "order_id" field. It's identical to OrderIDEQ.
func OrderID(v int64) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldEQ(FieldOrderID, v))
}

// AppliedAt applies equality check predicate on the "applied_at" field. It's identical to AppliedAtEQ.
func AppliedAt(v time.Time) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldEQ(FieldAppliedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldEQ(FieldUpdatedAt, v))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldHasSuffix(FieldCode, v))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldContainsFold(FieldCode, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldNotIn(FieldUserID, vs...))
}

// MembershipLevelEQ applies the EQ predicate on the "membership_level" field.
func MembershipLevelEQ(v int) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldEQ(FieldMembershipLevel, v))
}

// MembershipLevelNEQ applies the NEQ predicate on the "membership_level" field.
func MembershipLevelNEQ(v int) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldNEQ(FieldMembershipLevel, v))
}

// MembershipLevelIn applies the In predicate on the "membership_level" field.
func MembershipLevelIn(vs ...int) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldIn(FieldMembershipLevel, vs...))
}

// MembershipLevelNotIn applies the NotIn predicate on the "membership_level" field.
func MembershipLevelNotIn(vs ...int) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldNotIn(FieldMembershipLevel, vs...))
}

// MembershipLevelGT applies the GT predicate on the "membership_level" field.
func MembershipLevelGT(v int) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldGT(FieldMembershipLevel, v))
}

// MembershipLevelGTE applies the GTE predicate on the "membership_level" field.
func MembershipLevelGTE(v int) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldGTE(FieldMembershipLevel, v))
}

// MembershipLevelLT applies the LT predicate on the "membership_level" field.
func MembershipLevelLT(v int) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldLT(FieldMembershipLevel, v))
}

// MembershipLevelLTE applies the LTE predicate on the "membership_level" field.
func MembershipLevelLTE(v int) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldLTE(FieldMembershipLevel, v))
}

// CouponTypeEQ applies the EQ predicate on the "coupon_type" field.
func CouponTypeEQ(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldEQ(FieldCouponType, v))
}

// CouponTypeNEQ applies the NEQ predicate on the "coupon_type" field.
func CouponTypeNEQ(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldNEQ(FieldCouponType, v))
}

// CouponTypeIn applies the In predicate on the "coupon_type" field.
func CouponTypeIn(vs ...string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldIn(FieldCouponType, vs...))
}

// CouponTypeNotIn applies the NotIn predicate on the "coupon_type" field.
func CouponTypeNotIn(vs ...string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldNotIn(FieldCouponType, vs...))
}

// CouponTypeGT applies the GT predicate on the "coupon_type" field.
func CouponTypeGT(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldGT(FieldCouponType, v))
}

// CouponTypeGTE applies the GTE predicate on the "coupon_type" field.
func CouponTypeGTE(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldGTE(FieldCouponType, v))
}

// CouponTypeLT applies the LT predicate on the "coupon_type" field.
func CouponTypeLT(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldLT(FieldCouponType, v))
}

// CouponTypeLTE applies the LTE predicate on the "coupon_type" field.
func CouponTypeLTE(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldLTE(FieldCouponType, v))
}

// CouponTypeContains applies the Contains predicate on the "coupon_type" field.
func CouponTypeContains(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldContains(FieldCouponType, v))
}

// CouponTypeHasPrefix applies the HasPrefix predicate on the "coupon_type" field.
func CouponTypeHasPrefix(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldHasPrefix(FieldCouponType, v))
}

// CouponTypeHasSuffix applies the HasSuffix predicate on the "coupon_type" field.
func CouponTypeHasSuffix(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldHasSuffix(FieldCouponType, v))
}

// CouponTypeEqualFold applies the EqualFold predicate on the "coupon_type" field.
func CouponTypeEqualFold(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldEqualFold(FieldCouponType, v))
}

// CouponTypeContainsFold applies the ContainsFold predicate on the "coupon_type" field.
func CouponTypeContainsFold(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldContainsFold(FieldCouponType, v))
}

// ValueEQ applies the EQ predicate on the "value" field.
func ValueEQ(v float64) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldEQ(FieldValue, v))
}

// ValueNEQ applies the NEQ predicate on the "value" field.
func ValueNEQ(v float64) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldNEQ(FieldValue, v))
}

// ValueIn applies the In predicate on the "value" field.
func ValueIn(vs ...float64) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldIn(FieldValue, vs...))
}

// ValueNotIn applies the NotIn predicate on the "value" field.
func ValueNotIn(vs ...float64) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldNotIn(FieldValue, vs...))
}

// ValueGT applies the GT predicate on the "value" field.
func ValueGT(v float64) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldGT(FieldValue, v))
}

// ValueGTE applies the GTE predicate on the "value" field.
func ValueGTE(v float64) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldGTE(FieldValue, v))
}

// ValueLT applies the LT predicate on the "value" field.
func ValueLT(v float64) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldLT(FieldValue, v))
}

// ValueLTE applies the LTE predicate on the "value" field.
func ValueLTE(v float64) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldLTE(FieldValue, v))
}

// PeriodEQ applies the EQ predicate on the "period" field.
func PeriodEQ(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldEQ(FieldPeriod, v))
}

// PeriodNEQ applies the NEQ predicate on the "period" field.
func PeriodNEQ(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldNEQ(FieldPeriod, v))
}

// PeriodIn applies the In predicate on the "period" field.
func PeriodIn(vs ...string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldIn(FieldPeriod, vs...))
}

// PeriodNotIn applies the NotIn predicate on the "period" field.
func PeriodNotIn(vs ...string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldNotIn(FieldPeriod, vs...))
}

// PeriodGT applies the GT predicate on the "period" field.
func PeriodGT(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldGT(FieldPeriod, v))
}

// PeriodGTE applies the GTE predicate on the "period" field.
func PeriodGTE(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldGTE(FieldPeriod, v))
}

// PeriodLT applies the LT predicate on the "period" field.
func PeriodLT(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldLT(FieldPeriod, v))
}

// PeriodLTE applies the LTE predicate on the "period" field.
func PeriodLTE(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldLTE(FieldPeriod, v))
}

// PeriodContains applies the Contains predicate on the "period" field.
func PeriodContains(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldContains(FieldPeriod, v))
}

// PeriodHasPrefix applies the HasPrefix predicate on the "period" field.
func PeriodHasPrefix(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldHasPrefix(FieldPeriod, v))
}

// PeriodHasSuffix applies the HasSuffix predicate on the "period" field.
func PeriodHasSuffix(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldHasSuffix(FieldPeriod, v))
}

// PeriodEqualFold applies the EqualFold predicate on the "period" field.
func PeriodEqualFold(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldEqualFold(FieldPeriod, v))
}

// PeriodContainsFold applies the ContainsFold predicate on the "period" field.
func PeriodContainsFold(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldContainsFold(FieldPeriod, v))
}

// PeriodStartEQ applies the EQ predicate on the "period_start" field.
func PeriodStartEQ(v time.Time) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldEQ(FieldPeriodStart, v))
}

// PeriodStartNEQ applies the NEQ predicate on the "period_start" field.
func PeriodStartNEQ(v time.Time) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldNEQ(FieldPeriodStart, v))
}

// PeriodStartIn applies the In predicate on the "period_start" field.
func PeriodStartIn(vs ...time.Time) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldIn(FieldPeriodStart, vs...))
}

// PeriodStartNotIn applies the NotIn predicate on the "period_start" field.
func PeriodStartNotIn(vs ...time.Time) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldNotIn(FieldPeriodStart, vs...))
}

// PeriodStartGT applies the GT predicate on the "period_start" field.
func PeriodStartGT(v time.Time) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldGT(FieldPeriodStart, v))
}

// PeriodStartGTE applies the GTE predicate on the "period_start" field.
func PeriodStartGTE(v time.Time) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldGTE(FieldPeriodStart, v))
}

// PeriodStartLT applies the LT predicate on the "period_start" field.
func PeriodStartLT(v time.Time) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldLT(FieldPeriodStart, v))
}

// PeriodStartLTE applies the LTE predicate on the "period_start" field.
func PeriodStartLTE(v time.Time) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldLTE(FieldPeriodStart, v))
}

// PeriodEndEQ applies the EQ predicate on the "period_end" field.
func PeriodEndEQ(v time.Time) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldEQ(FieldPeriodEnd, v))
}

// PeriodEndNEQ applies the NEQ predicate on the "period_end" field.
func PeriodEndNEQ(v time.Time) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldNEQ(FieldPeriodEnd, v))
}

// PeriodEndIn applies the In predicate on the "period_end" field.
func PeriodEndIn(vs ...time.Time) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldIn(FieldPeriodEnd, vs...))
}

// PeriodEndNotIn applies the NotIn predicate on the "period_end" field.
func PeriodEndNotIn(vs ...time.Time) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldNotIn(FieldPeriodEnd, vs...))
}

// PeriodEndGT applies the GT predicate on the "period_end" field.
func PeriodEndGT(v time.Time) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldGT(FieldPeriodEnd, v))
}

// PeriodEndGTE applies the GTE predicate on the "period_end" field.
func PeriodEndGTE(v time.Time) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldGTE(FieldPeriodEnd, v))
}

// PeriodEndLT applies the LT predicate on the "period_end" field.
func PeriodEndLT(v time.Time) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldLT(FieldPeriodEnd, v))
}

// PeriodEndLTE applies the LTE predicate on the "period_end" field.
func PeriodEndLTE(v time.Time) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldLTE(FieldPeriodEnd, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldContainsFold(FieldStatus, v))
}

// OrderIDEQ applies the EQ predicate on the "order_id" field.
func OrderIDEQ(v int64) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldEQ(FieldOrderID, v))
}

// OrderIDNEQ applies the NEQ predicate on the "order_id" field.
func OrderIDNEQ(v int64) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldNEQ(FieldOrderID, v))
}

// OrderIDIn applies the In predicate on the "order_id" field.
func OrderIDIn(vs ...int64) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldIn(FieldOrderID, vs...))
}

// OrderIDNotIn applies the NotIn predicate on the "order_id" field.
func OrderIDNotIn(vs ...int64) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldNotIn(FieldOrderID, vs...))
}

// OrderIDGT applies the GT predicate on the "order_id" field.
func OrderIDGT(v int64) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldGT(FieldOrderID, v))
}

// OrderIDGTE applies the GTE predicate on the "order_id" field.
func OrderIDGTE(v int64) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldGTE(FieldOrderID, v))
}

// OrderIDLT applies the LT predicate on the "order_id" field.
func OrderIDLT(v int64) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldLT(FieldOrderID, v))
}

// OrderIDLTE applies the LTE predicate on the "order_id" field.
func OrderIDLTE(v int64) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldLTE(FieldOrderID, v))
}

// OrderIDIsNil applies the IsNil predicate on the "order_id" field.
func OrderIDIsNil() predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldIsNull(FieldOrderID))
}

// OrderIDNotNil applies the NotNil predicate on the "order_id" field.
func OrderIDNotNil() predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldNotNull(FieldOrderID))
}

// AppliedAtEQ applies the EQ predicate on the "applied_at" field.
func AppliedAtEQ(v time.Time) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldEQ(FieldAppliedAt, v))
}

// AppliedAtNEQ applies the NEQ predicate on the "applied_at" field.
func AppliedAtNEQ(v time.Time) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldNEQ(FieldAppliedAt, v))
}

// AppliedAtIn applies the In predicate on the "applied_at" field.
func AppliedAtIn(vs ...time.Time) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldIn(FieldAppliedAt, vs...))
}

// AppliedAtNotIn applies the NotIn predicate on the "applied_at" field.
func AppliedAtNotIn(vs ...time.Time) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldNotIn(FieldAppliedAt, vs...))
}

// AppliedAtGT applies the GT predicate on the "applied_at" field.
func AppliedAtGT(v time.Time) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldGT(FieldAppliedAt, v))
}

// AppliedAtGTE applies the GTE predicate on the "applied_at" field.
func AppliedAtGTE(v time.Time) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldGTE(FieldAppliedAt, v))
}

// AppliedAtLT applies the LT predicate on the "applied_at" field.
func AppliedAtLT(v time.Time) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldLT(FieldAppliedAt, v))
}

// AppliedAtLTE applies the LTE predicate on the "applied_at" field.
func AppliedAtLTE(v time.Time) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldLTE(FieldAppliedAt, v))
}

// AppliedAtIsNil applies the IsNil predicate on the "applied_at" field.
func AppliedAtIsNil() predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldIsNull(FieldAppliedAt))
}

// AppliedAtNotNil applies the NotNil predicate on the "applied_at" field.
func AppliedAtNotNil() predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldNotNull(FieldAppliedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.CafeCoupon {
	return predicate.CafeCoupon(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.CafeCoupon {
	return predicate.CafeCoupon(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CafeCoupon) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CafeCoupon) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CafeCoupon) predicate.CafeCoupon {
	return predicate.CafeCoupon(sql.NotPredicates(p))
}
