// Code generated by ent, DO NOT EDIT.

package cafecampaign

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldLTE(FieldID, id))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldEQ(FieldCode, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldEQ(FieldName, v))
}

// DiscountPercent applies equality check predicate on the "discount_percent" field. It's identical to DiscountPercentEQ.
func DiscountPercent(v int) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldEQ(FieldDiscountPercent, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldEQ(FieldEnabled, v))
}

// StartsAt applies equality check predicate on the "starts_at" field. It's identical to StartsAtEQ.
func StartsAt(v time.Time) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldEQ(FieldStartsAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v int64) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldEQ(FieldUpdatedAt, v))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldHasSuffix(FieldCode, v))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldContainsFold(FieldCode, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldContainsFold(FieldName, v))
}

// DiscountPercentEQ applies the EQ predicate on the "discount_percent" field.
func DiscountPercentEQ(v int) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldEQ(FieldDiscountPercent, v))
}

// DiscountPercentNEQ applies the NEQ predicate on the "discount_percent" field.
func DiscountPercentNEQ(v int) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldNEQ(FieldDiscountPercent, v))
}

// DiscountPercentIn applies the In predicate on the "discount_percent" field.
func DiscountPercentIn(vs ...int) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldIn(FieldDiscountPercent, vs...))
}

// DiscountPercentNotIn applies the NotIn predicate on the "discount_percent" field.
func DiscountPercentNotIn(vs ...int) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldNotIn(FieldDiscountPercent, vs...))
}

// DiscountPercentGT applies the GT predicate on the "discount_percent" field.
func DiscountPercentGT(v int) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldGT(FieldDiscountPercent, v))
}

// DiscountPercentGTE applies the GTE predicate on the "discount_percent" field.
func DiscountPercentGTE(v int) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldGTE(FieldDiscountPercent, v))
}

// DiscountPercentLT applies the LT predicate on the "discount_percent" field.
func DiscountPercentLT(v int) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldLT(FieldDiscountPercent, v))
}

// DiscountPercentLTE applies the LTE predicate on the "discount_percent" field.
func DiscountPercentLTE(v int) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldLTE(FieldDiscountPercent, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldNEQ(FieldEnabled, v))
}

// StartsAtEQ applies the EQ predicate on the "starts_at" field.
func StartsAtEQ(v time.Time) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldEQ(FieldStartsAt, v))
}

// StartsAtNEQ applies the NEQ predicate on the "starts_at" field.
func StartsAtNEQ(v time.Time) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldNEQ(FieldStartsAt, v))
}

// StartsAtIn applies the In predicate on the "starts_at" field.
func StartsAtIn(vs ...time.Time) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldIn(FieldStartsAt, vs...))
}

// StartsAtNotIn applies the NotIn predicate on the "starts_at" field.
func StartsAtNotIn(vs ...time.Time) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldNotIn(FieldStartsAt, vs...))
}

// StartsAtGT applies the GT predicate on the "starts_at" field.
func StartsAtGT(v time.Time) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldGT(FieldStartsAt, v))
}

// StartsAtGTE applies the GTE predicate on the "starts_at" field.
func StartsAtGTE(v time.Time) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldGTE(FieldStartsAt, v))
}

// StartsAtLT applies the LT predicate on the "starts_at" field.
func StartsAtLT(v time.Time) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldLT(FieldStartsAt, v))
}

// StartsAtLTE applies the LTE predicate on the "starts_at" field.
func StartsAtLTE(v time.Time) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldLTE(FieldStartsAt, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldLTE(FieldExpiresAt, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v int64) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v int64) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...int64) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...int64) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v int64) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v int64) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v int64) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v int64) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CafeCampaign) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CafeCampaign) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CafeCampaign) predicate.CafeCampaign {
	return predicate.CafeCampaign(sql.NotPredicates(p))
}
