// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/cafecampaign"
)

// CafeCampaignCreate is the builder for creating a CafeCampaign entity.
type CafeCampaignCreate struct {
	config
	mutation *CafeCampaignMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCode sets the "code" field.
func (_c *CafeCampaignCreate) SetCode(v string) *CafeCampaignCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetName sets the "name" field.
func (_c *CafeCampaignCreate) SetName(v string) *CafeCampaignCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDiscountPercent sets the "discount_percent" field.
func (_c *CafeCampaignCreate) SetDiscountPercent(v int) *CafeCampaignCreate {
	_c.mutation.SetDiscountPercent(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *CafeCampaignCreate) SetEnabled(v bool) *CafeCampaignCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *CafeCampaignCreate) SetNillableEnabled(v *bool) *CafeCampaignCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetStartsAt sets the "starts_at" field.
func (_c *CafeCampaignCreate) SetStartsAt(v time.Time) *CafeCampaignCreate {
	_c.mutation.SetStartsAt(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *CafeCampaignCreate) SetExpiresAt(v time.Time) *CafeCampaignCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *CafeCampaignCreate) SetCreatedBy(v int64) *CafeCampaignCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CafeCampaignCreate) SetCreatedAt(v time.Time) *CafeCampaignCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CafeCampaignCreate) SetNillableCreatedAt(v *time.Time) *CafeCampaignCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CafeCampaignCreate) SetUpdatedAt(v time.Time) *CafeCampaignCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CafeCampaignCreate) SetNillableUpdatedAt(v *time.Time) *CafeCampaignCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the CafeCampaignMutation object of the builder.
func (_c *CafeCampaignCreate) Mutation() *CafeCampaignMutation {
	return _c.mutation
}

// Save creates the CafeCampaign in the database.
func (_c *CafeCampaignCreate) Save(ctx context.Context) (*CafeCampaign, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CafeCampaignCreate) SaveX(ctx context.Context) *CafeCampaign {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CafeCampaignCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CafeCampaignCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CafeCampaignCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := cafecampaign.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := cafecampaign.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := cafecampaign.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CafeCampaignCreate) check() error {
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "CafeCampaign.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := cafecampaign.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "CafeCampaign.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "CafeCampaign.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := cafecampaign.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CafeCampaign.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DiscountPercent(); !ok {
		return &ValidationError{Name: "discount_percent", err: errors.New(`ent: missing required field "CafeCampaign.discount_percent"`)}
	}
	if v, ok := _c.mutation.DiscountPercent(); ok {
		if err := cafecampaign.DiscountPercentValidator(v); err != nil {
			return &ValidationError{Name: "discount_percent", err: fmt.Errorf(`ent: validator failed for field "CafeCampaign.discount_percent": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "CafeCampaign.enabled"`)}
	}
	if _, ok := _c.mutation.StartsAt(); !ok {
		return &ValidationError{Name: "starts_at", err: errors.New(`ent: missing required field "CafeCampaign.starts_at"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "CafeCampaign.expires_at"`)}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "CafeCampaign.created_by"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CafeCampaign.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CafeCampaign.updated_at"`)}
	}
	return nil
}

func (_c *CafeCampaignCreate) sqlSave(ctx context.Context) (*CafeCampaign, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CafeCampaignCreate) createSpec() (*CafeCampaign, *sqlgraph.CreateSpec) {
	var (
		_node = &CafeCampaign{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(cafecampaign.Table, sqlgraph.NewFieldSpec(cafecampaign.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(cafecampaign.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(cafecampaign.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.DiscountPercent(); ok {
		_spec.SetField(cafecampaign.FieldDiscountPercent, field.TypeInt, value)
		_node.DiscountPercent = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(cafecampaign.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.StartsAt(); ok {
		_spec.SetField(cafecampaign.FieldStartsAt, field.TypeTime, value)
		_node.StartsAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(cafecampaign.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(cafecampaign.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(cafecampaign.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(cafecampaign.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CafeCampaign.Create().
//		SetCode(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CafeCampaignUpsert) {
//			SetCode(v+v).
//		}).
//		Exec(ctx)
func (_c *CafeCampaignCreate) OnConflict(opts ...sql.ConflictOption) *CafeCampaignUpsertOne {
	_c.conflict = opts
	return &CafeCampaignUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CafeCampaign.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CafeCampaignCreate) OnConflictColumns(columns ...string) *CafeCampaignUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CafeCampaignUpsertOne{
		create: _c,
	}
}

type (
	// CafeCampaignUpsertOne is the builder for "upsert"-ing
	//  one CafeCampaign node.
	CafeCampaignUpsertOne struct {
		create *CafeCampaignCreate
	}

	// CafeCampaignUpsert is the "OnConflict" setter.
	CafeCampaignUpsert struct {
		*sql.UpdateSet
	}
)

// SetEnabled sets the "enabled" field.
func (u *CafeCampaignUpsert) SetEnabled(v bool) *CafeCampaignUpsert {
	u.Set(cafecampaign.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *CafeCampaignUpsert) UpdateEnabled() *CafeCampaignUpsert {
	u.SetExcluded(cafecampaign.FieldEnabled)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CafeCampaignUpsert) SetUpdatedAt(v time.Time) *CafeCampaignUpsert {
	u.Set(cafecampaign.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CafeCampaignUpsert) UpdateUpdatedAt() *CafeCampaignUpsert {
	u.SetExcluded(cafecampaign.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CafeCampaign.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CafeCampaignUpsertOne) UpdateNewValues() *CafeCampaignUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.Code(); exists {
			s.SetIgnore(cafecampaign.FieldCode)
		}
		if _, exists := u.create.mutation.Name(); exists {
			s.SetIgnore(cafecampaign.FieldName)
		}
		if _, exists := u.create.mutation.DiscountPercent(); exists {
			s.SetIgnore(cafecampaign.FieldDiscountPercent)
		}
		if _, exists := u.create.mutation.StartsAt(); exists {
			s.SetIgnore(cafecampaign.FieldStartsAt)
		}
		if _, exists := u.create.mutation.ExpiresAt(); exists {
			s.SetIgnore(cafecampaign.FieldExpiresAt)
		}
		if _, exists := u.create.mutation.CreatedBy(); exists {
			s.SetIgnore(cafecampaign.FieldCreatedBy)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(cafecampaign.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CafeCampaign.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CafeCampaignUpsertOne) Ignore() *CafeCampaignUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CafeCampaignUpsertOne) DoNothing() *CafeCampaignUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CafeCampaignCreate.OnConflict
// documentation for more info.
func (u *CafeCampaignUpsertOne) Update(set func(*CafeCampaignUpsert)) *CafeCampaignUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CafeCampaignUpsert{UpdateSet: update})
	}))
	return u
}

// SetEnabled sets the "enabled" field.
func (u *CafeCampaignUpsertOne) SetEnabled(v bool) *CafeCampaignUpsertOne {
	return u.Update(func(s *CafeCampaignUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *CafeCampaignUpsertOne) UpdateEnabled() *CafeCampaignUpsertOne {
	return u.Update(func(s *CafeCampaignUpsert) {
		s.UpdateEnabled()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CafeCampaignUpsertOne) SetUpdatedAt(v time.Time) *CafeCampaignUpsertOne {
	return u.Update(func(s *CafeCampaignUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CafeCampaignUpsertOne) UpdateUpdatedAt() *CafeCampaignUpsertOne {
	return u.Update(func(s *CafeCampaignUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CafeCampaignUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CafeCampaignCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CafeCampaignUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CafeCampaignUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CafeCampaignUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CafeCampaignCreateBulk is the builder for creating many CafeCampaign entities in bulk.
type CafeCampaignCreateBulk struct {
	config
	err      error
	builders []*CafeCampaignCreate
	conflict []sql.ConflictOption
}

// Save creates the CafeCampaign entities in the database.
func (_c *CafeCampaignCreateBulk) Save(ctx context.Context) ([]*CafeCampaign, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CafeCampaign, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CafeCampaignMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CafeCampaignCreateBulk) SaveX(ctx context.Context) []*CafeCampaign {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CafeCampaignCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CafeCampaignCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CafeCampaign.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CafeCampaignUpsert) {
//			SetCode(v+v).
//		}).
//		Exec(ctx)
func (_c *CafeCampaignCreateBulk) OnConflict(opts ...sql.ConflictOption) *CafeCampaignUpsertBulk {
	_c.conflict = opts
	return &CafeCampaignUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CafeCampaign.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CafeCampaignCreateBulk) OnConflictColumns(columns ...string) *CafeCampaignUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CafeCampaignUpsertBulk{
		create: _c,
	}
}

// CafeCampaignUpsertBulk is the builder for "upsert"-ing
// a bulk of CafeCampaign nodes.
type CafeCampaignUpsertBulk struct {
	create *CafeCampaignCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CafeCampaign.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CafeCampaignUpsertBulk) UpdateNewValues() *CafeCampaignUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.Code(); exists {
				s.SetIgnore(cafecampaign.FieldCode)
			}
			if _, exists := b.mutation.Name(); exists {
				s.SetIgnore(cafecampaign.FieldName)
			}
			if _, exists := b.mutation.DiscountPercent(); exists {
				s.SetIgnore(cafecampaign.FieldDiscountPercent)
			}
			if _, exists := b.mutation.StartsAt(); exists {
				s.SetIgnore(cafecampaign.FieldStartsAt)
			}
			if _, exists := b.mutation.ExpiresAt(); exists {
				s.SetIgnore(cafecampaign.FieldExpiresAt)
			}
			if _, exists := b.mutation.CreatedBy(); exists {
				s.SetIgnore(cafecampaign.FieldCreatedBy)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(cafecampaign.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CafeCampaign.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CafeCampaignUpsertBulk) Ignore() *CafeCampaignUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CafeCampaignUpsertBulk) DoNothing() *CafeCampaignUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CafeCampaignCreateBulk.OnConflict
// documentation for more info.
func (u *CafeCampaignUpsertBulk) Update(set func(*CafeCampaignUpsert)) *CafeCampaignUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CafeCampaignUpsert{UpdateSet: update})
	}))
	return u
}

// SetEnabled sets the "enabled" field.
func (u *CafeCampaignUpsertBulk) SetEnabled(v bool) *CafeCampaignUpsertBulk {
	return u.Update(func(s *CafeCampaignUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *CafeCampaignUpsertBulk) UpdateEnabled() *CafeCampaignUpsertBulk {
	return u.Update(func(s *CafeCampaignUpsert) {
		s.UpdateEnabled()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CafeCampaignUpsertBulk) SetUpdatedAt(v time.Time) *CafeCampaignUpsertBulk {
	return u.Update(func(s *CafeCampaignUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CafeCampaignUpsertBulk) UpdateUpdatedAt() *CafeCampaignUpsertBulk {
	return u.Update(func(s *CafeCampaignUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CafeCampaignUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CafeCampaignCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CafeCampaignCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CafeCampaignUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
