// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/promotionactivity"
	"github.com/Wei-Shaw/sub2api/ent/promotionactivityparticipation"
	"github.com/Wei-Shaw/sub2api/ent/promotionactivityplan"
)

// PromotionActivityCreate is the builder for creating a PromotionActivity entity.
type PromotionActivityCreate struct {
	config
	mutation *PromotionActivityMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *PromotionActivityCreate) SetName(v string) *PromotionActivityCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetActivityType sets the "activity_type" field.
func (_c *PromotionActivityCreate) SetActivityType(v string) *PromotionActivityCreate {
	_c.mutation.SetActivityType(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *PromotionActivityCreate) SetEnabled(v bool) *PromotionActivityCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *PromotionActivityCreate) SetNillableEnabled(v *bool) *PromotionActivityCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetStartsAt sets the "starts_at" field.
func (_c *PromotionActivityCreate) SetStartsAt(v time.Time) *PromotionActivityCreate {
	_c.mutation.SetStartsAt(v)
	return _c
}

// SetEndsAt sets the "ends_at" field.
func (_c *PromotionActivityCreate) SetEndsAt(v time.Time) *PromotionActivityCreate {
	_c.mutation.SetEndsAt(v)
	return _c
}

// SetMaxUsesPerUser sets the "max_uses_per_user" field.
func (_c *PromotionActivityCreate) SetMaxUsesPerUser(v int) *PromotionActivityCreate {
	_c.mutation.SetMaxUsesPerUser(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PromotionActivityCreate) SetCreatedAt(v time.Time) *PromotionActivityCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PromotionActivityCreate) SetNillableCreatedAt(v *time.Time) *PromotionActivityCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PromotionActivityCreate) SetUpdatedAt(v time.Time) *PromotionActivityCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PromotionActivityCreate) SetNillableUpdatedAt(v *time.Time) *PromotionActivityCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddPlanBonuseIDs adds the "plan_bonuses" edge to the PromotionActivityPlan entity by IDs.
func (_c *PromotionActivityCreate) AddPlanBonuseIDs(ids ...int64) *PromotionActivityCreate {
	_c.mutation.AddPlanBonuseIDs(ids...)
	return _c
}

// AddPlanBonuses adds the "plan_bonuses" edges to the PromotionActivityPlan entity.
func (_c *PromotionActivityCreate) AddPlanBonuses(v ...*PromotionActivityPlan) *PromotionActivityCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPlanBonuseIDs(ids...)
}

// AddParticipationIDs adds the "participations" edge to the PromotionActivityParticipation entity by IDs.
func (_c *PromotionActivityCreate) AddParticipationIDs(ids ...int64) *PromotionActivityCreate {
	_c.mutation.AddParticipationIDs(ids...)
	return _c
}

// AddParticipations adds the "participations" edges to the PromotionActivityParticipation entity.
func (_c *PromotionActivityCreate) AddParticipations(v ...*PromotionActivityParticipation) *PromotionActivityCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddParticipationIDs(ids...)
}

// Mutation returns the PromotionActivityMutation object of the builder.
func (_c *PromotionActivityCreate) Mutation() *PromotionActivityMutation {
	return _c.mutation
}

// Save creates the PromotionActivity in the database.
func (_c *PromotionActivityCreate) Save(ctx context.Context) (*PromotionActivity, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PromotionActivityCreate) SaveX(ctx context.Context) *PromotionActivity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromotionActivityCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromotionActivityCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PromotionActivityCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := promotionactivity.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := promotionactivity.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := promotionactivity.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PromotionActivityCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "PromotionActivity.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := promotionactivity.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PromotionActivity.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ActivityType(); !ok {
		return &ValidationError{Name: "activity_type", err: errors.New(`ent: missing required field "PromotionActivity.activity_type"`)}
	}
	if v, ok := _c.mutation.ActivityType(); ok {
		if err := promotionactivity.ActivityTypeValidator(v); err != nil {
			return &ValidationError{Name: "activity_type", err: fmt.Errorf(`ent: validator failed for field "PromotionActivity.activity_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "PromotionActivity.enabled"`)}
	}
	if _, ok := _c.mutation.StartsAt(); !ok {
		return &ValidationError{Name: "starts_at", err: errors.New(`ent: missing required field "PromotionActivity.starts_at"`)}
	}
	if _, ok := _c.mutation.EndsAt(); !ok {
		return &ValidationError{Name: "ends_at", err: errors.New(`ent: missing required field "PromotionActivity.ends_at"`)}
	}
	if _, ok := _c.mutation.MaxUsesPerUser(); !ok {
		return &ValidationError{Name: "max_uses_per_user", err: errors.New(`ent: missing required field "PromotionActivity.max_uses_per_user"`)}
	}
	if v, ok := _c.mutation.MaxUsesPerUser(); ok {
		if err := promotionactivity.MaxUsesPerUserValidator(v); err != nil {
			return &ValidationError{Name: "max_uses_per_user", err: fmt.Errorf(`ent: validator failed for field "PromotionActivity.max_uses_per_user": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PromotionActivity.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PromotionActivity.updated_at"`)}
	}
	return nil
}

func (_c *PromotionActivityCreate) sqlSave(ctx context.Context) (*PromotionActivity, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PromotionActivityCreate) createSpec() (*PromotionActivity, *sqlgraph.CreateSpec) {
	var (
		_node = &PromotionActivity{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(promotionactivity.Table, sqlgraph.NewFieldSpec(promotionactivity.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(promotionactivity.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.ActivityType(); ok {
		_spec.SetField(promotionactivity.FieldActivityType, field.TypeString, value)
		_node.ActivityType = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(promotionactivity.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.StartsAt(); ok {
		_spec.SetField(promotionactivity.FieldStartsAt, field.TypeTime, value)
		_node.StartsAt = value
	}
	if value, ok := _c.mutation.EndsAt(); ok {
		_spec.SetField(promotionactivity.FieldEndsAt, field.TypeTime, value)
		_node.EndsAt = value
	}
	if value, ok := _c.mutation.MaxUsesPerUser(); ok {
		_spec.SetField(promotionactivity.FieldMaxUsesPerUser, field.TypeInt, value)
		_node.MaxUsesPerUser = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(promotionactivity.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(promotionactivity.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.PlanBonusesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   promotionactivity.PlanBonusesTable,
			Columns: []string{promotionactivity.PlanBonusesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(promotionactivityplan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ParticipationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   promotionactivity.ParticipationsTable,
			Columns: []string{promotionactivity.ParticipationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(promotionactivityparticipation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PromotionActivity.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PromotionActivityUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *PromotionActivityCreate) OnConflict(opts ...sql.ConflictOption) *PromotionActivityUpsertOne {
	_c.conflict = opts
	return &PromotionActivityUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PromotionActivity.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PromotionActivityCreate) OnConflictColumns(columns ...string) *PromotionActivityUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PromotionActivityUpsertOne{
		create: _c,
	}
}

type (
	// PromotionActivityUpsertOne is the builder for "upsert"-ing
	//  one PromotionActivity node.
	PromotionActivityUpsertOne struct {
		create *PromotionActivityCreate
	}

	// PromotionActivityUpsert is the "OnConflict" setter.
	PromotionActivityUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *PromotionActivityUpsert) SetName(v string) *PromotionActivityUpsert {
	u.Set(promotionactivity.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PromotionActivityUpsert) UpdateName() *PromotionActivityUpsert {
	u.SetExcluded(promotionactivity.FieldName)
	return u
}

// SetActivityType sets the "activity_type" field.
func (u *PromotionActivityUpsert) SetActivityType(v string) *PromotionActivityUpsert {
	u.Set(promotionactivity.FieldActivityType, v)
	return u
}

// UpdateActivityType sets the "activity_type" field to the value that was provided on create.
func (u *PromotionActivityUpsert) UpdateActivityType() *PromotionActivityUpsert {
	u.SetExcluded(promotionactivity.FieldActivityType)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *PromotionActivityUpsert) SetEnabled(v bool) *PromotionActivityUpsert {
	u.Set(promotionactivity.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *PromotionActivityUpsert) UpdateEnabled() *PromotionActivityUpsert {
	u.SetExcluded(promotionactivity.FieldEnabled)
	return u
}

// SetStartsAt sets the "starts_at" field.
func (u *PromotionActivityUpsert) SetStartsAt(v time.Time) *PromotionActivityUpsert {
	u.Set(promotionactivity.FieldStartsAt, v)
	return u
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *PromotionActivityUpsert) UpdateStartsAt() *PromotionActivityUpsert {
	u.SetExcluded(promotionactivity.FieldStartsAt)
	return u
}

// SetEndsAt sets the "ends_at" field.
func (u *PromotionActivityUpsert) SetEndsAt(v time.Time) *PromotionActivityUpsert {
	u.Set(promotionactivity.FieldEndsAt, v)
	return u
}

// UpdateEndsAt sets the "ends_at" field to the value that was provided on create.
func (u *PromotionActivityUpsert) UpdateEndsAt() *PromotionActivityUpsert {
	u.SetExcluded(promotionactivity.FieldEndsAt)
	return u
}

// SetMaxUsesPerUser sets the "max_uses_per_user" field.
func (u *PromotionActivityUpsert) SetMaxUsesPerUser(v int) *PromotionActivityUpsert {
	u.Set(promotionactivity.FieldMaxUsesPerUser, v)
	return u
}

// UpdateMaxUsesPerUser sets the "max_uses_per_user" field to the value that was provided on create.
func (u *PromotionActivityUpsert) UpdateMaxUsesPerUser() *PromotionActivityUpsert {
	u.SetExcluded(promotionactivity.FieldMaxUsesPerUser)
	return u
}

// AddMaxUsesPerUser adds v to the "max_uses_per_user" field.
func (u *PromotionActivityUpsert) AddMaxUsesPerUser(v int) *PromotionActivityUpsert {
	u.Add(promotionactivity.FieldMaxUsesPerUser, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PromotionActivityUpsert) SetUpdatedAt(v time.Time) *PromotionActivityUpsert {
	u.Set(promotionactivity.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PromotionActivityUpsert) UpdateUpdatedAt() *PromotionActivityUpsert {
	u.SetExcluded(promotionactivity.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PromotionActivity.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PromotionActivityUpsertOne) UpdateNewValues() *PromotionActivityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(promotionactivity.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PromotionActivity.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PromotionActivityUpsertOne) Ignore() *PromotionActivityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PromotionActivityUpsertOne) DoNothing() *PromotionActivityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PromotionActivityCreate.OnConflict
// documentation for more info.
func (u *PromotionActivityUpsertOne) Update(set func(*PromotionActivityUpsert)) *PromotionActivityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PromotionActivityUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *PromotionActivityUpsertOne) SetName(v string) *PromotionActivityUpsertOne {
	return u.Update(func(s *PromotionActivityUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PromotionActivityUpsertOne) UpdateName() *PromotionActivityUpsertOne {
	return u.Update(func(s *PromotionActivityUpsert) {
		s.UpdateName()
	})
}

// SetActivityType sets the "activity_type" field.
func (u *PromotionActivityUpsertOne) SetActivityType(v string) *PromotionActivityUpsertOne {
	return u.Update(func(s *PromotionActivityUpsert) {
		s.SetActivityType(v)
	})
}

// UpdateActivityType sets the "activity_type" field to the value that was provided on create.
func (u *PromotionActivityUpsertOne) UpdateActivityType() *PromotionActivityUpsertOne {
	return u.Update(func(s *PromotionActivityUpsert) {
		s.UpdateActivityType()
	})
}

// SetEnabled sets the "enabled" field.
func (u *PromotionActivityUpsertOne) SetEnabled(v bool) *PromotionActivityUpsertOne {
	return u.Update(func(s *PromotionActivityUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *PromotionActivityUpsertOne) UpdateEnabled() *PromotionActivityUpsertOne {
	return u.Update(func(s *PromotionActivityUpsert) {
		s.UpdateEnabled()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *PromotionActivityUpsertOne) SetStartsAt(v time.Time) *PromotionActivityUpsertOne {
	return u.Update(func(s *PromotionActivityUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *PromotionActivityUpsertOne) UpdateStartsAt() *PromotionActivityUpsertOne {
	return u.Update(func(s *PromotionActivityUpsert) {
		s.UpdateStartsAt()
	})
}

// SetEndsAt sets the "ends_at" field.
func (u *PromotionActivityUpsertOne) SetEndsAt(v time.Time) *PromotionActivityUpsertOne {
	return u.Update(func(s *PromotionActivityUpsert) {
		s.SetEndsAt(v)
	})
}

// UpdateEndsAt sets the "ends_at" field to the value that was provided on create.
func (u *PromotionActivityUpsertOne) UpdateEndsAt() *PromotionActivityUpsertOne {
	return u.Update(func(s *PromotionActivityUpsert) {
		s.UpdateEndsAt()
	})
}

// SetMaxUsesPerUser sets the "max_uses_per_user" field.
func (u *PromotionActivityUpsertOne) SetMaxUsesPerUser(v int) *PromotionActivityUpsertOne {
	return u.Update(func(s *PromotionActivityUpsert) {
		s.SetMaxUsesPerUser(v)
	})
}

// AddMaxUsesPerUser adds v to the "max_uses_per_user" field.
func (u *PromotionActivityUpsertOne) AddMaxUsesPerUser(v int) *PromotionActivityUpsertOne {
	return u.Update(func(s *PromotionActivityUpsert) {
		s.AddMaxUsesPerUser(v)
	})
}

// UpdateMaxUsesPerUser sets the "max_uses_per_user" field to the value that was provided on create.
func (u *PromotionActivityUpsertOne) UpdateMaxUsesPerUser() *PromotionActivityUpsertOne {
	return u.Update(func(s *PromotionActivityUpsert) {
		s.UpdateMaxUsesPerUser()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PromotionActivityUpsertOne) SetUpdatedAt(v time.Time) *PromotionActivityUpsertOne {
	return u.Update(func(s *PromotionActivityUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PromotionActivityUpsertOne) UpdateUpdatedAt() *PromotionActivityUpsertOne {
	return u.Update(func(s *PromotionActivityUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PromotionActivityUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PromotionActivityCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PromotionActivityUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PromotionActivityUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PromotionActivityUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PromotionActivityCreateBulk is the builder for creating many PromotionActivity entities in bulk.
type PromotionActivityCreateBulk struct {
	config
	err      error
	builders []*PromotionActivityCreate
	conflict []sql.ConflictOption
}

// Save creates the PromotionActivity entities in the database.
func (_c *PromotionActivityCreateBulk) Save(ctx context.Context) ([]*PromotionActivity, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PromotionActivity, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PromotionActivityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PromotionActivityCreateBulk) SaveX(ctx context.Context) []*PromotionActivity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromotionActivityCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromotionActivityCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PromotionActivity.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PromotionActivityUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *PromotionActivityCreateBulk) OnConflict(opts ...sql.ConflictOption) *PromotionActivityUpsertBulk {
	_c.conflict = opts
	return &PromotionActivityUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PromotionActivity.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PromotionActivityCreateBulk) OnConflictColumns(columns ...string) *PromotionActivityUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PromotionActivityUpsertBulk{
		create: _c,
	}
}

// PromotionActivityUpsertBulk is the builder for "upsert"-ing
// a bulk of PromotionActivity nodes.
type PromotionActivityUpsertBulk struct {
	create *PromotionActivityCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PromotionActivity.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PromotionActivityUpsertBulk) UpdateNewValues() *PromotionActivityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(promotionactivity.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PromotionActivity.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PromotionActivityUpsertBulk) Ignore() *PromotionActivityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PromotionActivityUpsertBulk) DoNothing() *PromotionActivityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PromotionActivityCreateBulk.OnConflict
// documentation for more info.
func (u *PromotionActivityUpsertBulk) Update(set func(*PromotionActivityUpsert)) *PromotionActivityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PromotionActivityUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *PromotionActivityUpsertBulk) SetName(v string) *PromotionActivityUpsertBulk {
	return u.Update(func(s *PromotionActivityUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PromotionActivityUpsertBulk) UpdateName() *PromotionActivityUpsertBulk {
	return u.Update(func(s *PromotionActivityUpsert) {
		s.UpdateName()
	})
}

// SetActivityType sets the "activity_type" field.
func (u *PromotionActivityUpsertBulk) SetActivityType(v string) *PromotionActivityUpsertBulk {
	return u.Update(func(s *PromotionActivityUpsert) {
		s.SetActivityType(v)
	})
}

// UpdateActivityType sets the "activity_type" field to the value that was provided on create.
func (u *PromotionActivityUpsertBulk) UpdateActivityType() *PromotionActivityUpsertBulk {
	return u.Update(func(s *PromotionActivityUpsert) {
		s.UpdateActivityType()
	})
}

// SetEnabled sets the "enabled" field.
func (u *PromotionActivityUpsertBulk) SetEnabled(v bool) *PromotionActivityUpsertBulk {
	return u.Update(func(s *PromotionActivityUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *PromotionActivityUpsertBulk) UpdateEnabled() *PromotionActivityUpsertBulk {
	return u.Update(func(s *PromotionActivityUpsert) {
		s.UpdateEnabled()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *PromotionActivityUpsertBulk) SetStartsAt(v time.Time) *PromotionActivityUpsertBulk {
	return u.Update(func(s *PromotionActivityUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *PromotionActivityUpsertBulk) UpdateStartsAt() *PromotionActivityUpsertBulk {
	return u.Update(func(s *PromotionActivityUpsert) {
		s.UpdateStartsAt()
	})
}

// SetEndsAt sets the "ends_at" field.
func (u *PromotionActivityUpsertBulk) SetEndsAt(v time.Time) *PromotionActivityUpsertBulk {
	return u.Update(func(s *PromotionActivityUpsert) {
		s.SetEndsAt(v)
	})
}

// UpdateEndsAt sets the "ends_at" field to the value that was provided on create.
func (u *PromotionActivityUpsertBulk) UpdateEndsAt() *PromotionActivityUpsertBulk {
	return u.Update(func(s *PromotionActivityUpsert) {
		s.UpdateEndsAt()
	})
}

// SetMaxUsesPerUser sets the "max_uses_per_user" field.
func (u *PromotionActivityUpsertBulk) SetMaxUsesPerUser(v int) *PromotionActivityUpsertBulk {
	return u.Update(func(s *PromotionActivityUpsert) {
		s.SetMaxUsesPerUser(v)
	})
}

// AddMaxUsesPerUser adds v to the "max_uses_per_user" field.
func (u *PromotionActivityUpsertBulk) AddMaxUsesPerUser(v int) *PromotionActivityUpsertBulk {
	return u.Update(func(s *PromotionActivityUpsert) {
		s.AddMaxUsesPerUser(v)
	})
}

// UpdateMaxUsesPerUser sets the "max_uses_per_user" field to the value that was provided on create.
func (u *PromotionActivityUpsertBulk) UpdateMaxUsesPerUser() *PromotionActivityUpsertBulk {
	return u.Update(func(s *PromotionActivityUpsert) {
		s.UpdateMaxUsesPerUser()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PromotionActivityUpsertBulk) SetUpdatedAt(v time.Time) *PromotionActivityUpsertBulk {
	return u.Update(func(s *PromotionActivityUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PromotionActivityUpsertBulk) UpdateUpdatedAt() *PromotionActivityUpsertBulk {
	return u.Update(func(s *PromotionActivityUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PromotionActivityUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PromotionActivityCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PromotionActivityCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PromotionActivityUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
