// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/promotionactivity"
	"github.com/Wei-Shaw/sub2api/ent/promotionactivityparticipation"
	"github.com/Wei-Shaw/sub2api/ent/promotionactivityplan"
)

// PromotionActivityQuery is the builder for querying PromotionActivity entities.
type PromotionActivityQuery struct {
	config
	ctx                *QueryContext
	order              []promotionactivity.OrderOption
	inters             []Interceptor
	predicates         []predicate.PromotionActivity
	withPlanBonuses    *PromotionActivityPlanQuery
	withParticipations *PromotionActivityParticipationQuery
	modifiers          []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PromotionActivityQuery builder.
func (_q *PromotionActivityQuery) Where(ps ...predicate.PromotionActivity) *PromotionActivityQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *PromotionActivityQuery) Limit(limit int) *PromotionActivityQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *PromotionActivityQuery) Offset(offset int) *PromotionActivityQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *PromotionActivityQuery) Unique(unique bool) *PromotionActivityQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *PromotionActivityQuery) Order(o ...promotionactivity.OrderOption) *PromotionActivityQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryPlanBonuses chains the current query on the "plan_bonuses" edge.
func (_q *PromotionActivityQuery) QueryPlanBonuses() *PromotionActivityPlanQuery {
	query := (&PromotionActivityPlanClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(promotionactivity.Table, promotionactivity.FieldID, selector),
			sqlgraph.To(promotionactivityplan.Table, promotionactivityplan.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, promotionactivity.PlanBonusesTable, promotionactivity.PlanBonusesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryParticipations chains the current query on the "participations" edge.
func (_q *PromotionActivityQuery) QueryParticipations() *PromotionActivityParticipationQuery {
	query := (&PromotionActivityParticipationClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(promotionactivity.Table, promotionactivity.FieldID, selector),
			sqlgraph.To(promotionactivityparticipation.Table, promotionactivityparticipation.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, promotionactivity.ParticipationsTable, promotionactivity.ParticipationsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PromotionActivity entity from the query.
// Returns a *NotFoundError when no PromotionActivity was found.
func (_q *PromotionActivityQuery) First(ctx context.Context) (*PromotionActivity, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{promotionactivity.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *PromotionActivityQuery) FirstX(ctx context.Context) *PromotionActivity {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PromotionActivity ID from the query.
// Returns a *NotFoundError when no PromotionActivity ID was found.
func (_q *PromotionActivityQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{promotionactivity.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *PromotionActivityQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PromotionActivity entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PromotionActivity entity is found.
// Returns a *NotFoundError when no PromotionActivity entities are found.
func (_q *PromotionActivityQuery) Only(ctx context.Context) (*PromotionActivity, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{promotionactivity.Label}
	default:
		return nil, &NotSingularError{promotionactivity.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *PromotionActivityQuery) OnlyX(ctx context.Context) *PromotionActivity {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PromotionActivity ID in the query.
// Returns a *NotSingularError when more than one PromotionActivity ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *PromotionActivityQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{promotionactivity.Label}
	default:
		err = &NotSingularError{promotionactivity.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *PromotionActivityQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PromotionActivities.
func (_q *PromotionActivityQuery) All(ctx context.Context) ([]*PromotionActivity, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PromotionActivity, *PromotionActivityQuery]()
	return withInterceptors[[]*PromotionActivity](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *PromotionActivityQuery) AllX(ctx context.Context) []*PromotionActivity {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PromotionActivity IDs.
func (_q *PromotionActivityQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(promotionactivity.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *PromotionActivityQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *PromotionActivityQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*PromotionActivityQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *PromotionActivityQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *PromotionActivityQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *PromotionActivityQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PromotionActivityQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *PromotionActivityQuery) Clone() *PromotionActivityQuery {
	if _q == nil {
		return nil
	}
	return &PromotionActivityQuery{
		config:             _q.config,
		ctx:                _q.ctx.Clone(),
		order:              append([]promotionactivity.OrderOption{}, _q.order...),
		inters:             append([]Interceptor{}, _q.inters...),
		predicates:         append([]predicate.PromotionActivity{}, _q.predicates...),
		withPlanBonuses:    _q.withPlanBonuses.Clone(),
		withParticipations: _q.withParticipations.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithPlanBonuses tells the query-builder to eager-load the nodes that are connected to
// the "plan_bonuses" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PromotionActivityQuery) WithPlanBonuses(opts ...func(*PromotionActivityPlanQuery)) *PromotionActivityQuery {
	query := (&PromotionActivityPlanClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPlanBonuses = query
	return _q
}

// WithParticipations tells the query-builder to eager-load the nodes that are connected to
// the "participations" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PromotionActivityQuery) WithParticipations(opts ...func(*PromotionActivityParticipationQuery)) *PromotionActivityQuery {
	query := (&PromotionActivityParticipationClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withParticipations = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PromotionActivity.Query().
//		GroupBy(promotionactivity.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *PromotionActivityQuery) GroupBy(field string, fields ...string) *PromotionActivityGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PromotionActivityGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = promotionactivity.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.PromotionActivity.Query().
//		Select(promotionactivity.FieldName).
//		Scan(ctx, &v)
func (_q *PromotionActivityQuery) Select(fields ...string) *PromotionActivitySelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &PromotionActivitySelect{PromotionActivityQuery: _q}
	sbuild.label = promotionactivity.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PromotionActivitySelect configured with the given aggregations.
func (_q *PromotionActivityQuery) Aggregate(fns ...AggregateFunc) *PromotionActivitySelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *PromotionActivityQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !promotionactivity.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *PromotionActivityQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PromotionActivity, error) {
	var (
		nodes       = []*PromotionActivity{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withPlanBonuses != nil,
			_q.withParticipations != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PromotionActivity).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PromotionActivity{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withPlanBonuses; query != nil {
		if err := _q.loadPlanBonuses(ctx, query, nodes,
			func(n *PromotionActivity) { n.Edges.PlanBonuses = []*PromotionActivityPlan{} },
			func(n *PromotionActivity, e *PromotionActivityPlan) {
				n.Edges.PlanBonuses = append(n.Edges.PlanBonuses, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := _q.withParticipations; query != nil {
		if err := _q.loadParticipations(ctx, query, nodes,
			func(n *PromotionActivity) { n.Edges.Participations = []*PromotionActivityParticipation{} },
			func(n *PromotionActivity, e *PromotionActivityParticipation) {
				n.Edges.Participations = append(n.Edges.Participations, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *PromotionActivityQuery) loadPlanBonuses(ctx context.Context, query *PromotionActivityPlanQuery, nodes []*PromotionActivity, init func(*PromotionActivity), assign func(*PromotionActivity, *PromotionActivityPlan)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*PromotionActivity)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(promotionactivityplan.FieldActivityID)
	}
	query.Where(predicate.PromotionActivityPlan(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(promotionactivity.PlanBonusesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ActivityID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "activity_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *PromotionActivityQuery) loadParticipations(ctx context.Context, query *PromotionActivityParticipationQuery, nodes []*PromotionActivity, init func(*PromotionActivity), assign func(*PromotionActivity, *PromotionActivityParticipation)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*PromotionActivity)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(promotionactivityparticipation.FieldActivityID)
	}
	query.Where(predicate.PromotionActivityParticipation(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(promotionactivity.ParticipationsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ActivityID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "activity_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *PromotionActivityQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *PromotionActivityQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(promotionactivity.Table, promotionactivity.Columns, sqlgraph.NewFieldSpec(promotionactivity.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, promotionactivity.FieldID)
		for i := range fields {
			if fields[i] != promotionactivity.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *PromotionActivityQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(promotionactivity.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = promotionactivity.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *PromotionActivityQuery) ForUpdate(opts ...sql.LockOption) *PromotionActivityQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *PromotionActivityQuery) ForShare(opts ...sql.LockOption) *PromotionActivityQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// PromotionActivityGroupBy is the group-by builder for PromotionActivity entities.
type PromotionActivityGroupBy struct {
	selector
	build *PromotionActivityQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *PromotionActivityGroupBy) Aggregate(fns ...AggregateFunc) *PromotionActivityGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *PromotionActivityGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PromotionActivityQuery, *PromotionActivityGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *PromotionActivityGroupBy) sqlScan(ctx context.Context, root *PromotionActivityQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PromotionActivitySelect is the builder for selecting fields of PromotionActivity entities.
type PromotionActivitySelect struct {
	*PromotionActivityQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *PromotionActivitySelect) Aggregate(fns ...AggregateFunc) *PromotionActivitySelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *PromotionActivitySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PromotionActivityQuery, *PromotionActivitySelect](ctx, _s.PromotionActivityQuery, _s, _s.inters, v)
}

func (_s *PromotionActivitySelect) sqlScan(ctx context.Context, root *PromotionActivityQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
