// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/promotionactivity"
	"github.com/Wei-Shaw/sub2api/ent/promotionactivityplan"
)

// PromotionActivityPlanCreate is the builder for creating a PromotionActivityPlan entity.
type PromotionActivityPlanCreate struct {
	config
	mutation *PromotionActivityPlanMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetActivityID sets the "activity_id" field.
func (_c *PromotionActivityPlanCreate) SetActivityID(v int64) *PromotionActivityPlanCreate {
	_c.mutation.SetActivityID(v)
	return _c
}

// SetPlanID sets the "plan_id" field.
func (_c *PromotionActivityPlanCreate) SetPlanID(v int64) *PromotionActivityPlanCreate {
	_c.mutation.SetPlanID(v)
	return _c
}

// SetBonusDays sets the "bonus_days" field.
func (_c *PromotionActivityPlanCreate) SetBonusDays(v int) *PromotionActivityPlanCreate {
	_c.mutation.SetBonusDays(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PromotionActivityPlanCreate) SetCreatedAt(v time.Time) *PromotionActivityPlanCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PromotionActivityPlanCreate) SetNillableCreatedAt(v *time.Time) *PromotionActivityPlanCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PromotionActivityPlanCreate) SetUpdatedAt(v time.Time) *PromotionActivityPlanCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PromotionActivityPlanCreate) SetNillableUpdatedAt(v *time.Time) *PromotionActivityPlanCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetActivity sets the "activity" edge to the PromotionActivity entity.
func (_c *PromotionActivityPlanCreate) SetActivity(v *PromotionActivity) *PromotionActivityPlanCreate {
	return _c.SetActivityID(v.ID)
}

// Mutation returns the PromotionActivityPlanMutation object of the builder.
func (_c *PromotionActivityPlanCreate) Mutation() *PromotionActivityPlanMutation {
	return _c.mutation
}

// Save creates the PromotionActivityPlan in the database.
func (_c *PromotionActivityPlanCreate) Save(ctx context.Context) (*PromotionActivityPlan, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PromotionActivityPlanCreate) SaveX(ctx context.Context) *PromotionActivityPlan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromotionActivityPlanCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromotionActivityPlanCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PromotionActivityPlanCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := promotionactivityplan.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := promotionactivityplan.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PromotionActivityPlanCreate) check() error {
	if _, ok := _c.mutation.ActivityID(); !ok {
		return &ValidationError{Name: "activity_id", err: errors.New(`ent: missing required field "PromotionActivityPlan.activity_id"`)}
	}
	if v, ok := _c.mutation.ActivityID(); ok {
		if err := promotionactivityplan.ActivityIDValidator(v); err != nil {
			return &ValidationError{Name: "activity_id", err: fmt.Errorf(`ent: validator failed for field "PromotionActivityPlan.activity_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PlanID(); !ok {
		return &ValidationError{Name: "plan_id", err: errors.New(`ent: missing required field "PromotionActivityPlan.plan_id"`)}
	}
	if v, ok := _c.mutation.PlanID(); ok {
		if err := promotionactivityplan.PlanIDValidator(v); err != nil {
			return &ValidationError{Name: "plan_id", err: fmt.Errorf(`ent: validator failed for field "PromotionActivityPlan.plan_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BonusDays(); !ok {
		return &ValidationError{Name: "bonus_days", err: errors.New(`ent: missing required field "PromotionActivityPlan.bonus_days"`)}
	}
	if v, ok := _c.mutation.BonusDays(); ok {
		if err := promotionactivityplan.BonusDaysValidator(v); err != nil {
			return &ValidationError{Name: "bonus_days", err: fmt.Errorf(`ent: validator failed for field "PromotionActivityPlan.bonus_days": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PromotionActivityPlan.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PromotionActivityPlan.updated_at"`)}
	}
	if len(_c.mutation.ActivityIDs()) == 0 {
		return &ValidationError{Name: "activity", err: errors.New(`ent: missing required edge "PromotionActivityPlan.activity"`)}
	}
	return nil
}

func (_c *PromotionActivityPlanCreate) sqlSave(ctx context.Context) (*PromotionActivityPlan, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PromotionActivityPlanCreate) createSpec() (*PromotionActivityPlan, *sqlgraph.CreateSpec) {
	var (
		_node = &PromotionActivityPlan{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(promotionactivityplan.Table, sqlgraph.NewFieldSpec(promotionactivityplan.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.PlanID(); ok {
		_spec.SetField(promotionactivityplan.FieldPlanID, field.TypeInt64, value)
		_node.PlanID = value
	}
	if value, ok := _c.mutation.BonusDays(); ok {
		_spec.SetField(promotionactivityplan.FieldBonusDays, field.TypeInt, value)
		_node.BonusDays = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(promotionactivityplan.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(promotionactivityplan.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ActivityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   promotionactivityplan.ActivityTable,
			Columns: []string{promotionactivityplan.ActivityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(promotionactivity.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ActivityID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PromotionActivityPlan.Create().
//		SetActivityID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PromotionActivityPlanUpsert) {
//			SetActivityID(v+v).
//		}).
//		Exec(ctx)
func (_c *PromotionActivityPlanCreate) OnConflict(opts ...sql.ConflictOption) *PromotionActivityPlanUpsertOne {
	_c.conflict = opts
	return &PromotionActivityPlanUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PromotionActivityPlan.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PromotionActivityPlanCreate) OnConflictColumns(columns ...string) *PromotionActivityPlanUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PromotionActivityPlanUpsertOne{
		create: _c,
	}
}

type (
	// PromotionActivityPlanUpsertOne is the builder for "upsert"-ing
	//  one PromotionActivityPlan node.
	PromotionActivityPlanUpsertOne struct {
		create *PromotionActivityPlanCreate
	}

	// PromotionActivityPlanUpsert is the "OnConflict" setter.
	PromotionActivityPlanUpsert struct {
		*sql.UpdateSet
	}
)

// SetActivityID sets the "activity_id" field.
func (u *PromotionActivityPlanUpsert) SetActivityID(v int64) *PromotionActivityPlanUpsert {
	u.Set(promotionactivityplan.FieldActivityID, v)
	return u
}

// UpdateActivityID sets the "activity_id" field to the value that was provided on create.
func (u *PromotionActivityPlanUpsert) UpdateActivityID() *PromotionActivityPlanUpsert {
	u.SetExcluded(promotionactivityplan.FieldActivityID)
	return u
}

// SetPlanID sets the "plan_id" field.
func (u *PromotionActivityPlanUpsert) SetPlanID(v int64) *PromotionActivityPlanUpsert {
	u.Set(promotionactivityplan.FieldPlanID, v)
	return u
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *PromotionActivityPlanUpsert) UpdatePlanID() *PromotionActivityPlanUpsert {
	u.SetExcluded(promotionactivityplan.FieldPlanID)
	return u
}

// AddPlanID adds v to the "plan_id" field.
func (u *PromotionActivityPlanUpsert) AddPlanID(v int64) *PromotionActivityPlanUpsert {
	u.Add(promotionactivityplan.FieldPlanID, v)
	return u
}

// SetBonusDays sets the "bonus_days" field.
func (u *PromotionActivityPlanUpsert) SetBonusDays(v int) *PromotionActivityPlanUpsert {
	u.Set(promotionactivityplan.FieldBonusDays, v)
	return u
}

// UpdateBonusDays sets the "bonus_days" field to the value that was provided on create.
func (u *PromotionActivityPlanUpsert) UpdateBonusDays() *PromotionActivityPlanUpsert {
	u.SetExcluded(promotionactivityplan.FieldBonusDays)
	return u
}

// AddBonusDays adds v to the "bonus_days" field.
func (u *PromotionActivityPlanUpsert) AddBonusDays(v int) *PromotionActivityPlanUpsert {
	u.Add(promotionactivityplan.FieldBonusDays, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PromotionActivityPlanUpsert) SetUpdatedAt(v time.Time) *PromotionActivityPlanUpsert {
	u.Set(promotionactivityplan.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PromotionActivityPlanUpsert) UpdateUpdatedAt() *PromotionActivityPlanUpsert {
	u.SetExcluded(promotionactivityplan.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PromotionActivityPlan.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PromotionActivityPlanUpsertOne) UpdateNewValues() *PromotionActivityPlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(promotionactivityplan.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PromotionActivityPlan.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PromotionActivityPlanUpsertOne) Ignore() *PromotionActivityPlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PromotionActivityPlanUpsertOne) DoNothing() *PromotionActivityPlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PromotionActivityPlanCreate.OnConflict
// documentation for more info.
func (u *PromotionActivityPlanUpsertOne) Update(set func(*PromotionActivityPlanUpsert)) *PromotionActivityPlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PromotionActivityPlanUpsert{UpdateSet: update})
	}))
	return u
}

// SetActivityID sets the "activity_id" field.
func (u *PromotionActivityPlanUpsertOne) SetActivityID(v int64) *PromotionActivityPlanUpsertOne {
	return u.Update(func(s *PromotionActivityPlanUpsert) {
		s.SetActivityID(v)
	})
}

// UpdateActivityID sets the "activity_id" field to the value that was provided on create.
func (u *PromotionActivityPlanUpsertOne) UpdateActivityID() *PromotionActivityPlanUpsertOne {
	return u.Update(func(s *PromotionActivityPlanUpsert) {
		s.UpdateActivityID()
	})
}

// SetPlanID sets the "plan_id" field.
func (u *PromotionActivityPlanUpsertOne) SetPlanID(v int64) *PromotionActivityPlanUpsertOne {
	return u.Update(func(s *PromotionActivityPlanUpsert) {
		s.SetPlanID(v)
	})
}

// AddPlanID adds v to the "plan_id" field.
func (u *PromotionActivityPlanUpsertOne) AddPlanID(v int64) *PromotionActivityPlanUpsertOne {
	return u.Update(func(s *PromotionActivityPlanUpsert) {
		s.AddPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *PromotionActivityPlanUpsertOne) UpdatePlanID() *PromotionActivityPlanUpsertOne {
	return u.Update(func(s *PromotionActivityPlanUpsert) {
		s.UpdatePlanID()
	})
}

// SetBonusDays sets the "bonus_days" field.
func (u *PromotionActivityPlanUpsertOne) SetBonusDays(v int) *PromotionActivityPlanUpsertOne {
	return u.Update(func(s *PromotionActivityPlanUpsert) {
		s.SetBonusDays(v)
	})
}

// AddBonusDays adds v to the "bonus_days" field.
func (u *PromotionActivityPlanUpsertOne) AddBonusDays(v int) *PromotionActivityPlanUpsertOne {
	return u.Update(func(s *PromotionActivityPlanUpsert) {
		s.AddBonusDays(v)
	})
}

// UpdateBonusDays sets the "bonus_days" field to the value that was provided on create.
func (u *PromotionActivityPlanUpsertOne) UpdateBonusDays() *PromotionActivityPlanUpsertOne {
	return u.Update(func(s *PromotionActivityPlanUpsert) {
		s.UpdateBonusDays()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PromotionActivityPlanUpsertOne) SetUpdatedAt(v time.Time) *PromotionActivityPlanUpsertOne {
	return u.Update(func(s *PromotionActivityPlanUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PromotionActivityPlanUpsertOne) UpdateUpdatedAt() *PromotionActivityPlanUpsertOne {
	return u.Update(func(s *PromotionActivityPlanUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PromotionActivityPlanUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PromotionActivityPlanCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PromotionActivityPlanUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PromotionActivityPlanUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PromotionActivityPlanUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PromotionActivityPlanCreateBulk is the builder for creating many PromotionActivityPlan entities in bulk.
type PromotionActivityPlanCreateBulk struct {
	config
	err      error
	builders []*PromotionActivityPlanCreate
	conflict []sql.ConflictOption
}

// Save creates the PromotionActivityPlan entities in the database.
func (_c *PromotionActivityPlanCreateBulk) Save(ctx context.Context) ([]*PromotionActivityPlan, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PromotionActivityPlan, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PromotionActivityPlanMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PromotionActivityPlanCreateBulk) SaveX(ctx context.Context) []*PromotionActivityPlan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromotionActivityPlanCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromotionActivityPlanCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PromotionActivityPlan.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PromotionActivityPlanUpsert) {
//			SetActivityID(v+v).
//		}).
//		Exec(ctx)
func (_c *PromotionActivityPlanCreateBulk) OnConflict(opts ...sql.ConflictOption) *PromotionActivityPlanUpsertBulk {
	_c.conflict = opts
	return &PromotionActivityPlanUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PromotionActivityPlan.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PromotionActivityPlanCreateBulk) OnConflictColumns(columns ...string) *PromotionActivityPlanUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PromotionActivityPlanUpsertBulk{
		create: _c,
	}
}

// PromotionActivityPlanUpsertBulk is the builder for "upsert"-ing
// a bulk of PromotionActivityPlan nodes.
type PromotionActivityPlanUpsertBulk struct {
	create *PromotionActivityPlanCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PromotionActivityPlan.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PromotionActivityPlanUpsertBulk) UpdateNewValues() *PromotionActivityPlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(promotionactivityplan.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PromotionActivityPlan.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PromotionActivityPlanUpsertBulk) Ignore() *PromotionActivityPlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PromotionActivityPlanUpsertBulk) DoNothing() *PromotionActivityPlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PromotionActivityPlanCreateBulk.OnConflict
// documentation for more info.
func (u *PromotionActivityPlanUpsertBulk) Update(set func(*PromotionActivityPlanUpsert)) *PromotionActivityPlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PromotionActivityPlanUpsert{UpdateSet: update})
	}))
	return u
}

// SetActivityID sets the "activity_id" field.
func (u *PromotionActivityPlanUpsertBulk) SetActivityID(v int64) *PromotionActivityPlanUpsertBulk {
	return u.Update(func(s *PromotionActivityPlanUpsert) {
		s.SetActivityID(v)
	})
}

// UpdateActivityID sets the "activity_id" field to the value that was provided on create.
func (u *PromotionActivityPlanUpsertBulk) UpdateActivityID() *PromotionActivityPlanUpsertBulk {
	return u.Update(func(s *PromotionActivityPlanUpsert) {
		s.UpdateActivityID()
	})
}

// SetPlanID sets the "plan_id" field.
func (u *PromotionActivityPlanUpsertBulk) SetPlanID(v int64) *PromotionActivityPlanUpsertBulk {
	return u.Update(func(s *PromotionActivityPlanUpsert) {
		s.SetPlanID(v)
	})
}

// AddPlanID adds v to the "plan_id" field.
func (u *PromotionActivityPlanUpsertBulk) AddPlanID(v int64) *PromotionActivityPlanUpsertBulk {
	return u.Update(func(s *PromotionActivityPlanUpsert) {
		s.AddPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *PromotionActivityPlanUpsertBulk) UpdatePlanID() *PromotionActivityPlanUpsertBulk {
	return u.Update(func(s *PromotionActivityPlanUpsert) {
		s.UpdatePlanID()
	})
}

// SetBonusDays sets the "bonus_days" field.
func (u *PromotionActivityPlanUpsertBulk) SetBonusDays(v int) *PromotionActivityPlanUpsertBulk {
	return u.Update(func(s *PromotionActivityPlanUpsert) {
		s.SetBonusDays(v)
	})
}

// AddBonusDays adds v to the "bonus_days" field.
func (u *PromotionActivityPlanUpsertBulk) AddBonusDays(v int) *PromotionActivityPlanUpsertBulk {
	return u.Update(func(s *PromotionActivityPlanUpsert) {
		s.AddBonusDays(v)
	})
}

// UpdateBonusDays sets the "bonus_days" field to the value that was provided on create.
func (u *PromotionActivityPlanUpsertBulk) UpdateBonusDays() *PromotionActivityPlanUpsertBulk {
	return u.Update(func(s *PromotionActivityPlanUpsert) {
		s.UpdateBonusDays()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PromotionActivityPlanUpsertBulk) SetUpdatedAt(v time.Time) *PromotionActivityPlanUpsertBulk {
	return u.Update(func(s *PromotionActivityPlanUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PromotionActivityPlanUpsertBulk) UpdateUpdatedAt() *PromotionActivityPlanUpsertBulk {
	return u.Update(func(s *PromotionActivityPlanUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PromotionActivityPlanUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PromotionActivityPlanCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PromotionActivityPlanCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PromotionActivityPlanUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
