// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/promotionactivity"
)

// PromotionActivity is the model entity for the PromotionActivity schema.
type PromotionActivity struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// ActivityType holds the value of the "activity_type" field.
	ActivityType string `json:"activity_type,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// StartsAt holds the value of the "starts_at" field.
	StartsAt time.Time `json:"starts_at,omitempty"`
	// EndsAt holds the value of the "ends_at" field.
	EndsAt time.Time `json:"ends_at,omitempty"`
	// MaxUsesPerUser holds the value of the "max_uses_per_user" field.
	MaxUsesPerUser int `json:"max_uses_per_user,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PromotionActivityQuery when eager-loading is set.
	Edges        PromotionActivityEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PromotionActivityEdges holds the relations/edges for other nodes in the graph.
type PromotionActivityEdges struct {
	// PlanBonuses holds the value of the plan_bonuses edge.
	PlanBonuses []*PromotionActivityPlan `json:"plan_bonuses,omitempty"`
	// Participations holds the value of the participations edge.
	Participations []*PromotionActivityParticipation `json:"participations,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// PlanBonusesOrErr returns the PlanBonuses value or an error if the edge
// was not loaded in eager-loading.
func (e PromotionActivityEdges) PlanBonusesOrErr() ([]*PromotionActivityPlan, error) {
	if e.loadedTypes[0] {
		return e.PlanBonuses, nil
	}
	return nil, &NotLoadedError{edge: "plan_bonuses"}
}

// ParticipationsOrErr returns the Participations value or an error if the edge
// was not loaded in eager-loading.
func (e PromotionActivityEdges) ParticipationsOrErr() ([]*PromotionActivityParticipation, error) {
	if e.loadedTypes[1] {
		return e.Participations, nil
	}
	return nil, &NotLoadedError{edge: "participations"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PromotionActivity) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case promotionactivity.FieldEnabled:
			values[i] = new(sql.NullBool)
		case promotionactivity.FieldID, promotionactivity.FieldMaxUsesPerUser:
			values[i] = new(sql.NullInt64)
		case promotionactivity.FieldName, promotionactivity.FieldActivityType:
			values[i] = new(sql.NullString)
		case promotionactivity.FieldStartsAt, promotionactivity.FieldEndsAt, promotionactivity.FieldCreatedAt, promotionactivity.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PromotionActivity fields.
func (_m *PromotionActivity) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case promotionactivity.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case promotionactivity.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case promotionactivity.FieldActivityType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field activity_type", values[i])
			} else if value.Valid {
				_m.ActivityType = value.String
			}
		case promotionactivity.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case promotionactivity.FieldStartsAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field starts_at", values[i])
			} else if value.Valid {
				_m.StartsAt = value.Time
			}
		case promotionactivity.FieldEndsAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field ends_at", values[i])
			} else if value.Valid {
				_m.EndsAt = value.Time
			}
		case promotionactivity.FieldMaxUsesPerUser:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_uses_per_user", values[i])
			} else if value.Valid {
				_m.MaxUsesPerUser = int(value.Int64)
			}
		case promotionactivity.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case promotionactivity.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PromotionActivity.
// This includes values selected through modifiers, order, etc.
func (_m *PromotionActivity) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPlanBonuses queries the "plan_bonuses" edge of the PromotionActivity entity.
func (_m *PromotionActivity) QueryPlanBonuses() *PromotionActivityPlanQuery {
	return NewPromotionActivityClient(_m.config).QueryPlanBonuses(_m)
}

// QueryParticipations queries the "participations" edge of the PromotionActivity entity.
func (_m *PromotionActivity) QueryParticipations() *PromotionActivityParticipationQuery {
	return NewPromotionActivityClient(_m.config).QueryParticipations(_m)
}

// Update returns a builder for updating this PromotionActivity.
// Note that you need to call PromotionActivity.Unwrap() before calling this method if this PromotionActivity
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PromotionActivity) Update() *PromotionActivityUpdateOne {
	return NewPromotionActivityClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PromotionActivity entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PromotionActivity) Unwrap() *PromotionActivity {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PromotionActivity is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PromotionActivity) String() string {
	var builder strings.Builder
	builder.WriteString("PromotionActivity(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("activity_type=")
	builder.WriteString(_m.ActivityType)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("starts_at=")
	builder.WriteString(_m.StartsAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("ends_at=")
	builder.WriteString(_m.EndsAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("max_uses_per_user=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxUsesPerUser))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PromotionActivities is a parsable slice of PromotionActivity.
type PromotionActivities []*PromotionActivity
