// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/promotionactivity"
	"github.com/Wei-Shaw/sub2api/ent/promotionactivityplan"
)

// PromotionActivityPlanUpdate is the builder for updating PromotionActivityPlan entities.
type PromotionActivityPlanUpdate struct {
	config
	hooks    []Hook
	mutation *PromotionActivityPlanMutation
}

// Where appends a list predicates to the PromotionActivityPlanUpdate builder.
func (_u *PromotionActivityPlanUpdate) Where(ps ...predicate.PromotionActivityPlan) *PromotionActivityPlanUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetActivityID sets the "activity_id" field.
func (_u *PromotionActivityPlanUpdate) SetActivityID(v int64) *PromotionActivityPlanUpdate {
	_u.mutation.SetActivityID(v)
	return _u
}

// SetNillableActivityID sets the "activity_id" field if the given value is not nil.
func (_u *PromotionActivityPlanUpdate) SetNillableActivityID(v *int64) *PromotionActivityPlanUpdate {
	if v != nil {
		_u.SetActivityID(*v)
	}
	return _u
}

// SetPlanID sets the "plan_id" field.
func (_u *PromotionActivityPlanUpdate) SetPlanID(v int64) *PromotionActivityPlanUpdate {
	_u.mutation.ResetPlanID()
	_u.mutation.SetPlanID(v)
	return _u
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (_u *PromotionActivityPlanUpdate) SetNillablePlanID(v *int64) *PromotionActivityPlanUpdate {
	if v != nil {
		_u.SetPlanID(*v)
	}
	return _u
}

// AddPlanID adds value to the "plan_id" field.
func (_u *PromotionActivityPlanUpdate) AddPlanID(v int64) *PromotionActivityPlanUpdate {
	_u.mutation.AddPlanID(v)
	return _u
}

// SetBonusDays sets the "bonus_days" field.
func (_u *PromotionActivityPlanUpdate) SetBonusDays(v int) *PromotionActivityPlanUpdate {
	_u.mutation.ResetBonusDays()
	_u.mutation.SetBonusDays(v)
	return _u
}

// SetNillableBonusDays sets the "bonus_days" field if the given value is not nil.
func (_u *PromotionActivityPlanUpdate) SetNillableBonusDays(v *int) *PromotionActivityPlanUpdate {
	if v != nil {
		_u.SetBonusDays(*v)
	}
	return _u
}

// AddBonusDays adds value to the "bonus_days" field.
func (_u *PromotionActivityPlanUpdate) AddBonusDays(v int) *PromotionActivityPlanUpdate {
	_u.mutation.AddBonusDays(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PromotionActivityPlanUpdate) SetUpdatedAt(v time.Time) *PromotionActivityPlanUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetActivity sets the "activity" edge to the PromotionActivity entity.
func (_u *PromotionActivityPlanUpdate) SetActivity(v *PromotionActivity) *PromotionActivityPlanUpdate {
	return _u.SetActivityID(v.ID)
}

// Mutation returns the PromotionActivityPlanMutation object of the builder.
func (_u *PromotionActivityPlanUpdate) Mutation() *PromotionActivityPlanMutation {
	return _u.mutation
}

// ClearActivity clears the "activity" edge to the PromotionActivity entity.
func (_u *PromotionActivityPlanUpdate) ClearActivity() *PromotionActivityPlanUpdate {
	_u.mutation.ClearActivity()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PromotionActivityPlanUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PromotionActivityPlanUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PromotionActivityPlanUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PromotionActivityPlanUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PromotionActivityPlanUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := promotionactivityplan.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PromotionActivityPlanUpdate) check() error {
	if v, ok := _u.mutation.ActivityID(); ok {
		if err := promotionactivityplan.ActivityIDValidator(v); err != nil {
			return &ValidationError{Name: "activity_id", err: fmt.Errorf(`ent: validator failed for field "PromotionActivityPlan.activity_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PlanID(); ok {
		if err := promotionactivityplan.PlanIDValidator(v); err != nil {
			return &ValidationError{Name: "plan_id", err: fmt.Errorf(`ent: validator failed for field "PromotionActivityPlan.plan_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BonusDays(); ok {
		if err := promotionactivityplan.BonusDaysValidator(v); err != nil {
			return &ValidationError{Name: "bonus_days", err: fmt.Errorf(`ent: validator failed for field "PromotionActivityPlan.bonus_days": %w`, err)}
		}
	}
	if _u.mutation.ActivityCleared() && len(_u.mutation.ActivityIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PromotionActivityPlan.activity"`)
	}
	return nil
}

func (_u *PromotionActivityPlanUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(promotionactivityplan.Table, promotionactivityplan.Columns, sqlgraph.NewFieldSpec(promotionactivityplan.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PlanID(); ok {
		_spec.SetField(promotionactivityplan.FieldPlanID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPlanID(); ok {
		_spec.AddField(promotionactivityplan.FieldPlanID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.BonusDays(); ok {
		_spec.SetField(promotionactivityplan.FieldBonusDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBonusDays(); ok {
		_spec.AddField(promotionactivityplan.FieldBonusDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(promotionactivityplan.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ActivityCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   promotionactivityplan.ActivityTable,
			Columns: []string{promotionactivityplan.ActivityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(promotionactivity.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActivityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   promotionactivityplan.ActivityTable,
			Columns: []string{promotionactivityplan.ActivityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(promotionactivity.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{promotionactivityplan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PromotionActivityPlanUpdateOne is the builder for updating a single PromotionActivityPlan entity.
type PromotionActivityPlanUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PromotionActivityPlanMutation
}

// SetActivityID sets the "activity_id" field.
func (_u *PromotionActivityPlanUpdateOne) SetActivityID(v int64) *PromotionActivityPlanUpdateOne {
	_u.mutation.SetActivityID(v)
	return _u
}

// SetNillableActivityID sets the "activity_id" field if the given value is not nil.
func (_u *PromotionActivityPlanUpdateOne) SetNillableActivityID(v *int64) *PromotionActivityPlanUpdateOne {
	if v != nil {
		_u.SetActivityID(*v)
	}
	return _u
}

// SetPlanID sets the "plan_id" field.
func (_u *PromotionActivityPlanUpdateOne) SetPlanID(v int64) *PromotionActivityPlanUpdateOne {
	_u.mutation.ResetPlanID()
	_u.mutation.SetPlanID(v)
	return _u
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (_u *PromotionActivityPlanUpdateOne) SetNillablePlanID(v *int64) *PromotionActivityPlanUpdateOne {
	if v != nil {
		_u.SetPlanID(*v)
	}
	return _u
}

// AddPlanID adds value to the "plan_id" field.
func (_u *PromotionActivityPlanUpdateOne) AddPlanID(v int64) *PromotionActivityPlanUpdateOne {
	_u.mutation.AddPlanID(v)
	return _u
}

// SetBonusDays sets the "bonus_days" field.
func (_u *PromotionActivityPlanUpdateOne) SetBonusDays(v int) *PromotionActivityPlanUpdateOne {
	_u.mutation.ResetBonusDays()
	_u.mutation.SetBonusDays(v)
	return _u
}

// SetNillableBonusDays sets the "bonus_days" field if the given value is not nil.
func (_u *PromotionActivityPlanUpdateOne) SetNillableBonusDays(v *int) *PromotionActivityPlanUpdateOne {
	if v != nil {
		_u.SetBonusDays(*v)
	}
	return _u
}

// AddBonusDays adds value to the "bonus_days" field.
func (_u *PromotionActivityPlanUpdateOne) AddBonusDays(v int) *PromotionActivityPlanUpdateOne {
	_u.mutation.AddBonusDays(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PromotionActivityPlanUpdateOne) SetUpdatedAt(v time.Time) *PromotionActivityPlanUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetActivity sets the "activity" edge to the PromotionActivity entity.
func (_u *PromotionActivityPlanUpdateOne) SetActivity(v *PromotionActivity) *PromotionActivityPlanUpdateOne {
	return _u.SetActivityID(v.ID)
}

// Mutation returns the PromotionActivityPlanMutation object of the builder.
func (_u *PromotionActivityPlanUpdateOne) Mutation() *PromotionActivityPlanMutation {
	return _u.mutation
}

// ClearActivity clears the "activity" edge to the PromotionActivity entity.
func (_u *PromotionActivityPlanUpdateOne) ClearActivity() *PromotionActivityPlanUpdateOne {
	_u.mutation.ClearActivity()
	return _u
}

// Where appends a list predicates to the PromotionActivityPlanUpdate builder.
func (_u *PromotionActivityPlanUpdateOne) Where(ps ...predicate.PromotionActivityPlan) *PromotionActivityPlanUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PromotionActivityPlanUpdateOne) Select(field string, fields ...string) *PromotionActivityPlanUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PromotionActivityPlan entity.
func (_u *PromotionActivityPlanUpdateOne) Save(ctx context.Context) (*PromotionActivityPlan, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PromotionActivityPlanUpdateOne) SaveX(ctx context.Context) *PromotionActivityPlan {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PromotionActivityPlanUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PromotionActivityPlanUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PromotionActivityPlanUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := promotionactivityplan.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PromotionActivityPlanUpdateOne) check() error {
	if v, ok := _u.mutation.ActivityID(); ok {
		if err := promotionactivityplan.ActivityIDValidator(v); err != nil {
			return &ValidationError{Name: "activity_id", err: fmt.Errorf(`ent: validator failed for field "PromotionActivityPlan.activity_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PlanID(); ok {
		if err := promotionactivityplan.PlanIDValidator(v); err != nil {
			return &ValidationError{Name: "plan_id", err: fmt.Errorf(`ent: validator failed for field "PromotionActivityPlan.plan_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BonusDays(); ok {
		if err := promotionactivityplan.BonusDaysValidator(v); err != nil {
			return &ValidationError{Name: "bonus_days", err: fmt.Errorf(`ent: validator failed for field "PromotionActivityPlan.bonus_days": %w`, err)}
		}
	}
	if _u.mutation.ActivityCleared() && len(_u.mutation.ActivityIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PromotionActivityPlan.activity"`)
	}
	return nil
}

func (_u *PromotionActivityPlanUpdateOne) sqlSave(ctx context.Context) (_node *PromotionActivityPlan, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(promotionactivityplan.Table, promotionactivityplan.Columns, sqlgraph.NewFieldSpec(promotionactivityplan.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PromotionActivityPlan.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, promotionactivityplan.FieldID)
		for _, f := range fields {
			if !promotionactivityplan.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != promotionactivityplan.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PlanID(); ok {
		_spec.SetField(promotionactivityplan.FieldPlanID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPlanID(); ok {
		_spec.AddField(promotionactivityplan.FieldPlanID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.BonusDays(); ok {
		_spec.SetField(promotionactivityplan.FieldBonusDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBonusDays(); ok {
		_spec.AddField(promotionactivityplan.FieldBonusDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(promotionactivityplan.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ActivityCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   promotionactivityplan.ActivityTable,
			Columns: []string{promotionactivityplan.ActivityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(promotionactivity.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActivityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   promotionactivityplan.ActivityTable,
			Columns: []string{promotionactivityplan.ActivityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(promotionactivity.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PromotionActivityPlan{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{promotionactivityplan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
