// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionconcurrencyentitlement"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// SubscriptionConcurrencyEntitlement is the model entity for the SubscriptionConcurrencyEntitlement schema.
type SubscriptionConcurrencyEntitlement struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// SubscriptionID holds the value of the "subscription_id" field.
	SubscriptionID int64 `json:"subscription_id,omitempty"`
	// SourceOrderID holds the value of the "source_order_id" field.
	SourceOrderID *int64 `json:"source_order_id,omitempty"`
	// maximum user concurrency during this entitlement window
	Concurrency int `json:"concurrency,omitempty"`
	// StartsAt holds the value of the "starts_at" field.
	StartsAt time.Time `json:"starts_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SubscriptionConcurrencyEntitlementQuery when eager-loading is set.
	Edges        SubscriptionConcurrencyEntitlementEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SubscriptionConcurrencyEntitlementEdges holds the relations/edges for other nodes in the graph.
type SubscriptionConcurrencyEntitlementEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Subscription holds the value of the subscription edge.
	Subscription *UserSubscription `json:"subscription,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionConcurrencyEntitlementEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// SubscriptionOrErr returns the Subscription value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionConcurrencyEntitlementEdges) SubscriptionOrErr() (*UserSubscription, error) {
	if e.Subscription != nil {
		return e.Subscription, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: usersubscription.Label}
	}
	return nil, &NotLoadedError{edge: "subscription"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SubscriptionConcurrencyEntitlement) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case subscriptionconcurrencyentitlement.FieldID, subscriptionconcurrencyentitlement.FieldUserID, subscriptionconcurrencyentitlement.FieldSubscriptionID, subscriptionconcurrencyentitlement.FieldSourceOrderID, subscriptionconcurrencyentitlement.FieldConcurrency:
			values[i] = new(sql.NullInt64)
		case subscriptionconcurrencyentitlement.FieldCreatedAt, subscriptionconcurrencyentitlement.FieldUpdatedAt, subscriptionconcurrencyentitlement.FieldStartsAt, subscriptionconcurrencyentitlement.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SubscriptionConcurrencyEntitlement fields.
func (_m *SubscriptionConcurrencyEntitlement) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case subscriptionconcurrencyentitlement.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case subscriptionconcurrencyentitlement.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case subscriptionconcurrencyentitlement.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case subscriptionconcurrencyentitlement.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case subscriptionconcurrencyentitlement.FieldSubscriptionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_id", values[i])
			} else if value.Valid {
				_m.SubscriptionID = value.Int64
			}
		case subscriptionconcurrencyentitlement.FieldSourceOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field source_order_id", values[i])
			} else if value.Valid {
				_m.SourceOrderID = new(int64)
				*_m.SourceOrderID = value.Int64
			}
		case subscriptionconcurrencyentitlement.FieldConcurrency:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field concurrency", values[i])
			} else if value.Valid {
				_m.Concurrency = int(value.Int64)
			}
		case subscriptionconcurrencyentitlement.FieldStartsAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field starts_at", values[i])
			} else if value.Valid {
				_m.StartsAt = value.Time
			}
		case subscriptionconcurrencyentitlement.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SubscriptionConcurrencyEntitlement.
// This includes values selected through modifiers, order, etc.
func (_m *SubscriptionConcurrencyEntitlement) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the SubscriptionConcurrencyEntitlement entity.
func (_m *SubscriptionConcurrencyEntitlement) QueryUser() *UserQuery {
	return NewSubscriptionConcurrencyEntitlementClient(_m.config).QueryUser(_m)
}

// QuerySubscription queries the "subscription" edge of the SubscriptionConcurrencyEntitlement entity.
func (_m *SubscriptionConcurrencyEntitlement) QuerySubscription() *UserSubscriptionQuery {
	return NewSubscriptionConcurrencyEntitlementClient(_m.config).QuerySubscription(_m)
}

// Update returns a builder for updating this SubscriptionConcurrencyEntitlement.
// Note that you need to call SubscriptionConcurrencyEntitlement.Unwrap() before calling this method if this SubscriptionConcurrencyEntitlement
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SubscriptionConcurrencyEntitlement) Update() *SubscriptionConcurrencyEntitlementUpdateOne {
	return NewSubscriptionConcurrencyEntitlementClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SubscriptionConcurrencyEntitlement entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SubscriptionConcurrencyEntitlement) Unwrap() *SubscriptionConcurrencyEntitlement {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SubscriptionConcurrencyEntitlement is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SubscriptionConcurrencyEntitlement) String() string {
	var builder strings.Builder
	builder.WriteString("SubscriptionConcurrencyEntitlement(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("subscription_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SubscriptionID))
	builder.WriteString(", ")
	if v := _m.SourceOrderID; v != nil {
		builder.WriteString("source_order_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("concurrency=")
	builder.WriteString(fmt.Sprintf("%v", _m.Concurrency))
	builder.WriteString(", ")
	builder.WriteString("starts_at=")
	builder.WriteString(_m.StartsAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SubscriptionConcurrencyEntitlements is a parsable slice of SubscriptionConcurrencyEntitlement.
type SubscriptionConcurrencyEntitlements []*SubscriptionConcurrencyEntitlement
