// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionearlyresetentitlement"
)

// SubscriptionEarlyResetEntitlementUpdate is the builder for updating SubscriptionEarlyResetEntitlement entities.
type SubscriptionEarlyResetEntitlementUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionEarlyResetEntitlementMutation
}

// Where appends a list predicates to the SubscriptionEarlyResetEntitlementUpdate builder.
func (_u *SubscriptionEarlyResetEntitlementUpdate) Where(ps ...predicate.SubscriptionEarlyResetEntitlement) *SubscriptionEarlyResetEntitlementUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionEarlyResetEntitlementUpdate) SetUpdatedAt(v time.Time) *SubscriptionEarlyResetEntitlementUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SubscriptionEarlyResetEntitlementUpdate) SetUserID(v int64) *SubscriptionEarlyResetEntitlementUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SubscriptionEarlyResetEntitlementUpdate) SetNillableUserID(v *int64) *SubscriptionEarlyResetEntitlementUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *SubscriptionEarlyResetEntitlementUpdate) AddUserID(v int64) *SubscriptionEarlyResetEntitlementUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *SubscriptionEarlyResetEntitlementUpdate) SetSubscriptionID(v int64) *SubscriptionEarlyResetEntitlementUpdate {
	_u.mutation.ResetSubscriptionID()
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *SubscriptionEarlyResetEntitlementUpdate) SetNillableSubscriptionID(v *int64) *SubscriptionEarlyResetEntitlementUpdate {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// AddSubscriptionID adds value to the "subscription_id" field.
func (_u *SubscriptionEarlyResetEntitlementUpdate) AddSubscriptionID(v int64) *SubscriptionEarlyResetEntitlementUpdate {
	_u.mutation.AddSubscriptionID(v)
	return _u
}

// SetSourceOrderID sets the "source_order_id" field.
func (_u *SubscriptionEarlyResetEntitlementUpdate) SetSourceOrderID(v int64) *SubscriptionEarlyResetEntitlementUpdate {
	_u.mutation.ResetSourceOrderID()
	_u.mutation.SetSourceOrderID(v)
	return _u
}

// SetNillableSourceOrderID sets the "source_order_id" field if the given value is not nil.
func (_u *SubscriptionEarlyResetEntitlementUpdate) SetNillableSourceOrderID(v *int64) *SubscriptionEarlyResetEntitlementUpdate {
	if v != nil {
		_u.SetSourceOrderID(*v)
	}
	return _u
}

// AddSourceOrderID adds value to the "source_order_id" field.
func (_u *SubscriptionEarlyResetEntitlementUpdate) AddSourceOrderID(v int64) *SubscriptionEarlyResetEntitlementUpdate {
	_u.mutation.AddSourceOrderID(v)
	return _u
}

// ClearSourceOrderID clears the value of the "source_order_id" field.
func (_u *SubscriptionEarlyResetEntitlementUpdate) ClearSourceOrderID() *SubscriptionEarlyResetEntitlementUpdate {
	_u.mutation.ClearSourceOrderID()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *SubscriptionEarlyResetEntitlementUpdate) SetEnabled(v bool) *SubscriptionEarlyResetEntitlementUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *SubscriptionEarlyResetEntitlementUpdate) SetNillableEnabled(v *bool) *SubscriptionEarlyResetEntitlementUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetDurationDays sets the "duration_days" field.
func (_u *SubscriptionEarlyResetEntitlementUpdate) SetDurationDays(v int) *SubscriptionEarlyResetEntitlementUpdate {
	_u.mutation.ResetDurationDays()
	_u.mutation.SetDurationDays(v)
	return _u
}

// SetNillableDurationDays sets the "duration_days" field if the given value is not nil.
func (_u *SubscriptionEarlyResetEntitlementUpdate) SetNillableDurationDays(v *int) *SubscriptionEarlyResetEntitlementUpdate {
	if v != nil {
		_u.SetDurationDays(*v)
	}
	return _u
}

// AddDurationDays adds value to the "duration_days" field.
func (_u *SubscriptionEarlyResetEntitlementUpdate) AddDurationDays(v int) *SubscriptionEarlyResetEntitlementUpdate {
	_u.mutation.AddDurationDays(v)
	return _u
}

// SetCustomTerm sets the "custom_term" field.
func (_u *SubscriptionEarlyResetEntitlementUpdate) SetCustomTerm(v bool) *SubscriptionEarlyResetEntitlementUpdate {
	_u.mutation.SetCustomTerm(v)
	return _u
}

// SetNillableCustomTerm sets the "custom_term" field if the given value is not nil.
func (_u *SubscriptionEarlyResetEntitlementUpdate) SetNillableCustomTerm(v *bool) *SubscriptionEarlyResetEntitlementUpdate {
	if v != nil {
		_u.SetCustomTerm(*v)
	}
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *SubscriptionEarlyResetEntitlementUpdate) SetStartsAt(v time.Time) *SubscriptionEarlyResetEntitlementUpdate {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *SubscriptionEarlyResetEntitlementUpdate) SetNillableStartsAt(v *time.Time) *SubscriptionEarlyResetEntitlementUpdate {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *SubscriptionEarlyResetEntitlementUpdate) SetExpiresAt(v time.Time) *SubscriptionEarlyResetEntitlementUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *SubscriptionEarlyResetEntitlementUpdate) SetNillableExpiresAt(v *time.Time) *SubscriptionEarlyResetEntitlementUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// Mutation returns the SubscriptionEarlyResetEntitlementMutation object of the builder.
func (_u *SubscriptionEarlyResetEntitlementUpdate) Mutation() *SubscriptionEarlyResetEntitlementMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubscriptionEarlyResetEntitlementUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionEarlyResetEntitlementUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubscriptionEarlyResetEntitlementUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionEarlyResetEntitlementUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionEarlyResetEntitlementUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscriptionearlyresetentitlement.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionEarlyResetEntitlementUpdate) check() error {
	if v, ok := _u.mutation.DurationDays(); ok {
		if err := subscriptionearlyresetentitlement.DurationDaysValidator(v); err != nil {
			return &ValidationError{Name: "duration_days", err: fmt.Errorf(`ent: validator failed for field "SubscriptionEarlyResetEntitlement.duration_days": %w`, err)}
		}
	}
	return nil
}

func (_u *SubscriptionEarlyResetEntitlementUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionearlyresetentitlement.Table, subscriptionearlyresetentitlement.Columns, sqlgraph.NewFieldSpec(subscriptionearlyresetentitlement.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionearlyresetentitlement.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(subscriptionearlyresetentitlement.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(subscriptionearlyresetentitlement.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SubscriptionID(); ok {
		_spec.SetField(subscriptionearlyresetentitlement.FieldSubscriptionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubscriptionID(); ok {
		_spec.AddField(subscriptionearlyresetentitlement.FieldSubscriptionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SourceOrderID(); ok {
		_spec.SetField(subscriptionearlyresetentitlement.FieldSourceOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSourceOrderID(); ok {
		_spec.AddField(subscriptionearlyresetentitlement.FieldSourceOrderID, field.TypeInt64, value)
	}
	if _u.mutation.SourceOrderIDCleared() {
		_spec.ClearField(subscriptionearlyresetentitlement.FieldSourceOrderID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(subscriptionearlyresetentitlement.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DurationDays(); ok {
		_spec.SetField(subscriptionearlyresetentitlement.FieldDurationDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationDays(); ok {
		_spec.AddField(subscriptionearlyresetentitlement.FieldDurationDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CustomTerm(); ok {
		_spec.SetField(subscriptionearlyresetentitlement.FieldCustomTerm, field.TypeBool, value)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(subscriptionearlyresetentitlement.FieldStartsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(subscriptionearlyresetentitlement.FieldExpiresAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionearlyresetentitlement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubscriptionEarlyResetEntitlementUpdateOne is the builder for updating a single SubscriptionEarlyResetEntitlement entity.
type SubscriptionEarlyResetEntitlementUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionEarlyResetEntitlementMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionEarlyResetEntitlementUpdateOne) SetUpdatedAt(v time.Time) *SubscriptionEarlyResetEntitlementUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SubscriptionEarlyResetEntitlementUpdateOne) SetUserID(v int64) *SubscriptionEarlyResetEntitlementUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SubscriptionEarlyResetEntitlementUpdateOne) SetNillableUserID(v *int64) *SubscriptionEarlyResetEntitlementUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *SubscriptionEarlyResetEntitlementUpdateOne) AddUserID(v int64) *SubscriptionEarlyResetEntitlementUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *SubscriptionEarlyResetEntitlementUpdateOne) SetSubscriptionID(v int64) *SubscriptionEarlyResetEntitlementUpdateOne {
	_u.mutation.ResetSubscriptionID()
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *SubscriptionEarlyResetEntitlementUpdateOne) SetNillableSubscriptionID(v *int64) *SubscriptionEarlyResetEntitlementUpdateOne {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// AddSubscriptionID adds value to the "subscription_id" field.
func (_u *SubscriptionEarlyResetEntitlementUpdateOne) AddSubscriptionID(v int64) *SubscriptionEarlyResetEntitlementUpdateOne {
	_u.mutation.AddSubscriptionID(v)
	return _u
}

// SetSourceOrderID sets the "source_order_id" field.
func (_u *SubscriptionEarlyResetEntitlementUpdateOne) SetSourceOrderID(v int64) *SubscriptionEarlyResetEntitlementUpdateOne {
	_u.mutation.ResetSourceOrderID()
	_u.mutation.SetSourceOrderID(v)
	return _u
}

// SetNillableSourceOrderID sets the "source_order_id" field if the given value is not nil.
func (_u *SubscriptionEarlyResetEntitlementUpdateOne) SetNillableSourceOrderID(v *int64) *SubscriptionEarlyResetEntitlementUpdateOne {
	if v != nil {
		_u.SetSourceOrderID(*v)
	}
	return _u
}

// AddSourceOrderID adds value to the "source_order_id" field.
func (_u *SubscriptionEarlyResetEntitlementUpdateOne) AddSourceOrderID(v int64) *SubscriptionEarlyResetEntitlementUpdateOne {
	_u.mutation.AddSourceOrderID(v)
	return _u
}

// ClearSourceOrderID clears the value of the "source_order_id" field.
func (_u *SubscriptionEarlyResetEntitlementUpdateOne) ClearSourceOrderID() *SubscriptionEarlyResetEntitlementUpdateOne {
	_u.mutation.ClearSourceOrderID()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *SubscriptionEarlyResetEntitlementUpdateOne) SetEnabled(v bool) *SubscriptionEarlyResetEntitlementUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *SubscriptionEarlyResetEntitlementUpdateOne) SetNillableEnabled(v *bool) *SubscriptionEarlyResetEntitlementUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetDurationDays sets the "duration_days" field.
func (_u *SubscriptionEarlyResetEntitlementUpdateOne) SetDurationDays(v int) *SubscriptionEarlyResetEntitlementUpdateOne {
	_u.mutation.ResetDurationDays()
	_u.mutation.SetDurationDays(v)
	return _u
}

// SetNillableDurationDays sets the "duration_days" field if the given value is not nil.
func (_u *SubscriptionEarlyResetEntitlementUpdateOne) SetNillableDurationDays(v *int) *SubscriptionEarlyResetEntitlementUpdateOne {
	if v != nil {
		_u.SetDurationDays(*v)
	}
	return _u
}

// AddDurationDays adds value to the "duration_days" field.
func (_u *SubscriptionEarlyResetEntitlementUpdateOne) AddDurationDays(v int) *SubscriptionEarlyResetEntitlementUpdateOne {
	_u.mutation.AddDurationDays(v)
	return _u
}

// SetCustomTerm sets the "custom_term" field.
func (_u *SubscriptionEarlyResetEntitlementUpdateOne) SetCustomTerm(v bool) *SubscriptionEarlyResetEntitlementUpdateOne {
	_u.mutation.SetCustomTerm(v)
	return _u
}

// SetNillableCustomTerm sets the "custom_term" field if the given value is not nil.
func (_u *SubscriptionEarlyResetEntitlementUpdateOne) SetNillableCustomTerm(v *bool) *SubscriptionEarlyResetEntitlementUpdateOne {
	if v != nil {
		_u.SetCustomTerm(*v)
	}
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *SubscriptionEarlyResetEntitlementUpdateOne) SetStartsAt(v time.Time) *SubscriptionEarlyResetEntitlementUpdateOne {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *SubscriptionEarlyResetEntitlementUpdateOne) SetNillableStartsAt(v *time.Time) *SubscriptionEarlyResetEntitlementUpdateOne {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *SubscriptionEarlyResetEntitlementUpdateOne) SetExpiresAt(v time.Time) *SubscriptionEarlyResetEntitlementUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *SubscriptionEarlyResetEntitlementUpdateOne) SetNillableExpiresAt(v *time.Time) *SubscriptionEarlyResetEntitlementUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// Mutation returns the SubscriptionEarlyResetEntitlementMutation object of the builder.
func (_u *SubscriptionEarlyResetEntitlementUpdateOne) Mutation() *SubscriptionEarlyResetEntitlementMutation {
	return _u.mutation
}

// Where appends a list predicates to the SubscriptionEarlyResetEntitlementUpdate builder.
func (_u *SubscriptionEarlyResetEntitlementUpdateOne) Where(ps ...predicate.SubscriptionEarlyResetEntitlement) *SubscriptionEarlyResetEntitlementUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubscriptionEarlyResetEntitlementUpdateOne) Select(field string, fields ...string) *SubscriptionEarlyResetEntitlementUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SubscriptionEarlyResetEntitlement entity.
func (_u *SubscriptionEarlyResetEntitlementUpdateOne) Save(ctx context.Context) (*SubscriptionEarlyResetEntitlement, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionEarlyResetEntitlementUpdateOne) SaveX(ctx context.Context) *SubscriptionEarlyResetEntitlement {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubscriptionEarlyResetEntitlementUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionEarlyResetEntitlementUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionEarlyResetEntitlementUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscriptionearlyresetentitlement.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionEarlyResetEntitlementUpdateOne) check() error {
	if v, ok := _u.mutation.DurationDays(); ok {
		if err := subscriptionearlyresetentitlement.DurationDaysValidator(v); err != nil {
			return &ValidationError{Name: "duration_days", err: fmt.Errorf(`ent: validator failed for field "SubscriptionEarlyResetEntitlement.duration_days": %w`, err)}
		}
	}
	return nil
}

func (_u *SubscriptionEarlyResetEntitlementUpdateOne) sqlSave(ctx context.Context) (_node *SubscriptionEarlyResetEntitlement, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionearlyresetentitlement.Table, subscriptionearlyresetentitlement.Columns, sqlgraph.NewFieldSpec(subscriptionearlyresetentitlement.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SubscriptionEarlyResetEntitlement.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptionearlyresetentitlement.FieldID)
		for _, f := range fields {
			if !subscriptionearlyresetentitlement.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscriptionearlyresetentitlement.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionearlyresetentitlement.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(subscriptionearlyresetentitlement.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(subscriptionearlyresetentitlement.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SubscriptionID(); ok {
		_spec.SetField(subscriptionearlyresetentitlement.FieldSubscriptionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubscriptionID(); ok {
		_spec.AddField(subscriptionearlyresetentitlement.FieldSubscriptionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SourceOrderID(); ok {
		_spec.SetField(subscriptionearlyresetentitlement.FieldSourceOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSourceOrderID(); ok {
		_spec.AddField(subscriptionearlyresetentitlement.FieldSourceOrderID, field.TypeInt64, value)
	}
	if _u.mutation.SourceOrderIDCleared() {
		_spec.ClearField(subscriptionearlyresetentitlement.FieldSourceOrderID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(subscriptionearlyresetentitlement.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DurationDays(); ok {
		_spec.SetField(subscriptionearlyresetentitlement.FieldDurationDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationDays(); ok {
		_spec.AddField(subscriptionearlyresetentitlement.FieldDurationDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CustomTerm(); ok {
		_spec.SetField(subscriptionearlyresetentitlement.FieldCustomTerm, field.TypeBool, value)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(subscriptionearlyresetentitlement.FieldStartsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(subscriptionearlyresetentitlement.FieldExpiresAt, field.TypeTime, value)
	}
	_node = &SubscriptionEarlyResetEntitlement{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionearlyresetentitlement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
