// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionconcurrencyentitlement"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// SubscriptionConcurrencyEntitlementUpdate is the builder for updating SubscriptionConcurrencyEntitlement entities.
type SubscriptionConcurrencyEntitlementUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionConcurrencyEntitlementMutation
}

// Where appends a list predicates to the SubscriptionConcurrencyEntitlementUpdate builder.
func (_u *SubscriptionConcurrencyEntitlementUpdate) Where(ps ...predicate.SubscriptionConcurrencyEntitlement) *SubscriptionConcurrencyEntitlementUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionConcurrencyEntitlementUpdate) SetUpdatedAt(v time.Time) *SubscriptionConcurrencyEntitlementUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SubscriptionConcurrencyEntitlementUpdate) SetUserID(v int64) *SubscriptionConcurrencyEntitlementUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SubscriptionConcurrencyEntitlementUpdate) SetNillableUserID(v *int64) *SubscriptionConcurrencyEntitlementUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *SubscriptionConcurrencyEntitlementUpdate) SetSubscriptionID(v int64) *SubscriptionConcurrencyEntitlementUpdate {
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *SubscriptionConcurrencyEntitlementUpdate) SetNillableSubscriptionID(v *int64) *SubscriptionConcurrencyEntitlementUpdate {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// SetSourceOrderID sets the "source_order_id" field.
func (_u *SubscriptionConcurrencyEntitlementUpdate) SetSourceOrderID(v int64) *SubscriptionConcurrencyEntitlementUpdate {
	_u.mutation.ResetSourceOrderID()
	_u.mutation.SetSourceOrderID(v)
	return _u
}

// SetNillableSourceOrderID sets the "source_order_id" field if the given value is not nil.
func (_u *SubscriptionConcurrencyEntitlementUpdate) SetNillableSourceOrderID(v *int64) *SubscriptionConcurrencyEntitlementUpdate {
	if v != nil {
		_u.SetSourceOrderID(*v)
	}
	return _u
}

// AddSourceOrderID adds value to the "source_order_id" field.
func (_u *SubscriptionConcurrencyEntitlementUpdate) AddSourceOrderID(v int64) *SubscriptionConcurrencyEntitlementUpdate {
	_u.mutation.AddSourceOrderID(v)
	return _u
}

// ClearSourceOrderID clears the value of the "source_order_id" field.
func (_u *SubscriptionConcurrencyEntitlementUpdate) ClearSourceOrderID() *SubscriptionConcurrencyEntitlementUpdate {
	_u.mutation.ClearSourceOrderID()
	return _u
}

// SetConcurrency sets the "concurrency" field.
func (_u *SubscriptionConcurrencyEntitlementUpdate) SetConcurrency(v int) *SubscriptionConcurrencyEntitlementUpdate {
	_u.mutation.ResetConcurrency()
	_u.mutation.SetConcurrency(v)
	return _u
}

// SetNillableConcurrency sets the "concurrency" field if the given value is not nil.
func (_u *SubscriptionConcurrencyEntitlementUpdate) SetNillableConcurrency(v *int) *SubscriptionConcurrencyEntitlementUpdate {
	if v != nil {
		_u.SetConcurrency(*v)
	}
	return _u
}

// AddConcurrency adds value to the "concurrency" field.
func (_u *SubscriptionConcurrencyEntitlementUpdate) AddConcurrency(v int) *SubscriptionConcurrencyEntitlementUpdate {
	_u.mutation.AddConcurrency(v)
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *SubscriptionConcurrencyEntitlementUpdate) SetStartsAt(v time.Time) *SubscriptionConcurrencyEntitlementUpdate {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *SubscriptionConcurrencyEntitlementUpdate) SetNillableStartsAt(v *time.Time) *SubscriptionConcurrencyEntitlementUpdate {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *SubscriptionConcurrencyEntitlementUpdate) SetExpiresAt(v time.Time) *SubscriptionConcurrencyEntitlementUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *SubscriptionConcurrencyEntitlementUpdate) SetNillableExpiresAt(v *time.Time) *SubscriptionConcurrencyEntitlementUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SubscriptionConcurrencyEntitlementUpdate) SetUser(v *User) *SubscriptionConcurrencyEntitlementUpdate {
	return _u.SetUserID(v.ID)
}

// SetSubscription sets the "subscription" edge to the UserSubscription entity.
func (_u *SubscriptionConcurrencyEntitlementUpdate) SetSubscription(v *UserSubscription) *SubscriptionConcurrencyEntitlementUpdate {
	return _u.SetSubscriptionID(v.ID)
}

// Mutation returns the SubscriptionConcurrencyEntitlementMutation object of the builder.
func (_u *SubscriptionConcurrencyEntitlementUpdate) Mutation() *SubscriptionConcurrencyEntitlementMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SubscriptionConcurrencyEntitlementUpdate) ClearUser() *SubscriptionConcurrencyEntitlementUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearSubscription clears the "subscription" edge to the UserSubscription entity.
func (_u *SubscriptionConcurrencyEntitlementUpdate) ClearSubscription() *SubscriptionConcurrencyEntitlementUpdate {
	_u.mutation.ClearSubscription()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubscriptionConcurrencyEntitlementUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionConcurrencyEntitlementUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubscriptionConcurrencyEntitlementUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionConcurrencyEntitlementUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionConcurrencyEntitlementUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscriptionconcurrencyentitlement.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionConcurrencyEntitlementUpdate) check() error {
	if v, ok := _u.mutation.Concurrency(); ok {
		if err := subscriptionconcurrencyentitlement.ConcurrencyValidator(v); err != nil {
			return &ValidationError{Name: "concurrency", err: fmt.Errorf(`ent: validator failed for field "SubscriptionConcurrencyEntitlement.concurrency": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionConcurrencyEntitlement.user"`)
	}
	if _u.mutation.SubscriptionCleared() && len(_u.mutation.SubscriptionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionConcurrencyEntitlement.subscription"`)
	}
	return nil
}

func (_u *SubscriptionConcurrencyEntitlementUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionconcurrencyentitlement.Table, subscriptionconcurrencyentitlement.Columns, sqlgraph.NewFieldSpec(subscriptionconcurrencyentitlement.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionconcurrencyentitlement.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SourceOrderID(); ok {
		_spec.SetField(subscriptionconcurrencyentitlement.FieldSourceOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSourceOrderID(); ok {
		_spec.AddField(subscriptionconcurrencyentitlement.FieldSourceOrderID, field.TypeInt64, value)
	}
	if _u.mutation.SourceOrderIDCleared() {
		_spec.ClearField(subscriptionconcurrencyentitlement.FieldSourceOrderID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Concurrency(); ok {
		_spec.SetField(subscriptionconcurrencyentitlement.FieldConcurrency, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConcurrency(); ok {
		_spec.AddField(subscriptionconcurrencyentitlement.FieldConcurrency, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(subscriptionconcurrencyentitlement.FieldStartsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(subscriptionconcurrencyentitlement.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionconcurrencyentitlement.UserTable,
			Columns: []string{subscriptionconcurrencyentitlement.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionconcurrencyentitlement.UserTable,
			Columns: []string{subscriptionconcurrencyentitlement.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubscriptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionconcurrencyentitlement.SubscriptionTable,
			Columns: []string{subscriptionconcurrencyentitlement.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionconcurrencyentitlement.SubscriptionTable,
			Columns: []string{subscriptionconcurrencyentitlement.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionconcurrencyentitlement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubscriptionConcurrencyEntitlementUpdateOne is the builder for updating a single SubscriptionConcurrencyEntitlement entity.
type SubscriptionConcurrencyEntitlementUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionConcurrencyEntitlementMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionConcurrencyEntitlementUpdateOne) SetUpdatedAt(v time.Time) *SubscriptionConcurrencyEntitlementUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SubscriptionConcurrencyEntitlementUpdateOne) SetUserID(v int64) *SubscriptionConcurrencyEntitlementUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SubscriptionConcurrencyEntitlementUpdateOne) SetNillableUserID(v *int64) *SubscriptionConcurrencyEntitlementUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *SubscriptionConcurrencyEntitlementUpdateOne) SetSubscriptionID(v int64) *SubscriptionConcurrencyEntitlementUpdateOne {
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *SubscriptionConcurrencyEntitlementUpdateOne) SetNillableSubscriptionID(v *int64) *SubscriptionConcurrencyEntitlementUpdateOne {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// SetSourceOrderID sets the "source_order_id" field.
func (_u *SubscriptionConcurrencyEntitlementUpdateOne) SetSourceOrderID(v int64) *SubscriptionConcurrencyEntitlementUpdateOne {
	_u.mutation.ResetSourceOrderID()
	_u.mutation.SetSourceOrderID(v)
	return _u
}

// SetNillableSourceOrderID sets the "source_order_id" field if the given value is not nil.
func (_u *SubscriptionConcurrencyEntitlementUpdateOne) SetNillableSourceOrderID(v *int64) *SubscriptionConcurrencyEntitlementUpdateOne {
	if v != nil {
		_u.SetSourceOrderID(*v)
	}
	return _u
}

// AddSourceOrderID adds value to the "source_order_id" field.
func (_u *SubscriptionConcurrencyEntitlementUpdateOne) AddSourceOrderID(v int64) *SubscriptionConcurrencyEntitlementUpdateOne {
	_u.mutation.AddSourceOrderID(v)
	return _u
}

// ClearSourceOrderID clears the value of the "source_order_id" field.
func (_u *SubscriptionConcurrencyEntitlementUpdateOne) ClearSourceOrderID() *SubscriptionConcurrencyEntitlementUpdateOne {
	_u.mutation.ClearSourceOrderID()
	return _u
}

// SetConcurrency sets the "concurrency" field.
func (_u *SubscriptionConcurrencyEntitlementUpdateOne) SetConcurrency(v int) *SubscriptionConcurrencyEntitlementUpdateOne {
	_u.mutation.ResetConcurrency()
	_u.mutation.SetConcurrency(v)
	return _u
}

// SetNillableConcurrency sets the "concurrency" field if the given value is not nil.
func (_u *SubscriptionConcurrencyEntitlementUpdateOne) SetNillableConcurrency(v *int) *SubscriptionConcurrencyEntitlementUpdateOne {
	if v != nil {
		_u.SetConcurrency(*v)
	}
	return _u
}

// AddConcurrency adds value to the "concurrency" field.
func (_u *SubscriptionConcurrencyEntitlementUpdateOne) AddConcurrency(v int) *SubscriptionConcurrencyEntitlementUpdateOne {
	_u.mutation.AddConcurrency(v)
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *SubscriptionConcurrencyEntitlementUpdateOne) SetStartsAt(v time.Time) *SubscriptionConcurrencyEntitlementUpdateOne {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *SubscriptionConcurrencyEntitlementUpdateOne) SetNillableStartsAt(v *time.Time) *SubscriptionConcurrencyEntitlementUpdateOne {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *SubscriptionConcurrencyEntitlementUpdateOne) SetExpiresAt(v time.Time) *SubscriptionConcurrencyEntitlementUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *SubscriptionConcurrencyEntitlementUpdateOne) SetNillableExpiresAt(v *time.Time) *SubscriptionConcurrencyEntitlementUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SubscriptionConcurrencyEntitlementUpdateOne) SetUser(v *User) *SubscriptionConcurrencyEntitlementUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetSubscription sets the "subscription" edge to the UserSubscription entity.
func (_u *SubscriptionConcurrencyEntitlementUpdateOne) SetSubscription(v *UserSubscription) *SubscriptionConcurrencyEntitlementUpdateOne {
	return _u.SetSubscriptionID(v.ID)
}

// Mutation returns the SubscriptionConcurrencyEntitlementMutation object of the builder.
func (_u *SubscriptionConcurrencyEntitlementUpdateOne) Mutation() *SubscriptionConcurrencyEntitlementMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SubscriptionConcurrencyEntitlementUpdateOne) ClearUser() *SubscriptionConcurrencyEntitlementUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearSubscription clears the "subscription" edge to the UserSubscription entity.
func (_u *SubscriptionConcurrencyEntitlementUpdateOne) ClearSubscription() *SubscriptionConcurrencyEntitlementUpdateOne {
	_u.mutation.ClearSubscription()
	return _u
}

// Where appends a list predicates to the SubscriptionConcurrencyEntitlementUpdate builder.
func (_u *SubscriptionConcurrencyEntitlementUpdateOne) Where(ps ...predicate.SubscriptionConcurrencyEntitlement) *SubscriptionConcurrencyEntitlementUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubscriptionConcurrencyEntitlementUpdateOne) Select(field string, fields ...string) *SubscriptionConcurrencyEntitlementUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SubscriptionConcurrencyEntitlement entity.
func (_u *SubscriptionConcurrencyEntitlementUpdateOne) Save(ctx context.Context) (*SubscriptionConcurrencyEntitlement, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionConcurrencyEntitlementUpdateOne) SaveX(ctx context.Context) *SubscriptionConcurrencyEntitlement {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubscriptionConcurrencyEntitlementUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionConcurrencyEntitlementUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionConcurrencyEntitlementUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscriptionconcurrencyentitlement.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionConcurrencyEntitlementUpdateOne) check() error {
	if v, ok := _u.mutation.Concurrency(); ok {
		if err := subscriptionconcurrencyentitlement.ConcurrencyValidator(v); err != nil {
			return &ValidationError{Name: "concurrency", err: fmt.Errorf(`ent: validator failed for field "SubscriptionConcurrencyEntitlement.concurrency": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionConcurrencyEntitlement.user"`)
	}
	if _u.mutation.SubscriptionCleared() && len(_u.mutation.SubscriptionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionConcurrencyEntitlement.subscription"`)
	}
	return nil
}

func (_u *SubscriptionConcurrencyEntitlementUpdateOne) sqlSave(ctx context.Context) (_node *SubscriptionConcurrencyEntitlement, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionconcurrencyentitlement.Table, subscriptionconcurrencyentitlement.Columns, sqlgraph.NewFieldSpec(subscriptionconcurrencyentitlement.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SubscriptionConcurrencyEntitlement.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptionconcurrencyentitlement.FieldID)
		for _, f := range fields {
			if !subscriptionconcurrencyentitlement.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscriptionconcurrencyentitlement.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionconcurrencyentitlement.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SourceOrderID(); ok {
		_spec.SetField(subscriptionconcurrencyentitlement.FieldSourceOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSourceOrderID(); ok {
		_spec.AddField(subscriptionconcurrencyentitlement.FieldSourceOrderID, field.TypeInt64, value)
	}
	if _u.mutation.SourceOrderIDCleared() {
		_spec.ClearField(subscriptionconcurrencyentitlement.FieldSourceOrderID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Concurrency(); ok {
		_spec.SetField(subscriptionconcurrencyentitlement.FieldConcurrency, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConcurrency(); ok {
		_spec.AddField(subscriptionconcurrencyentitlement.FieldConcurrency, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(subscriptionconcurrencyentitlement.FieldStartsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(subscriptionconcurrencyentitlement.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionconcurrencyentitlement.UserTable,
			Columns: []string{subscriptionconcurrencyentitlement.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionconcurrencyentitlement.UserTable,
			Columns: []string{subscriptionconcurrencyentitlement.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubscriptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionconcurrencyentitlement.SubscriptionTable,
			Columns: []string{subscriptionconcurrencyentitlement.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionconcurrencyentitlement.SubscriptionTable,
			Columns: []string{subscriptionconcurrencyentitlement.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SubscriptionConcurrencyEntitlement{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionconcurrencyentitlement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
