// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionconcurrencyentitlement"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// SubscriptionConcurrencyEntitlementCreate is the builder for creating a SubscriptionConcurrencyEntitlement entity.
type SubscriptionConcurrencyEntitlementCreate struct {
	config
	mutation *SubscriptionConcurrencyEntitlementMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *SubscriptionConcurrencyEntitlementCreate) SetCreatedAt(v time.Time) *SubscriptionConcurrencyEntitlementCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SubscriptionConcurrencyEntitlementCreate) SetNillableCreatedAt(v *time.Time) *SubscriptionConcurrencyEntitlementCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SubscriptionConcurrencyEntitlementCreate) SetUpdatedAt(v time.Time) *SubscriptionConcurrencyEntitlementCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SubscriptionConcurrencyEntitlementCreate) SetNillableUpdatedAt(v *time.Time) *SubscriptionConcurrencyEntitlementCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *SubscriptionConcurrencyEntitlementCreate) SetUserID(v int64) *SubscriptionConcurrencyEntitlementCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetSubscriptionID sets the "subscription_id" field.
func (_c *SubscriptionConcurrencyEntitlementCreate) SetSubscriptionID(v int64) *SubscriptionConcurrencyEntitlementCreate {
	_c.mutation.SetSubscriptionID(v)
	return _c
}

// SetSourceOrderID sets the "source_order_id" field.
func (_c *SubscriptionConcurrencyEntitlementCreate) SetSourceOrderID(v int64) *SubscriptionConcurrencyEntitlementCreate {
	_c.mutation.SetSourceOrderID(v)
	return _c
}

// SetNillableSourceOrderID sets the "source_order_id" field if the given value is not nil.
func (_c *SubscriptionConcurrencyEntitlementCreate) SetNillableSourceOrderID(v *int64) *SubscriptionConcurrencyEntitlementCreate {
	if v != nil {
		_c.SetSourceOrderID(*v)
	}
	return _c
}

// SetConcurrency sets the "concurrency" field.
func (_c *SubscriptionConcurrencyEntitlementCreate) SetConcurrency(v int) *SubscriptionConcurrencyEntitlementCreate {
	_c.mutation.SetConcurrency(v)
	return _c
}

// SetStartsAt sets the "starts_at" field.
func (_c *SubscriptionConcurrencyEntitlementCreate) SetStartsAt(v time.Time) *SubscriptionConcurrencyEntitlementCreate {
	_c.mutation.SetStartsAt(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *SubscriptionConcurrencyEntitlementCreate) SetExpiresAt(v time.Time) *SubscriptionConcurrencyEntitlementCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *SubscriptionConcurrencyEntitlementCreate) SetUser(v *User) *SubscriptionConcurrencyEntitlementCreate {
	return _c.SetUserID(v.ID)
}

// SetSubscription sets the "subscription" edge to the UserSubscription entity.
func (_c *SubscriptionConcurrencyEntitlementCreate) SetSubscription(v *UserSubscription) *SubscriptionConcurrencyEntitlementCreate {
	return _c.SetSubscriptionID(v.ID)
}

// Mutation returns the SubscriptionConcurrencyEntitlementMutation object of the builder.
func (_c *SubscriptionConcurrencyEntitlementCreate) Mutation() *SubscriptionConcurrencyEntitlementMutation {
	return _c.mutation
}

// Save creates the SubscriptionConcurrencyEntitlement in the database.
func (_c *SubscriptionConcurrencyEntitlementCreate) Save(ctx context.Context) (*SubscriptionConcurrencyEntitlement, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SubscriptionConcurrencyEntitlementCreate) SaveX(ctx context.Context) *SubscriptionConcurrencyEntitlement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionConcurrencyEntitlementCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionConcurrencyEntitlementCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SubscriptionConcurrencyEntitlementCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := subscriptionconcurrencyentitlement.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := subscriptionconcurrencyentitlement.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SubscriptionConcurrencyEntitlementCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SubscriptionConcurrencyEntitlement.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SubscriptionConcurrencyEntitlement.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "SubscriptionConcurrencyEntitlement.user_id"`)}
	}
	if _, ok := _c.mutation.SubscriptionID(); !ok {
		return &ValidationError{Name: "subscription_id", err: errors.New(`ent: missing required field "SubscriptionConcurrencyEntitlement.subscription_id"`)}
	}
	if _, ok := _c.mutation.Concurrency(); !ok {
		return &ValidationError{Name: "concurrency", err: errors.New(`ent: missing required field "SubscriptionConcurrencyEntitlement.concurrency"`)}
	}
	if v, ok := _c.mutation.Concurrency(); ok {
		if err := subscriptionconcurrencyentitlement.ConcurrencyValidator(v); err != nil {
			return &ValidationError{Name: "concurrency", err: fmt.Errorf(`ent: validator failed for field "SubscriptionConcurrencyEntitlement.concurrency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StartsAt(); !ok {
		return &ValidationError{Name: "starts_at", err: errors.New(`ent: missing required field "SubscriptionConcurrencyEntitlement.starts_at"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "SubscriptionConcurrencyEntitlement.expires_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "SubscriptionConcurrencyEntitlement.user"`)}
	}
	if len(_c.mutation.SubscriptionIDs()) == 0 {
		return &ValidationError{Name: "subscription", err: errors.New(`ent: missing required edge "SubscriptionConcurrencyEntitlement.subscription"`)}
	}
	return nil
}

func (_c *SubscriptionConcurrencyEntitlementCreate) sqlSave(ctx context.Context) (*SubscriptionConcurrencyEntitlement, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SubscriptionConcurrencyEntitlementCreate) createSpec() (*SubscriptionConcurrencyEntitlement, *sqlgraph.CreateSpec) {
	var (
		_node = &SubscriptionConcurrencyEntitlement{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(subscriptionconcurrencyentitlement.Table, sqlgraph.NewFieldSpec(subscriptionconcurrencyentitlement.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(subscriptionconcurrencyentitlement.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionconcurrencyentitlement.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.SourceOrderID(); ok {
		_spec.SetField(subscriptionconcurrencyentitlement.FieldSourceOrderID, field.TypeInt64, value)
		_node.SourceOrderID = &value
	}
	if value, ok := _c.mutation.Concurrency(); ok {
		_spec.SetField(subscriptionconcurrencyentitlement.FieldConcurrency, field.TypeInt, value)
		_node.Concurrency = value
	}
	if value, ok := _c.mutation.StartsAt(); ok {
		_spec.SetField(subscriptionconcurrencyentitlement.FieldStartsAt, field.TypeTime, value)
		_node.StartsAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(subscriptionconcurrencyentitlement.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionconcurrencyentitlement.UserTable,
			Columns: []string{subscriptionconcurrencyentitlement.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionconcurrencyentitlement.SubscriptionTable,
			Columns: []string{subscriptionconcurrencyentitlement.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SubscriptionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionConcurrencyEntitlement.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionConcurrencyEntitlementUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionConcurrencyEntitlementCreate) OnConflict(opts ...sql.ConflictOption) *SubscriptionConcurrencyEntitlementUpsertOne {
	_c.conflict = opts
	return &SubscriptionConcurrencyEntitlementUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionConcurrencyEntitlement.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionConcurrencyEntitlementCreate) OnConflictColumns(columns ...string) *SubscriptionConcurrencyEntitlementUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionConcurrencyEntitlementUpsertOne{
		create: _c,
	}
}

type (
	// SubscriptionConcurrencyEntitlementUpsertOne is the builder for "upsert"-ing
	//  one SubscriptionConcurrencyEntitlement node.
	SubscriptionConcurrencyEntitlementUpsertOne struct {
		create *SubscriptionConcurrencyEntitlementCreate
	}

	// SubscriptionConcurrencyEntitlementUpsert is the "OnConflict" setter.
	SubscriptionConcurrencyEntitlementUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionConcurrencyEntitlementUpsert) SetUpdatedAt(v time.Time) *SubscriptionConcurrencyEntitlementUpsert {
	u.Set(subscriptionconcurrencyentitlement.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionConcurrencyEntitlementUpsert) UpdateUpdatedAt() *SubscriptionConcurrencyEntitlementUpsert {
	u.SetExcluded(subscriptionconcurrencyentitlement.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *SubscriptionConcurrencyEntitlementUpsert) SetUserID(v int64) *SubscriptionConcurrencyEntitlementUpsert {
	u.Set(subscriptionconcurrencyentitlement.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SubscriptionConcurrencyEntitlementUpsert) UpdateUserID() *SubscriptionConcurrencyEntitlementUpsert {
	u.SetExcluded(subscriptionconcurrencyentitlement.FieldUserID)
	return u
}

// SetSubscriptionID sets the "subscription_id" field.
func (u *SubscriptionConcurrencyEntitlementUpsert) SetSubscriptionID(v int64) *SubscriptionConcurrencyEntitlementUpsert {
	u.Set(subscriptionconcurrencyentitlement.FieldSubscriptionID, v)
	return u
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *SubscriptionConcurrencyEntitlementUpsert) UpdateSubscriptionID() *SubscriptionConcurrencyEntitlementUpsert {
	u.SetExcluded(subscriptionconcurrencyentitlement.FieldSubscriptionID)
	return u
}

// SetSourceOrderID sets the "source_order_id" field.
func (u *SubscriptionConcurrencyEntitlementUpsert) SetSourceOrderID(v int64) *SubscriptionConcurrencyEntitlementUpsert {
	u.Set(subscriptionconcurrencyentitlement.FieldSourceOrderID, v)
	return u
}

// UpdateSourceOrderID sets the "source_order_id" field to the value that was provided on create.
func (u *SubscriptionConcurrencyEntitlementUpsert) UpdateSourceOrderID() *SubscriptionConcurrencyEntitlementUpsert {
	u.SetExcluded(subscriptionconcurrencyentitlement.FieldSourceOrderID)
	return u
}

// AddSourceOrderID adds v to the "source_order_id" field.
func (u *SubscriptionConcurrencyEntitlementUpsert) AddSourceOrderID(v int64) *SubscriptionConcurrencyEntitlementUpsert {
	u.Add(subscriptionconcurrencyentitlement.FieldSourceOrderID, v)
	return u
}

// ClearSourceOrderID clears the value of the "source_order_id" field.
func (u *SubscriptionConcurrencyEntitlementUpsert) ClearSourceOrderID() *SubscriptionConcurrencyEntitlementUpsert {
	u.SetNull(subscriptionconcurrencyentitlement.FieldSourceOrderID)
	return u
}

// SetConcurrency sets the "concurrency" field.
func (u *SubscriptionConcurrencyEntitlementUpsert) SetConcurrency(v int) *SubscriptionConcurrencyEntitlementUpsert {
	u.Set(subscriptionconcurrencyentitlement.FieldConcurrency, v)
	return u
}

// UpdateConcurrency sets the "concurrency" field to the value that was provided on create.
func (u *SubscriptionConcurrencyEntitlementUpsert) UpdateConcurrency() *SubscriptionConcurrencyEntitlementUpsert {
	u.SetExcluded(subscriptionconcurrencyentitlement.FieldConcurrency)
	return u
}

// AddConcurrency adds v to the "concurrency" field.
func (u *SubscriptionConcurrencyEntitlementUpsert) AddConcurrency(v int) *SubscriptionConcurrencyEntitlementUpsert {
	u.Add(subscriptionconcurrencyentitlement.FieldConcurrency, v)
	return u
}

// SetStartsAt sets the "starts_at" field.
func (u *SubscriptionConcurrencyEntitlementUpsert) SetStartsAt(v time.Time) *SubscriptionConcurrencyEntitlementUpsert {
	u.Set(subscriptionconcurrencyentitlement.FieldStartsAt, v)
	return u
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *SubscriptionConcurrencyEntitlementUpsert) UpdateStartsAt() *SubscriptionConcurrencyEntitlementUpsert {
	u.SetExcluded(subscriptionconcurrencyentitlement.FieldStartsAt)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *SubscriptionConcurrencyEntitlementUpsert) SetExpiresAt(v time.Time) *SubscriptionConcurrencyEntitlementUpsert {
	u.Set(subscriptionconcurrencyentitlement.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *SubscriptionConcurrencyEntitlementUpsert) UpdateExpiresAt() *SubscriptionConcurrencyEntitlementUpsert {
	u.SetExcluded(subscriptionconcurrencyentitlement.FieldExpiresAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SubscriptionConcurrencyEntitlement.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionConcurrencyEntitlementUpsertOne) UpdateNewValues() *SubscriptionConcurrencyEntitlementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(subscriptionconcurrencyentitlement.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionConcurrencyEntitlement.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SubscriptionConcurrencyEntitlementUpsertOne) Ignore() *SubscriptionConcurrencyEntitlementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionConcurrencyEntitlementUpsertOne) DoNothing() *SubscriptionConcurrencyEntitlementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionConcurrencyEntitlementCreate.OnConflict
// documentation for more info.
func (u *SubscriptionConcurrencyEntitlementUpsertOne) Update(set func(*SubscriptionConcurrencyEntitlementUpsert)) *SubscriptionConcurrencyEntitlementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionConcurrencyEntitlementUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionConcurrencyEntitlementUpsertOne) SetUpdatedAt(v time.Time) *SubscriptionConcurrencyEntitlementUpsertOne {
	return u.Update(func(s *SubscriptionConcurrencyEntitlementUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionConcurrencyEntitlementUpsertOne) UpdateUpdatedAt() *SubscriptionConcurrencyEntitlementUpsertOne {
	return u.Update(func(s *SubscriptionConcurrencyEntitlementUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *SubscriptionConcurrencyEntitlementUpsertOne) SetUserID(v int64) *SubscriptionConcurrencyEntitlementUpsertOne {
	return u.Update(func(s *SubscriptionConcurrencyEntitlementUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SubscriptionConcurrencyEntitlementUpsertOne) UpdateUserID() *SubscriptionConcurrencyEntitlementUpsertOne {
	return u.Update(func(s *SubscriptionConcurrencyEntitlementUpsert) {
		s.UpdateUserID()
	})
}

// SetSubscriptionID sets the "subscription_id" field.
func (u *SubscriptionConcurrencyEntitlementUpsertOne) SetSubscriptionID(v int64) *SubscriptionConcurrencyEntitlementUpsertOne {
	return u.Update(func(s *SubscriptionConcurrencyEntitlementUpsert) {
		s.SetSubscriptionID(v)
	})
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *SubscriptionConcurrencyEntitlementUpsertOne) UpdateSubscriptionID() *SubscriptionConcurrencyEntitlementUpsertOne {
	return u.Update(func(s *SubscriptionConcurrencyEntitlementUpsert) {
		s.UpdateSubscriptionID()
	})
}

// SetSourceOrderID sets the "source_order_id" field.
func (u *SubscriptionConcurrencyEntitlementUpsertOne) SetSourceOrderID(v int64) *SubscriptionConcurrencyEntitlementUpsertOne {
	return u.Update(func(s *SubscriptionConcurrencyEntitlementUpsert) {
		s.SetSourceOrderID(v)
	})
}

// AddSourceOrderID adds v to the "source_order_id" field.
func (u *SubscriptionConcurrencyEntitlementUpsertOne) AddSourceOrderID(v int64) *SubscriptionConcurrencyEntitlementUpsertOne {
	return u.Update(func(s *SubscriptionConcurrencyEntitlementUpsert) {
		s.AddSourceOrderID(v)
	})
}

// UpdateSourceOrderID sets the "source_order_id" field to the value that was provided on create.
func (u *SubscriptionConcurrencyEntitlementUpsertOne) UpdateSourceOrderID() *SubscriptionConcurrencyEntitlementUpsertOne {
	return u.Update(func(s *SubscriptionConcurrencyEntitlementUpsert) {
		s.UpdateSourceOrderID()
	})
}

// ClearSourceOrderID clears the value of the "source_order_id" field.
func (u *SubscriptionConcurrencyEntitlementUpsertOne) ClearSourceOrderID() *SubscriptionConcurrencyEntitlementUpsertOne {
	return u.Update(func(s *SubscriptionConcurrencyEntitlementUpsert) {
		s.ClearSourceOrderID()
	})
}

// SetConcurrency sets the "concurrency" field.
func (u *SubscriptionConcurrencyEntitlementUpsertOne) SetConcurrency(v int) *SubscriptionConcurrencyEntitlementUpsertOne {
	return u.Update(func(s *SubscriptionConcurrencyEntitlementUpsert) {
		s.SetConcurrency(v)
	})
}

// AddConcurrency adds v to the "concurrency" field.
func (u *SubscriptionConcurrencyEntitlementUpsertOne) AddConcurrency(v int) *SubscriptionConcurrencyEntitlementUpsertOne {
	return u.Update(func(s *SubscriptionConcurrencyEntitlementUpsert) {
		s.AddConcurrency(v)
	})
}

// UpdateConcurrency sets the "concurrency" field to the value that was provided on create.
func (u *SubscriptionConcurrencyEntitlementUpsertOne) UpdateConcurrency() *SubscriptionConcurrencyEntitlementUpsertOne {
	return u.Update(func(s *SubscriptionConcurrencyEntitlementUpsert) {
		s.UpdateConcurrency()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *SubscriptionConcurrencyEntitlementUpsertOne) SetStartsAt(v time.Time) *SubscriptionConcurrencyEntitlementUpsertOne {
	return u.Update(func(s *SubscriptionConcurrencyEntitlementUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *SubscriptionConcurrencyEntitlementUpsertOne) UpdateStartsAt() *SubscriptionConcurrencyEntitlementUpsertOne {
	return u.Update(func(s *SubscriptionConcurrencyEntitlementUpsert) {
		s.UpdateStartsAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *SubscriptionConcurrencyEntitlementUpsertOne) SetExpiresAt(v time.Time) *SubscriptionConcurrencyEntitlementUpsertOne {
	return u.Update(func(s *SubscriptionConcurrencyEntitlementUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *SubscriptionConcurrencyEntitlementUpsertOne) UpdateExpiresAt() *SubscriptionConcurrencyEntitlementUpsertOne {
	return u.Update(func(s *SubscriptionConcurrencyEntitlementUpsert) {
		s.UpdateExpiresAt()
	})
}

// Exec executes the query.
func (u *SubscriptionConcurrencyEntitlementUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionConcurrencyEntitlementCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionConcurrencyEntitlementUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SubscriptionConcurrencyEntitlementUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SubscriptionConcurrencyEntitlementUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SubscriptionConcurrencyEntitlementCreateBulk is the builder for creating many SubscriptionConcurrencyEntitlement entities in bulk.
type SubscriptionConcurrencyEntitlementCreateBulk struct {
	config
	err      error
	builders []*SubscriptionConcurrencyEntitlementCreate
	conflict []sql.ConflictOption
}

// Save creates the SubscriptionConcurrencyEntitlement entities in the database.
func (_c *SubscriptionConcurrencyEntitlementCreateBulk) Save(ctx context.Context) ([]*SubscriptionConcurrencyEntitlement, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SubscriptionConcurrencyEntitlement, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubscriptionConcurrencyEntitlementMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SubscriptionConcurrencyEntitlementCreateBulk) SaveX(ctx context.Context) []*SubscriptionConcurrencyEntitlement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionConcurrencyEntitlementCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionConcurrencyEntitlementCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionConcurrencyEntitlement.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionConcurrencyEntitlementUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionConcurrencyEntitlementCreateBulk) OnConflict(opts ...sql.ConflictOption) *SubscriptionConcurrencyEntitlementUpsertBulk {
	_c.conflict = opts
	return &SubscriptionConcurrencyEntitlementUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionConcurrencyEntitlement.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionConcurrencyEntitlementCreateBulk) OnConflictColumns(columns ...string) *SubscriptionConcurrencyEntitlementUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionConcurrencyEntitlementUpsertBulk{
		create: _c,
	}
}

// SubscriptionConcurrencyEntitlementUpsertBulk is the builder for "upsert"-ing
// a bulk of SubscriptionConcurrencyEntitlement nodes.
type SubscriptionConcurrencyEntitlementUpsertBulk struct {
	create *SubscriptionConcurrencyEntitlementCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SubscriptionConcurrencyEntitlement.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionConcurrencyEntitlementUpsertBulk) UpdateNewValues() *SubscriptionConcurrencyEntitlementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(subscriptionconcurrencyentitlement.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionConcurrencyEntitlement.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SubscriptionConcurrencyEntitlementUpsertBulk) Ignore() *SubscriptionConcurrencyEntitlementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionConcurrencyEntitlementUpsertBulk) DoNothing() *SubscriptionConcurrencyEntitlementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionConcurrencyEntitlementCreateBulk.OnConflict
// documentation for more info.
func (u *SubscriptionConcurrencyEntitlementUpsertBulk) Update(set func(*SubscriptionConcurrencyEntitlementUpsert)) *SubscriptionConcurrencyEntitlementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionConcurrencyEntitlementUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionConcurrencyEntitlementUpsertBulk) SetUpdatedAt(v time.Time) *SubscriptionConcurrencyEntitlementUpsertBulk {
	return u.Update(func(s *SubscriptionConcurrencyEntitlementUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionConcurrencyEntitlementUpsertBulk) UpdateUpdatedAt() *SubscriptionConcurrencyEntitlementUpsertBulk {
	return u.Update(func(s *SubscriptionConcurrencyEntitlementUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *SubscriptionConcurrencyEntitlementUpsertBulk) SetUserID(v int64) *SubscriptionConcurrencyEntitlementUpsertBulk {
	return u.Update(func(s *SubscriptionConcurrencyEntitlementUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SubscriptionConcurrencyEntitlementUpsertBulk) UpdateUserID() *SubscriptionConcurrencyEntitlementUpsertBulk {
	return u.Update(func(s *SubscriptionConcurrencyEntitlementUpsert) {
		s.UpdateUserID()
	})
}

// SetSubscriptionID sets the "subscription_id" field.
func (u *SubscriptionConcurrencyEntitlementUpsertBulk) SetSubscriptionID(v int64) *SubscriptionConcurrencyEntitlementUpsertBulk {
	return u.Update(func(s *SubscriptionConcurrencyEntitlementUpsert) {
		s.SetSubscriptionID(v)
	})
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *SubscriptionConcurrencyEntitlementUpsertBulk) UpdateSubscriptionID() *SubscriptionConcurrencyEntitlementUpsertBulk {
	return u.Update(func(s *SubscriptionConcurrencyEntitlementUpsert) {
		s.UpdateSubscriptionID()
	})
}

// SetSourceOrderID sets the "source_order_id" field.
func (u *SubscriptionConcurrencyEntitlementUpsertBulk) SetSourceOrderID(v int64) *SubscriptionConcurrencyEntitlementUpsertBulk {
	return u.Update(func(s *SubscriptionConcurrencyEntitlementUpsert) {
		s.SetSourceOrderID(v)
	})
}

// AddSourceOrderID adds v to the "source_order_id" field.
func (u *SubscriptionConcurrencyEntitlementUpsertBulk) AddSourceOrderID(v int64) *SubscriptionConcurrencyEntitlementUpsertBulk {
	return u.Update(func(s *SubscriptionConcurrencyEntitlementUpsert) {
		s.AddSourceOrderID(v)
	})
}

// UpdateSourceOrderID sets the "source_order_id" field to the value that was provided on create.
func (u *SubscriptionConcurrencyEntitlementUpsertBulk) UpdateSourceOrderID() *SubscriptionConcurrencyEntitlementUpsertBulk {
	return u.Update(func(s *SubscriptionConcurrencyEntitlementUpsert) {
		s.UpdateSourceOrderID()
	})
}

// ClearSourceOrderID clears the value of the "source_order_id" field.
func (u *SubscriptionConcurrencyEntitlementUpsertBulk) ClearSourceOrderID() *SubscriptionConcurrencyEntitlementUpsertBulk {
	return u.Update(func(s *SubscriptionConcurrencyEntitlementUpsert) {
		s.ClearSourceOrderID()
	})
}

// SetConcurrency sets the "concurrency" field.
func (u *SubscriptionConcurrencyEntitlementUpsertBulk) SetConcurrency(v int) *SubscriptionConcurrencyEntitlementUpsertBulk {
	return u.Update(func(s *SubscriptionConcurrencyEntitlementUpsert) {
		s.SetConcurrency(v)
	})
}

// AddConcurrency adds v to the "concurrency" field.
func (u *SubscriptionConcurrencyEntitlementUpsertBulk) AddConcurrency(v int) *SubscriptionConcurrencyEntitlementUpsertBulk {
	return u.Update(func(s *SubscriptionConcurrencyEntitlementUpsert) {
		s.AddConcurrency(v)
	})
}

// UpdateConcurrency sets the "concurrency" field to the value that was provided on create.
func (u *SubscriptionConcurrencyEntitlementUpsertBulk) UpdateConcurrency() *SubscriptionConcurrencyEntitlementUpsertBulk {
	return u.Update(func(s *SubscriptionConcurrencyEntitlementUpsert) {
		s.UpdateConcurrency()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *SubscriptionConcurrencyEntitlementUpsertBulk) SetStartsAt(v time.Time) *SubscriptionConcurrencyEntitlementUpsertBulk {
	return u.Update(func(s *SubscriptionConcurrencyEntitlementUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *SubscriptionConcurrencyEntitlementUpsertBulk) UpdateStartsAt() *SubscriptionConcurrencyEntitlementUpsertBulk {
	return u.Update(func(s *SubscriptionConcurrencyEntitlementUpsert) {
		s.UpdateStartsAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *SubscriptionConcurrencyEntitlementUpsertBulk) SetExpiresAt(v time.Time) *SubscriptionConcurrencyEntitlementUpsertBulk {
	return u.Update(func(s *SubscriptionConcurrencyEntitlementUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *SubscriptionConcurrencyEntitlementUpsertBulk) UpdateExpiresAt() *SubscriptionConcurrencyEntitlementUpsertBulk {
	return u.Update(func(s *SubscriptionConcurrencyEntitlementUpsert) {
		s.UpdateExpiresAt()
	})
}

// Exec executes the query.
func (u *SubscriptionConcurrencyEntitlementUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SubscriptionConcurrencyEntitlementCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionConcurrencyEntitlementCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionConcurrencyEntitlementUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
