// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionearlyresetentitlement"
)

// SubscriptionEarlyResetEntitlementCreate is the builder for creating a SubscriptionEarlyResetEntitlement entity.
type SubscriptionEarlyResetEntitlementCreate struct {
	config
	mutation *SubscriptionEarlyResetEntitlementMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *SubscriptionEarlyResetEntitlementCreate) SetCreatedAt(v time.Time) *SubscriptionEarlyResetEntitlementCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SubscriptionEarlyResetEntitlementCreate) SetNillableCreatedAt(v *time.Time) *SubscriptionEarlyResetEntitlementCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SubscriptionEarlyResetEntitlementCreate) SetUpdatedAt(v time.Time) *SubscriptionEarlyResetEntitlementCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SubscriptionEarlyResetEntitlementCreate) SetNillableUpdatedAt(v *time.Time) *SubscriptionEarlyResetEntitlementCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *SubscriptionEarlyResetEntitlementCreate) SetUserID(v int64) *SubscriptionEarlyResetEntitlementCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetSubscriptionID sets the "subscription_id" field.
func (_c *SubscriptionEarlyResetEntitlementCreate) SetSubscriptionID(v int64) *SubscriptionEarlyResetEntitlementCreate {
	_c.mutation.SetSubscriptionID(v)
	return _c
}

// SetSourceOrderID sets the "source_order_id" field.
func (_c *SubscriptionEarlyResetEntitlementCreate) SetSourceOrderID(v int64) *SubscriptionEarlyResetEntitlementCreate {
	_c.mutation.SetSourceOrderID(v)
	return _c
}

// SetNillableSourceOrderID sets the "source_order_id" field if the given value is not nil.
func (_c *SubscriptionEarlyResetEntitlementCreate) SetNillableSourceOrderID(v *int64) *SubscriptionEarlyResetEntitlementCreate {
	if v != nil {
		_c.SetSourceOrderID(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *SubscriptionEarlyResetEntitlementCreate) SetEnabled(v bool) *SubscriptionEarlyResetEntitlementCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *SubscriptionEarlyResetEntitlementCreate) SetNillableEnabled(v *bool) *SubscriptionEarlyResetEntitlementCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetDurationDays sets the "duration_days" field.
func (_c *SubscriptionEarlyResetEntitlementCreate) SetDurationDays(v int) *SubscriptionEarlyResetEntitlementCreate {
	_c.mutation.SetDurationDays(v)
	return _c
}

// SetNillableDurationDays sets the "duration_days" field if the given value is not nil.
func (_c *SubscriptionEarlyResetEntitlementCreate) SetNillableDurationDays(v *int) *SubscriptionEarlyResetEntitlementCreate {
	if v != nil {
		_c.SetDurationDays(*v)
	}
	return _c
}

// SetCustomTerm sets the "custom_term" field.
func (_c *SubscriptionEarlyResetEntitlementCreate) SetCustomTerm(v bool) *SubscriptionEarlyResetEntitlementCreate {
	_c.mutation.SetCustomTerm(v)
	return _c
}

// SetNillableCustomTerm sets the "custom_term" field if the given value is not nil.
func (_c *SubscriptionEarlyResetEntitlementCreate) SetNillableCustomTerm(v *bool) *SubscriptionEarlyResetEntitlementCreate {
	if v != nil {
		_c.SetCustomTerm(*v)
	}
	return _c
}

// SetStartsAt sets the "starts_at" field.
func (_c *SubscriptionEarlyResetEntitlementCreate) SetStartsAt(v time.Time) *SubscriptionEarlyResetEntitlementCreate {
	_c.mutation.SetStartsAt(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *SubscriptionEarlyResetEntitlementCreate) SetExpiresAt(v time.Time) *SubscriptionEarlyResetEntitlementCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// Mutation returns the SubscriptionEarlyResetEntitlementMutation object of the builder.
func (_c *SubscriptionEarlyResetEntitlementCreate) Mutation() *SubscriptionEarlyResetEntitlementMutation {
	return _c.mutation
}

// Save creates the SubscriptionEarlyResetEntitlement in the database.
func (_c *SubscriptionEarlyResetEntitlementCreate) Save(ctx context.Context) (*SubscriptionEarlyResetEntitlement, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SubscriptionEarlyResetEntitlementCreate) SaveX(ctx context.Context) *SubscriptionEarlyResetEntitlement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionEarlyResetEntitlementCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionEarlyResetEntitlementCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SubscriptionEarlyResetEntitlementCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := subscriptionearlyresetentitlement.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := subscriptionearlyresetentitlement.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := subscriptionearlyresetentitlement.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.DurationDays(); !ok {
		v := subscriptionearlyresetentitlement.DefaultDurationDays
		_c.mutation.SetDurationDays(v)
	}
	if _, ok := _c.mutation.CustomTerm(); !ok {
		v := subscriptionearlyresetentitlement.DefaultCustomTerm
		_c.mutation.SetCustomTerm(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SubscriptionEarlyResetEntitlementCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SubscriptionEarlyResetEntitlement.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SubscriptionEarlyResetEntitlement.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "SubscriptionEarlyResetEntitlement.user_id"`)}
	}
	if _, ok := _c.mutation.SubscriptionID(); !ok {
		return &ValidationError{Name: "subscription_id", err: errors.New(`ent: missing required field "SubscriptionEarlyResetEntitlement.subscription_id"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "SubscriptionEarlyResetEntitlement.enabled"`)}
	}
	if _, ok := _c.mutation.DurationDays(); !ok {
		return &ValidationError{Name: "duration_days", err: errors.New(`ent: missing required field "SubscriptionEarlyResetEntitlement.duration_days"`)}
	}
	if v, ok := _c.mutation.DurationDays(); ok {
		if err := subscriptionearlyresetentitlement.DurationDaysValidator(v); err != nil {
			return &ValidationError{Name: "duration_days", err: fmt.Errorf(`ent: validator failed for field "SubscriptionEarlyResetEntitlement.duration_days": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CustomTerm(); !ok {
		return &ValidationError{Name: "custom_term", err: errors.New(`ent: missing required field "SubscriptionEarlyResetEntitlement.custom_term"`)}
	}
	if _, ok := _c.mutation.StartsAt(); !ok {
		return &ValidationError{Name: "starts_at", err: errors.New(`ent: missing required field "SubscriptionEarlyResetEntitlement.starts_at"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "SubscriptionEarlyResetEntitlement.expires_at"`)}
	}
	return nil
}

func (_c *SubscriptionEarlyResetEntitlementCreate) sqlSave(ctx context.Context) (*SubscriptionEarlyResetEntitlement, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SubscriptionEarlyResetEntitlementCreate) createSpec() (*SubscriptionEarlyResetEntitlement, *sqlgraph.CreateSpec) {
	var (
		_node = &SubscriptionEarlyResetEntitlement{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(subscriptionearlyresetentitlement.Table, sqlgraph.NewFieldSpec(subscriptionearlyresetentitlement.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(subscriptionearlyresetentitlement.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionearlyresetentitlement.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(subscriptionearlyresetentitlement.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.SubscriptionID(); ok {
		_spec.SetField(subscriptionearlyresetentitlement.FieldSubscriptionID, field.TypeInt64, value)
		_node.SubscriptionID = value
	}
	if value, ok := _c.mutation.SourceOrderID(); ok {
		_spec.SetField(subscriptionearlyresetentitlement.FieldSourceOrderID, field.TypeInt64, value)
		_node.SourceOrderID = &value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(subscriptionearlyresetentitlement.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.DurationDays(); ok {
		_spec.SetField(subscriptionearlyresetentitlement.FieldDurationDays, field.TypeInt, value)
		_node.DurationDays = value
	}
	if value, ok := _c.mutation.CustomTerm(); ok {
		_spec.SetField(subscriptionearlyresetentitlement.FieldCustomTerm, field.TypeBool, value)
		_node.CustomTerm = value
	}
	if value, ok := _c.mutation.StartsAt(); ok {
		_spec.SetField(subscriptionearlyresetentitlement.FieldStartsAt, field.TypeTime, value)
		_node.StartsAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(subscriptionearlyresetentitlement.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionEarlyResetEntitlement.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionEarlyResetEntitlementUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionEarlyResetEntitlementCreate) OnConflict(opts ...sql.ConflictOption) *SubscriptionEarlyResetEntitlementUpsertOne {
	_c.conflict = opts
	return &SubscriptionEarlyResetEntitlementUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionEarlyResetEntitlement.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionEarlyResetEntitlementCreate) OnConflictColumns(columns ...string) *SubscriptionEarlyResetEntitlementUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionEarlyResetEntitlementUpsertOne{
		create: _c,
	}
}

type (
	// SubscriptionEarlyResetEntitlementUpsertOne is the builder for "upsert"-ing
	//  one SubscriptionEarlyResetEntitlement node.
	SubscriptionEarlyResetEntitlementUpsertOne struct {
		create *SubscriptionEarlyResetEntitlementCreate
	}

	// SubscriptionEarlyResetEntitlementUpsert is the "OnConflict" setter.
	SubscriptionEarlyResetEntitlementUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionEarlyResetEntitlementUpsert) SetUpdatedAt(v time.Time) *SubscriptionEarlyResetEntitlementUpsert {
	u.Set(subscriptionearlyresetentitlement.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionEarlyResetEntitlementUpsert) UpdateUpdatedAt() *SubscriptionEarlyResetEntitlementUpsert {
	u.SetExcluded(subscriptionearlyresetentitlement.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *SubscriptionEarlyResetEntitlementUpsert) SetUserID(v int64) *SubscriptionEarlyResetEntitlementUpsert {
	u.Set(subscriptionearlyresetentitlement.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SubscriptionEarlyResetEntitlementUpsert) UpdateUserID() *SubscriptionEarlyResetEntitlementUpsert {
	u.SetExcluded(subscriptionearlyresetentitlement.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *SubscriptionEarlyResetEntitlementUpsert) AddUserID(v int64) *SubscriptionEarlyResetEntitlementUpsert {
	u.Add(subscriptionearlyresetentitlement.FieldUserID, v)
	return u
}

// SetSubscriptionID sets the "subscription_id" field.
func (u *SubscriptionEarlyResetEntitlementUpsert) SetSubscriptionID(v int64) *SubscriptionEarlyResetEntitlementUpsert {
	u.Set(subscriptionearlyresetentitlement.FieldSubscriptionID, v)
	return u
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *SubscriptionEarlyResetEntitlementUpsert) UpdateSubscriptionID() *SubscriptionEarlyResetEntitlementUpsert {
	u.SetExcluded(subscriptionearlyresetentitlement.FieldSubscriptionID)
	return u
}

// AddSubscriptionID adds v to the "subscription_id" field.
func (u *SubscriptionEarlyResetEntitlementUpsert) AddSubscriptionID(v int64) *SubscriptionEarlyResetEntitlementUpsert {
	u.Add(subscriptionearlyresetentitlement.FieldSubscriptionID, v)
	return u
}

// SetSourceOrderID sets the "source_order_id" field.
func (u *SubscriptionEarlyResetEntitlementUpsert) SetSourceOrderID(v int64) *SubscriptionEarlyResetEntitlementUpsert {
	u.Set(subscriptionearlyresetentitlement.FieldSourceOrderID, v)
	return u
}

// UpdateSourceOrderID sets the "source_order_id" field to the value that was provided on create.
func (u *SubscriptionEarlyResetEntitlementUpsert) UpdateSourceOrderID() *SubscriptionEarlyResetEntitlementUpsert {
	u.SetExcluded(subscriptionearlyresetentitlement.FieldSourceOrderID)
	return u
}

// AddSourceOrderID adds v to the "source_order_id" field.
func (u *SubscriptionEarlyResetEntitlementUpsert) AddSourceOrderID(v int64) *SubscriptionEarlyResetEntitlementUpsert {
	u.Add(subscriptionearlyresetentitlement.FieldSourceOrderID, v)
	return u
}

// ClearSourceOrderID clears the value of the "source_order_id" field.
func (u *SubscriptionEarlyResetEntitlementUpsert) ClearSourceOrderID() *SubscriptionEarlyResetEntitlementUpsert {
	u.SetNull(subscriptionearlyresetentitlement.FieldSourceOrderID)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *SubscriptionEarlyResetEntitlementUpsert) SetEnabled(v bool) *SubscriptionEarlyResetEntitlementUpsert {
	u.Set(subscriptionearlyresetentitlement.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *SubscriptionEarlyResetEntitlementUpsert) UpdateEnabled() *SubscriptionEarlyResetEntitlementUpsert {
	u.SetExcluded(subscriptionearlyresetentitlement.FieldEnabled)
	return u
}

// SetDurationDays sets the "duration_days" field.
func (u *SubscriptionEarlyResetEntitlementUpsert) SetDurationDays(v int) *SubscriptionEarlyResetEntitlementUpsert {
	u.Set(subscriptionearlyresetentitlement.FieldDurationDays, v)
	return u
}

// UpdateDurationDays sets the "duration_days" field to the value that was provided on create.
func (u *SubscriptionEarlyResetEntitlementUpsert) UpdateDurationDays() *SubscriptionEarlyResetEntitlementUpsert {
	u.SetExcluded(subscriptionearlyresetentitlement.FieldDurationDays)
	return u
}

// AddDurationDays adds v to the "duration_days" field.
func (u *SubscriptionEarlyResetEntitlementUpsert) AddDurationDays(v int) *SubscriptionEarlyResetEntitlementUpsert {
	u.Add(subscriptionearlyresetentitlement.FieldDurationDays, v)
	return u
}

// SetCustomTerm sets the "custom_term" field.
func (u *SubscriptionEarlyResetEntitlementUpsert) SetCustomTerm(v bool) *SubscriptionEarlyResetEntitlementUpsert {
	u.Set(subscriptionearlyresetentitlement.FieldCustomTerm, v)
	return u
}

// UpdateCustomTerm sets the "custom_term" field to the value that was provided on create.
func (u *SubscriptionEarlyResetEntitlementUpsert) UpdateCustomTerm() *SubscriptionEarlyResetEntitlementUpsert {
	u.SetExcluded(subscriptionearlyresetentitlement.FieldCustomTerm)
	return u
}

// SetStartsAt sets the "starts_at" field.
func (u *SubscriptionEarlyResetEntitlementUpsert) SetStartsAt(v time.Time) *SubscriptionEarlyResetEntitlementUpsert {
	u.Set(subscriptionearlyresetentitlement.FieldStartsAt, v)
	return u
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *SubscriptionEarlyResetEntitlementUpsert) UpdateStartsAt() *SubscriptionEarlyResetEntitlementUpsert {
	u.SetExcluded(subscriptionearlyresetentitlement.FieldStartsAt)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *SubscriptionEarlyResetEntitlementUpsert) SetExpiresAt(v time.Time) *SubscriptionEarlyResetEntitlementUpsert {
	u.Set(subscriptionearlyresetentitlement.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *SubscriptionEarlyResetEntitlementUpsert) UpdateExpiresAt() *SubscriptionEarlyResetEntitlementUpsert {
	u.SetExcluded(subscriptionearlyresetentitlement.FieldExpiresAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SubscriptionEarlyResetEntitlement.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionEarlyResetEntitlementUpsertOne) UpdateNewValues() *SubscriptionEarlyResetEntitlementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(subscriptionearlyresetentitlement.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionEarlyResetEntitlement.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SubscriptionEarlyResetEntitlementUpsertOne) Ignore() *SubscriptionEarlyResetEntitlementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionEarlyResetEntitlementUpsertOne) DoNothing() *SubscriptionEarlyResetEntitlementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionEarlyResetEntitlementCreate.OnConflict
// documentation for more info.
func (u *SubscriptionEarlyResetEntitlementUpsertOne) Update(set func(*SubscriptionEarlyResetEntitlementUpsert)) *SubscriptionEarlyResetEntitlementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionEarlyResetEntitlementUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionEarlyResetEntitlementUpsertOne) SetUpdatedAt(v time.Time) *SubscriptionEarlyResetEntitlementUpsertOne {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionEarlyResetEntitlementUpsertOne) UpdateUpdatedAt() *SubscriptionEarlyResetEntitlementUpsertOne {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *SubscriptionEarlyResetEntitlementUpsertOne) SetUserID(v int64) *SubscriptionEarlyResetEntitlementUpsertOne {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *SubscriptionEarlyResetEntitlementUpsertOne) AddUserID(v int64) *SubscriptionEarlyResetEntitlementUpsertOne {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SubscriptionEarlyResetEntitlementUpsertOne) UpdateUserID() *SubscriptionEarlyResetEntitlementUpsertOne {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.UpdateUserID()
	})
}

// SetSubscriptionID sets the "subscription_id" field.
func (u *SubscriptionEarlyResetEntitlementUpsertOne) SetSubscriptionID(v int64) *SubscriptionEarlyResetEntitlementUpsertOne {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.SetSubscriptionID(v)
	})
}

// AddSubscriptionID adds v to the "subscription_id" field.
func (u *SubscriptionEarlyResetEntitlementUpsertOne) AddSubscriptionID(v int64) *SubscriptionEarlyResetEntitlementUpsertOne {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.AddSubscriptionID(v)
	})
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *SubscriptionEarlyResetEntitlementUpsertOne) UpdateSubscriptionID() *SubscriptionEarlyResetEntitlementUpsertOne {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.UpdateSubscriptionID()
	})
}

// SetSourceOrderID sets the "source_order_id" field.
func (u *SubscriptionEarlyResetEntitlementUpsertOne) SetSourceOrderID(v int64) *SubscriptionEarlyResetEntitlementUpsertOne {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.SetSourceOrderID(v)
	})
}

// AddSourceOrderID adds v to the "source_order_id" field.
func (u *SubscriptionEarlyResetEntitlementUpsertOne) AddSourceOrderID(v int64) *SubscriptionEarlyResetEntitlementUpsertOne {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.AddSourceOrderID(v)
	})
}

// UpdateSourceOrderID sets the "source_order_id" field to the value that was provided on create.
func (u *SubscriptionEarlyResetEntitlementUpsertOne) UpdateSourceOrderID() *SubscriptionEarlyResetEntitlementUpsertOne {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.UpdateSourceOrderID()
	})
}

// ClearSourceOrderID clears the value of the "source_order_id" field.
func (u *SubscriptionEarlyResetEntitlementUpsertOne) ClearSourceOrderID() *SubscriptionEarlyResetEntitlementUpsertOne {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.ClearSourceOrderID()
	})
}

// SetEnabled sets the "enabled" field.
func (u *SubscriptionEarlyResetEntitlementUpsertOne) SetEnabled(v bool) *SubscriptionEarlyResetEntitlementUpsertOne {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *SubscriptionEarlyResetEntitlementUpsertOne) UpdateEnabled() *SubscriptionEarlyResetEntitlementUpsertOne {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.UpdateEnabled()
	})
}

// SetDurationDays sets the "duration_days" field.
func (u *SubscriptionEarlyResetEntitlementUpsertOne) SetDurationDays(v int) *SubscriptionEarlyResetEntitlementUpsertOne {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.SetDurationDays(v)
	})
}

// AddDurationDays adds v to the "duration_days" field.
func (u *SubscriptionEarlyResetEntitlementUpsertOne) AddDurationDays(v int) *SubscriptionEarlyResetEntitlementUpsertOne {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.AddDurationDays(v)
	})
}

// UpdateDurationDays sets the "duration_days" field to the value that was provided on create.
func (u *SubscriptionEarlyResetEntitlementUpsertOne) UpdateDurationDays() *SubscriptionEarlyResetEntitlementUpsertOne {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.UpdateDurationDays()
	})
}

// SetCustomTerm sets the "custom_term" field.
func (u *SubscriptionEarlyResetEntitlementUpsertOne) SetCustomTerm(v bool) *SubscriptionEarlyResetEntitlementUpsertOne {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.SetCustomTerm(v)
	})
}

// UpdateCustomTerm sets the "custom_term" field to the value that was provided on create.
func (u *SubscriptionEarlyResetEntitlementUpsertOne) UpdateCustomTerm() *SubscriptionEarlyResetEntitlementUpsertOne {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.UpdateCustomTerm()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *SubscriptionEarlyResetEntitlementUpsertOne) SetStartsAt(v time.Time) *SubscriptionEarlyResetEntitlementUpsertOne {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *SubscriptionEarlyResetEntitlementUpsertOne) UpdateStartsAt() *SubscriptionEarlyResetEntitlementUpsertOne {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.UpdateStartsAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *SubscriptionEarlyResetEntitlementUpsertOne) SetExpiresAt(v time.Time) *SubscriptionEarlyResetEntitlementUpsertOne {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *SubscriptionEarlyResetEntitlementUpsertOne) UpdateExpiresAt() *SubscriptionEarlyResetEntitlementUpsertOne {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.UpdateExpiresAt()
	})
}

// Exec executes the query.
func (u *SubscriptionEarlyResetEntitlementUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionEarlyResetEntitlementCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionEarlyResetEntitlementUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SubscriptionEarlyResetEntitlementUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SubscriptionEarlyResetEntitlementUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SubscriptionEarlyResetEntitlementCreateBulk is the builder for creating many SubscriptionEarlyResetEntitlement entities in bulk.
type SubscriptionEarlyResetEntitlementCreateBulk struct {
	config
	err      error
	builders []*SubscriptionEarlyResetEntitlementCreate
	conflict []sql.ConflictOption
}

// Save creates the SubscriptionEarlyResetEntitlement entities in the database.
func (_c *SubscriptionEarlyResetEntitlementCreateBulk) Save(ctx context.Context) ([]*SubscriptionEarlyResetEntitlement, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SubscriptionEarlyResetEntitlement, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubscriptionEarlyResetEntitlementMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SubscriptionEarlyResetEntitlementCreateBulk) SaveX(ctx context.Context) []*SubscriptionEarlyResetEntitlement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionEarlyResetEntitlementCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionEarlyResetEntitlementCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionEarlyResetEntitlement.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionEarlyResetEntitlementUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionEarlyResetEntitlementCreateBulk) OnConflict(opts ...sql.ConflictOption) *SubscriptionEarlyResetEntitlementUpsertBulk {
	_c.conflict = opts
	return &SubscriptionEarlyResetEntitlementUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionEarlyResetEntitlement.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionEarlyResetEntitlementCreateBulk) OnConflictColumns(columns ...string) *SubscriptionEarlyResetEntitlementUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionEarlyResetEntitlementUpsertBulk{
		create: _c,
	}
}

// SubscriptionEarlyResetEntitlementUpsertBulk is the builder for "upsert"-ing
// a bulk of SubscriptionEarlyResetEntitlement nodes.
type SubscriptionEarlyResetEntitlementUpsertBulk struct {
	create *SubscriptionEarlyResetEntitlementCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SubscriptionEarlyResetEntitlement.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionEarlyResetEntitlementUpsertBulk) UpdateNewValues() *SubscriptionEarlyResetEntitlementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(subscriptionearlyresetentitlement.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionEarlyResetEntitlement.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SubscriptionEarlyResetEntitlementUpsertBulk) Ignore() *SubscriptionEarlyResetEntitlementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionEarlyResetEntitlementUpsertBulk) DoNothing() *SubscriptionEarlyResetEntitlementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionEarlyResetEntitlementCreateBulk.OnConflict
// documentation for more info.
func (u *SubscriptionEarlyResetEntitlementUpsertBulk) Update(set func(*SubscriptionEarlyResetEntitlementUpsert)) *SubscriptionEarlyResetEntitlementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionEarlyResetEntitlementUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionEarlyResetEntitlementUpsertBulk) SetUpdatedAt(v time.Time) *SubscriptionEarlyResetEntitlementUpsertBulk {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionEarlyResetEntitlementUpsertBulk) UpdateUpdatedAt() *SubscriptionEarlyResetEntitlementUpsertBulk {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *SubscriptionEarlyResetEntitlementUpsertBulk) SetUserID(v int64) *SubscriptionEarlyResetEntitlementUpsertBulk {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *SubscriptionEarlyResetEntitlementUpsertBulk) AddUserID(v int64) *SubscriptionEarlyResetEntitlementUpsertBulk {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SubscriptionEarlyResetEntitlementUpsertBulk) UpdateUserID() *SubscriptionEarlyResetEntitlementUpsertBulk {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.UpdateUserID()
	})
}

// SetSubscriptionID sets the "subscription_id" field.
func (u *SubscriptionEarlyResetEntitlementUpsertBulk) SetSubscriptionID(v int64) *SubscriptionEarlyResetEntitlementUpsertBulk {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.SetSubscriptionID(v)
	})
}

// AddSubscriptionID adds v to the "subscription_id" field.
func (u *SubscriptionEarlyResetEntitlementUpsertBulk) AddSubscriptionID(v int64) *SubscriptionEarlyResetEntitlementUpsertBulk {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.AddSubscriptionID(v)
	})
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *SubscriptionEarlyResetEntitlementUpsertBulk) UpdateSubscriptionID() *SubscriptionEarlyResetEntitlementUpsertBulk {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.UpdateSubscriptionID()
	})
}

// SetSourceOrderID sets the "source_order_id" field.
func (u *SubscriptionEarlyResetEntitlementUpsertBulk) SetSourceOrderID(v int64) *SubscriptionEarlyResetEntitlementUpsertBulk {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.SetSourceOrderID(v)
	})
}

// AddSourceOrderID adds v to the "source_order_id" field.
func (u *SubscriptionEarlyResetEntitlementUpsertBulk) AddSourceOrderID(v int64) *SubscriptionEarlyResetEntitlementUpsertBulk {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.AddSourceOrderID(v)
	})
}

// UpdateSourceOrderID sets the "source_order_id" field to the value that was provided on create.
func (u *SubscriptionEarlyResetEntitlementUpsertBulk) UpdateSourceOrderID() *SubscriptionEarlyResetEntitlementUpsertBulk {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.UpdateSourceOrderID()
	})
}

// ClearSourceOrderID clears the value of the "source_order_id" field.
func (u *SubscriptionEarlyResetEntitlementUpsertBulk) ClearSourceOrderID() *SubscriptionEarlyResetEntitlementUpsertBulk {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.ClearSourceOrderID()
	})
}

// SetEnabled sets the "enabled" field.
func (u *SubscriptionEarlyResetEntitlementUpsertBulk) SetEnabled(v bool) *SubscriptionEarlyResetEntitlementUpsertBulk {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *SubscriptionEarlyResetEntitlementUpsertBulk) UpdateEnabled() *SubscriptionEarlyResetEntitlementUpsertBulk {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.UpdateEnabled()
	})
}

// SetDurationDays sets the "duration_days" field.
func (u *SubscriptionEarlyResetEntitlementUpsertBulk) SetDurationDays(v int) *SubscriptionEarlyResetEntitlementUpsertBulk {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.SetDurationDays(v)
	})
}

// AddDurationDays adds v to the "duration_days" field.
func (u *SubscriptionEarlyResetEntitlementUpsertBulk) AddDurationDays(v int) *SubscriptionEarlyResetEntitlementUpsertBulk {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.AddDurationDays(v)
	})
}

// UpdateDurationDays sets the "duration_days" field to the value that was provided on create.
func (u *SubscriptionEarlyResetEntitlementUpsertBulk) UpdateDurationDays() *SubscriptionEarlyResetEntitlementUpsertBulk {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.UpdateDurationDays()
	})
}

// SetCustomTerm sets the "custom_term" field.
func (u *SubscriptionEarlyResetEntitlementUpsertBulk) SetCustomTerm(v bool) *SubscriptionEarlyResetEntitlementUpsertBulk {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.SetCustomTerm(v)
	})
}

// UpdateCustomTerm sets the "custom_term" field to the value that was provided on create.
func (u *SubscriptionEarlyResetEntitlementUpsertBulk) UpdateCustomTerm() *SubscriptionEarlyResetEntitlementUpsertBulk {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.UpdateCustomTerm()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *SubscriptionEarlyResetEntitlementUpsertBulk) SetStartsAt(v time.Time) *SubscriptionEarlyResetEntitlementUpsertBulk {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *SubscriptionEarlyResetEntitlementUpsertBulk) UpdateStartsAt() *SubscriptionEarlyResetEntitlementUpsertBulk {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.UpdateStartsAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *SubscriptionEarlyResetEntitlementUpsertBulk) SetExpiresAt(v time.Time) *SubscriptionEarlyResetEntitlementUpsertBulk {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *SubscriptionEarlyResetEntitlementUpsertBulk) UpdateExpiresAt() *SubscriptionEarlyResetEntitlementUpsertBulk {
	return u.Update(func(s *SubscriptionEarlyResetEntitlementUpsert) {
		s.UpdateExpiresAt()
	})
}

// Exec executes the query.
func (u *SubscriptionEarlyResetEntitlementUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SubscriptionEarlyResetEntitlementCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionEarlyResetEntitlementCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionEarlyResetEntitlementUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
