// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/waitlistentry"
)

// WaitlistEntry is the model entity for the WaitlistEntry schema.
type WaitlistEntry struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// ConfirmationAttemptedAt holds the value of the "confirmation_attempted_at" field.
	ConfirmationAttemptedAt *time.Time `json:"confirmation_attempted_at,omitempty"`
	// ConfirmationSentAt holds the value of the "confirmation_sent_at" field.
	ConfirmationSentAt *time.Time `json:"confirmation_sent_at,omitempty"`
	// ApprovedAt holds the value of the "approved_at" field.
	ApprovedAt *time.Time `json:"approved_at,omitempty"`
	// ApprovedBy holds the value of the "approved_by" field.
	ApprovedBy *int64 `json:"approved_by,omitempty"`
	// GrantedUserID holds the value of the "granted_user_id" field.
	GrantedUserID *int64 `json:"granted_user_id,omitempty"`
	// ApprovalNoticeAttemptedAt holds the value of the "approval_notice_attempted_at" field.
	ApprovalNoticeAttemptedAt *time.Time `json:"approval_notice_attempted_at,omitempty"`
	// ApprovalNoticeSentAt holds the value of the "approval_notice_sent_at" field.
	ApprovalNoticeSentAt *time.Time `json:"approval_notice_sent_at,omitempty"`
	selectValues         sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WaitlistEntry) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case waitlistentry.FieldID, waitlistentry.FieldApprovedBy, waitlistentry.FieldGrantedUserID:
			values[i] = new(sql.NullInt64)
		case waitlistentry.FieldEmail:
			values[i] = new(sql.NullString)
		case waitlistentry.FieldCreatedAt, waitlistentry.FieldConfirmationAttemptedAt, waitlistentry.FieldConfirmationSentAt, waitlistentry.FieldApprovedAt, waitlistentry.FieldApprovalNoticeAttemptedAt, waitlistentry.FieldApprovalNoticeSentAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WaitlistEntry fields.
func (_m *WaitlistEntry) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case waitlistentry.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case waitlistentry.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case waitlistentry.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case waitlistentry.FieldConfirmationAttemptedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field confirmation_attempted_at", values[i])
			} else if value.Valid {
				_m.ConfirmationAttemptedAt = new(time.Time)
				*_m.ConfirmationAttemptedAt = value.Time
			}
		case waitlistentry.FieldConfirmationSentAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field confirmation_sent_at", values[i])
			} else if value.Valid {
				_m.ConfirmationSentAt = new(time.Time)
				*_m.ConfirmationSentAt = value.Time
			}
		case waitlistentry.FieldApprovedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field approved_at", values[i])
			} else if value.Valid {
				_m.ApprovedAt = new(time.Time)
				*_m.ApprovedAt = value.Time
			}
		case waitlistentry.FieldApprovedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field approved_by", values[i])
			} else if value.Valid {
				_m.ApprovedBy = new(int64)
				*_m.ApprovedBy = value.Int64
			}
		case waitlistentry.FieldGrantedUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field granted_user_id", values[i])
			} else if value.Valid {
				_m.GrantedUserID = new(int64)
				*_m.GrantedUserID = value.Int64
			}
		case waitlistentry.FieldApprovalNoticeAttemptedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field approval_notice_attempted_at", values[i])
			} else if value.Valid {
				_m.ApprovalNoticeAttemptedAt = new(time.Time)
				*_m.ApprovalNoticeAttemptedAt = value.Time
			}
		case waitlistentry.FieldApprovalNoticeSentAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field approval_notice_sent_at", values[i])
			} else if value.Valid {
				_m.ApprovalNoticeSentAt = new(time.Time)
				*_m.ApprovalNoticeSentAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WaitlistEntry.
// This includes values selected through modifiers, order, etc.
func (_m *WaitlistEntry) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this WaitlistEntry.
// Note that you need to call WaitlistEntry.Unwrap() before calling this method if this WaitlistEntry
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *WaitlistEntry) Update() *WaitlistEntryUpdateOne {
	return NewWaitlistEntryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the WaitlistEntry entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *WaitlistEntry) Unwrap() *WaitlistEntry {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: WaitlistEntry is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *WaitlistEntry) String() string {
	var builder strings.Builder
	builder.WriteString("WaitlistEntry(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ConfirmationAttemptedAt; v != nil {
		builder.WriteString("confirmation_attempted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ConfirmationSentAt; v != nil {
		builder.WriteString("confirmation_sent_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ApprovedAt; v != nil {
		builder.WriteString("approved_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ApprovedBy; v != nil {
		builder.WriteString("approved_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.GrantedUserID; v != nil {
		builder.WriteString("granted_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ApprovalNoticeAttemptedAt; v != nil {
		builder.WriteString("approval_notice_attempted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ApprovalNoticeSentAt; v != nil {
		builder.WriteString("approval_notice_sent_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// WaitlistEntries is a parsable slice of WaitlistEntry.
type WaitlistEntries []*WaitlistEntry
