package service

import (
	"bufio"
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"

	"github.com/Wei-Shaw/sub2api/internal/pkg/openai_compat"
	"github.com/gin-gonic/gin"
)

type openAICompactionV2ResponseStats struct {
	OutputItemCount int
	CompactionCount int
	SawCompleted    bool
	TerminalType    string
	ProtocolErr     error
}

type openAICompactionV2Event struct {
	Type     json.RawMessage `json:"type"`
	Item     json.RawMessage `json:"item"`
	Response json.RawMessage `json:"response"`
}

// Forward wraps protocol-sensitive attempts in an isolated response writer.
// No branch can expose a successful remote compaction response until it has
// passed the same validation Codex applies to the final downstream payload.
func (s *OpenAIGatewayService) Forward(ctx context.Context, c *gin.Context, account *Account, body []byte) (*OpenAIForwardResult, error) {
	kind := GetOpenAIRequestKind(c)
	if kind == OpenAIRequestKindStandard {
		kind = ClassifyOpenAIRequest(body)
		SetOpenAIRequestKind(c, kind)
	}
	if kind != OpenAIRequestKindRemoteCompactionV2 || c == nil || c.Writer == nil {
		return s.forward(ctx, c, account, body)
	}

	// The Responses-to-Chat bridge drops compaction_trigger and therefore can
	// never produce the opaque compaction item Codex requires. This is a local
	// capability mismatch, not an account health failure.
	if account != nil && !account.IsGrok() && !account.IsOpenAIPassthroughEnabled() && account.Type == AccountTypeAPIKey && !openai_compat.ShouldUseResponsesAPI(account.Extra) {
		failoverErr := s.newOpenAIStreamFailoverError(
			c,
			account,
			false,
			"",
			nil,
			"remote compaction v2 requires a Responses API upstream",
		)
		failoverErr.DoNotPenalizeAccount = true
		return nil, failoverErr
	}

	realWriter := c.Writer
	attemptWriter := newOpenAICompactionV2AttemptWriter(realWriter, resolveUpstreamResponseReadLimit(s.cfg))
	c.Writer = attemptWriter
	defer func() {
		c.Writer = realWriter
	}()

	downstreamStream := newOpenAIRequestView(body).Stream
	keepaliveInterval := time.Duration(0)
	if downstreamStream && s != nil && s.cfg != nil && s.cfg.Gateway.StreamKeepaliveInterval > 0 {
		keepaliveInterval = time.Duration(s.cfg.Gateway.StreamKeepaliveInterval) * time.Second
	}
	attemptCtx, cancelAttempt := context.WithTimeout(normalizeOpenAICompactionV2Context(ctx), s.openAICompactionV2TotalTimeout())
	defer cancelAttempt()
	stopKeepalive := attemptWriter.startKeepalive(attemptCtx, keepaliveInterval)
	result, err := s.forward(attemptCtx, c, account, body)
	stopKeepalive()
	if err != nil {
		var failoverErr *UpstreamFailoverError
		if errors.As(err, &failoverErr) {
			return result, err
		}
		// A keepalive comment may already have committed SSE headers. Never append
		// a buffered JSON error (or an unterminated partial event stream) after it;
		// let the handler emit one protocol-valid response.failed event instead.
		if downstreamStream && !openAICompactionV2BodyHasTerminalEvent(attemptWriter.Body()) {
			return result, fmt.Errorf("remote compaction v2 upstream error: %w", err)
		}
		// Preserve explicit non-failover errors generated by the selected branch.
		if commitErr := attemptWriter.Commit(); commitErr != nil {
			return result, fmt.Errorf("commit remote compaction error response: %w", commitErr)
		}
		return result, err
	}

	if attemptErr := attemptWriter.Err(); attemptErr != nil {
		return nil, s.newOpenAICompactionV2AttemptFailoverError(c, account, attemptWriter, attemptErr)
	}
	if validationErr := validateOpenAICompactionV2ResponseBody(attemptWriter.Body(), downstreamStream); validationErr != nil {
		return nil, s.newOpenAICompactionV2AttemptFailoverError(c, account, attemptWriter, validationErr)
	}
	if commitErr := attemptWriter.Commit(); commitErr != nil {
		return result, fmt.Errorf("commit remote compaction response: %w", commitErr)
	}
	return result, nil
}

const defaultOpenAICompactionV2TotalTimeout = 30 * time.Minute

func normalizeOpenAICompactionV2Context(ctx context.Context) context.Context {
	if ctx == nil {
		return context.Background()
	}
	return ctx
}

func decodeOpenAICompactionV2Event(data []byte) (string, openAICompactionV2Event, error) {
	var event openAICompactionV2Event
	if err := json.Unmarshal(data, &event); err != nil {
		return "", event, fmt.Errorf("invalid event JSON: %w", err)
	}
	var eventType string
	if len(event.Type) == 0 || json.Unmarshal(event.Type, &eventType) != nil {
		return "", event, errors.New("event type is required and must be a string")
	}
	return eventType, event, nil
}

func inspectOpenAICompactionV2OutputItem(raw json.RawMessage, stats *openAICompactionV2ResponseStats) {
	if stats == nil || len(raw) == 0 {
		return
	}
	var item struct {
		Type             json.RawMessage `json:"type"`
		EncryptedContent json.RawMessage `json:"encrypted_content"`
	}
	if json.Unmarshal(raw, &item) != nil {
		return
	}
	var itemType string
	if len(item.Type) == 0 || json.Unmarshal(item.Type, &itemType) != nil {
		return
	}
	stats.OutputItemCount++
	switch itemType {
	case "compaction", "compaction_summary":
		var encryptedContent string
		if len(item.EncryptedContent) > 0 && json.Unmarshal(item.EncryptedContent, &encryptedContent) == nil {
			stats.CompactionCount++
		}
	}
}

func validateOpenAICompactionV2Usage(raw json.RawMessage) error {
	if len(raw) == 0 || bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		return nil
	}
	var usage struct {
		InputTokens        *int64          `json:"input_tokens"`
		OutputTokens       *int64          `json:"output_tokens"`
		TotalTokens        *int64          `json:"total_tokens"`
		InputTokenDetails  json.RawMessage `json:"input_tokens_details"`
		OutputTokenDetails json.RawMessage `json:"output_tokens_details"`
	}
	if err := json.Unmarshal(raw, &usage); err != nil {
		return fmt.Errorf("response.usage is invalid: %w", err)
	}
	if usage.InputTokens == nil || usage.OutputTokens == nil || usage.TotalTokens == nil {
		return errors.New("response.usage must include input_tokens, output_tokens, and total_tokens")
	}
	if len(usage.InputTokenDetails) > 0 && !bytes.Equal(bytes.TrimSpace(usage.InputTokenDetails), []byte("null")) {
		var details struct {
			CachedTokens *int64 `json:"cached_tokens"`
		}
		if err := json.Unmarshal(usage.InputTokenDetails, &details); err != nil || details.CachedTokens == nil {
			return errors.New("response.usage.input_tokens_details.cached_tokens is required")
		}
	}
	if len(usage.OutputTokenDetails) > 0 && !bytes.Equal(bytes.TrimSpace(usage.OutputTokenDetails), []byte("null")) {
		var details struct {
			ReasoningTokens *int64 `json:"reasoning_tokens"`
		}
		if err := json.Unmarshal(usage.OutputTokenDetails, &details); err != nil || details.ReasoningTokens == nil {
			return errors.New("response.usage.output_tokens_details.reasoning_tokens is required")
		}
	}
	return nil
}

func validateOpenAICompactionV2CompletedResponse(raw json.RawMessage) (string, error) {
	if len(raw) == 0 {
		return "", errors.New("response.completed.response is required")
	}
	var response struct {
		ID      json.RawMessage `json:"id"`
		Usage   json.RawMessage `json:"usage"`
		EndTurn json.RawMessage `json:"end_turn"`
	}
	if err := json.Unmarshal(raw, &response); err != nil {
		return "", fmt.Errorf("response.completed.response is invalid: %w", err)
	}
	var responseID string
	if len(response.ID) == 0 || json.Unmarshal(response.ID, &responseID) != nil {
		return "", errors.New("response.completed.response.id is required and must be a string")
	}
	if err := validateOpenAICompactionV2Usage(response.Usage); err != nil {
		return "", err
	}
	if len(response.EndTurn) > 0 && !bytes.Equal(bytes.TrimSpace(response.EndTurn), []byte("null")) {
		var endTurn bool
		if err := json.Unmarshal(response.EndTurn, &endTurn); err != nil {
			return "", errors.New("response.completed.response.end_turn must be a boolean")
		}
	}
	return responseID, nil
}

func inspectOpenAICompactionV2Payload(data []byte, stats *openAICompactionV2ResponseStats) {
	if stats == nil || stats.SawCompleted || stats.ProtocolErr != nil {
		return
	}
	eventType, event, err := decodeOpenAICompactionV2Event(data)
	if err != nil {
		stats.ProtocolErr = err
		return
	}
	switch eventType {
	case "response.output_item.done":
		inspectOpenAICompactionV2OutputItem(event.Item, stats)
	case "response.completed":
		_, validationErr := validateOpenAICompactionV2CompletedResponse(event.Response)
		if validationErr != nil {
			stats.ProtocolErr = validationErr
			return
		}
		stats.SawCompleted = true
		stats.TerminalType = eventType
	case "response.failed", "response.incomplete", "response.cancelled", "response.canceled":
		stats.TerminalType = eventType
	}
}

func inspectOpenAICompactionV2SSE(body []byte) openAICompactionV2ResponseStats {
	stats := openAICompactionV2ResponseStats{}
	forEachOpenAISSEEventPayload(string(body), func(_ string, data []byte) {
		inspectOpenAICompactionV2Payload(data, &stats)
	})
	return stats
}

func inspectOpenAICompactionV2JSON(body []byte) openAICompactionV2ResponseStats {
	stats := openAICompactionV2ResponseStats{}
	var response struct {
		ID     json.RawMessage   `json:"id"`
		Status json.RawMessage   `json:"status"`
		Output []json.RawMessage `json:"output"`
		Usage  json.RawMessage   `json:"usage"`
	}
	if err := json.Unmarshal(body, &response); err != nil {
		stats.ProtocolErr = fmt.Errorf("invalid response JSON: %w", err)
		return stats
	}
	var responseID string
	if len(response.ID) == 0 || json.Unmarshal(response.ID, &responseID) != nil {
		stats.ProtocolErr = errors.New("response.id is required and must be a string")
		return stats
	}
	var status string
	if len(response.Status) == 0 || json.Unmarshal(response.Status, &status) != nil || strings.TrimSpace(status) != "completed" {
		stats.ProtocolErr = errors.New("response.status must be completed")
		return stats
	}
	if err := validateOpenAICompactionV2Usage(response.Usage); err != nil {
		stats.ProtocolErr = err
		return stats
	}
	for _, item := range response.Output {
		inspectOpenAICompactionV2OutputItem(item, &stats)
	}
	stats.SawCompleted = true
	return stats
}

func validateOpenAICompactionV2Stats(stats openAICompactionV2ResponseStats) error {
	if stats.ProtocolErr != nil {
		return fmt.Errorf("remote compaction v2 response protocol error: %w", stats.ProtocolErr)
	}
	if stats.TerminalType != "" && stats.TerminalType != "response.completed" {
		return fmt.Errorf("remote compaction v2 response terminated with %s", stats.TerminalType)
	}
	if !stats.SawCompleted {
		return errors.New("remote compaction v2 response closed before response.completed")
	}
	if stats.CompactionCount != 1 {
		return fmt.Errorf(
			"remote compaction v2 expected exactly one compaction output item, got %d from %d output items",
			stats.CompactionCount,
			stats.OutputItemCount,
		)
	}
	return nil
}

func validateOpenAICompactionV2ResponseBody(body []byte, downstreamStream bool) error {
	if len(bytes.TrimSpace(body)) == 0 {
		return errors.New("remote compaction v2 response body is empty")
	}
	if bodyHasSSEFraming(body) {
		return validateOpenAICompactionV2Stats(inspectOpenAICompactionV2SSE(body))
	}
	if downstreamStream {
		return errors.New("remote compaction v2 expected an event-stream response")
	}
	return validateOpenAICompactionV2Stats(inspectOpenAICompactionV2JSON(body))
}

func openAICompactionV2PayloadIsTerminal(data []byte) bool {
	eventType, _, err := decodeOpenAICompactionV2Event(data)
	if err != nil {
		return false
	}
	switch eventType {
	case "response.completed", "response.failed", "response.incomplete", "response.cancelled", "response.canceled":
		return true
	default:
		return false
	}
}

func openAICompactionV2BodyHasTerminalEvent(body []byte) bool {
	if !bodyHasSSEFraming(body) {
		return false
	}
	found := false
	forEachOpenAISSEEventPayload(string(body), func(_ string, data []byte) {
		if !found && openAICompactionV2PayloadIsTerminal(data) {
			found = true
		}
	})
	return found
}

func (s *OpenAIGatewayService) openAICompactionV2IdleTimeout() time.Duration {
	if s == nil || s.cfg == nil || s.cfg.Gateway.StreamDataIntervalTimeout <= 0 {
		return 0
	}
	return time.Duration(s.cfg.Gateway.StreamDataIntervalTimeout) * time.Second
}

func (s *OpenAIGatewayService) openAICompactionV2TotalTimeout() time.Duration {
	if s != nil && s.cfg != nil && s.cfg.Gateway.ConcurrencySlotTTLMinutes > 0 {
		return time.Duration(s.cfg.Gateway.ConcurrencySlotTTLMinutes) * time.Minute
	}
	return defaultOpenAICompactionV2TotalTimeout
}

type openAICompactionV2ScanEvent struct {
	line string
	err  error
	eof  bool
}

func (s *OpenAIGatewayService) readOpenAICompactionV2SSEUntilTerminal(ctx context.Context, body io.ReadCloser) ([]byte, error) {
	maxBytes := resolveUpstreamResponseReadLimit(s.cfg)
	if maxBytes > defaultOpenAICompactionV2AttemptMaxBytes {
		maxBytes = defaultOpenAICompactionV2AttemptMaxBytes
	}
	maxLineSize := defaultMaxLineSize
	if s != nil && s.cfg != nil && s.cfg.Gateway.MaxLineSize > 0 {
		maxLineSize = s.cfg.Gateway.MaxLineSize
	}

	events := make(chan openAICompactionV2ScanEvent, 16)
	done := make(chan struct{})
	go func() {
		scanner := bufio.NewScanner(body)
		scanBuf := getSSEScannerBuf64K()
		defer putSSEScannerBuf64K(scanBuf)
		scanner.Buffer(scanBuf[:0], maxLineSize)
		for scanner.Scan() {
			event := openAICompactionV2ScanEvent{line: scanner.Text()}
			select {
			case events <- event:
			case <-done:
				return
			}
		}
		select {
		case events <- openAICompactionV2ScanEvent{err: scanner.Err(), eof: true}:
		case <-done:
		}
	}()
	defer close(done)

	idleTimeout := s.openAICompactionV2IdleTimeout()
	var idleTimer *time.Timer
	var idleCh <-chan time.Time
	if idleTimeout > 0 {
		idleTimer = time.NewTimer(idleTimeout)
		idleCh = idleTimer.C
		defer idleTimer.Stop()
	}
	resetIdleTimer := func() {
		if idleTimer == nil {
			return
		}
		if !idleTimer.Stop() {
			select {
			case <-idleTimer.C:
			default:
			}
		}
		idleTimer.Reset(idleTimeout)
	}

	var buffered bytes.Buffer
	var frameAccumulator openAISSEEventAccumulator
	for {
		select {
		case <-ctx.Done():
			_ = body.Close()
			return buffered.Bytes(), fmt.Errorf("remote compaction v2 read canceled: %w", ctx.Err())
		case <-idleCh:
			_ = body.Close()
			return buffered.Bytes(), errors.New("remote compaction v2 stream data interval timeout")
		case event := <-events:
			if event.eof {
				frameAccumulator.Flush(func(_ string, data []byte) {})
				if event.err != nil {
					return buffered.Bytes(), fmt.Errorf("read remote compaction v2 event stream: %w", event.err)
				}
				return buffered.Bytes(), nil
			}
			dataLine, hasData := extractOpenAISSEDataLine(event.line)
			if hasData && strings.TrimSpace(dataLine) != "" {
				// Transport comments and blank frame separators must not keep a
				// stalled compaction attempt alive indefinitely.
				resetIdleTimer()
			}
			lineBytes := int64(len(event.line) + 1)
			if int64(buffered.Len())+lineBytes > maxBytes {
				_ = body.Close()
				return buffered.Bytes(), fmt.Errorf("%w: limit=%d", errOpenAICompactionV2AttemptTooLarge, maxBytes)
			}
			buffered.WriteString(event.line)
			buffered.WriteByte('\n')

			terminalAtFrameBoundary := false
			frameAccumulator.AddLine(event.line, func(_ string, data []byte) {
				terminalAtFrameBoundary = terminalAtFrameBoundary || openAICompactionV2PayloadIsTerminal(data)
			})
			terminalOnDataLine := false
			if hasData {
				terminalOnDataLine = openAICompactionV2PayloadIsTerminal([]byte(dataLine))
			}
			if !terminalAtFrameBoundary && !terminalOnDataLine {
				continue
			}
			if terminalOnDataLine && strings.TrimSpace(event.line) != "" {
				if int64(buffered.Len())+1 > maxBytes {
					_ = body.Close()
					return buffered.Bytes(), fmt.Errorf("%w: limit=%d", errOpenAICompactionV2AttemptTooLarge, maxBytes)
				}
				buffered.WriteByte('\n')
			}
			_ = body.Close()
			return buffered.Bytes(), nil
		}
	}
}

func (s *OpenAIGatewayService) readOpenAICompactionV2JSON(ctx context.Context, body io.ReadCloser) ([]byte, error) {
	type readResult struct {
		body []byte
		err  error
	}
	resultCh := make(chan readResult, 1)
	go func() {
		payload, err := readUpstreamResponseBodyLimited(body, min(resolveUpstreamResponseReadLimit(s.cfg), defaultOpenAICompactionV2AttemptMaxBytes))
		resultCh <- readResult{body: payload, err: err}
	}()

	var timeoutCh <-chan time.Time
	var timer *time.Timer
	if timeout := s.openAICompactionV2IdleTimeout(); timeout > 0 {
		timer = time.NewTimer(timeout)
		timeoutCh = timer.C
		defer timer.Stop()
	}
	select {
	case result := <-resultCh:
		return result.body, result.err
	case <-ctx.Done():
		_ = body.Close()
		return nil, fmt.Errorf("remote compaction v2 read canceled: %w", ctx.Err())
	case <-timeoutCh:
		_ = body.Close()
		return nil, errors.New("remote compaction v2 response timeout")
	}
}

// readAndValidateOpenAICompactionV2Response buffers only through the first
// terminal event. It never waits for EOF after response.completed.
func (s *OpenAIGatewayService) readAndValidateOpenAICompactionV2Response(ctx context.Context, resp *http.Response, downstreamStream bool) ([]byte, error) {
	if resp == nil || resp.Body == nil {
		return nil, errors.New("remote compaction v2 upstream response has no body")
	}
	if ctx == nil {
		ctx = context.Background()
	}
	originalBody := resp.Body
	var body []byte
	var err error
	if downstreamStream || isEventStreamResponse(resp.Header) {
		body, err = s.readOpenAICompactionV2SSEUntilTerminal(ctx, originalBody)
	} else {
		body, err = s.readOpenAICompactionV2JSON(ctx, originalBody)
	}
	_ = originalBody.Close()
	if err != nil {
		return body, err
	}
	if err := validateOpenAICompactionV2ResponseBody(body, downstreamStream); err != nil {
		return body, err
	}
	resp.Body = io.NopCloser(bytes.NewReader(body))
	return body, nil
}

func (s *OpenAIGatewayService) newOpenAICompactionV2AttemptFailoverError(
	c *gin.Context,
	account *Account,
	attempt *openAICompactionV2AttemptWriter,
	validationErr error,
) *UpstreamFailoverError {
	response := &http.Response{Header: make(http.Header)}
	payload := []byte(nil)
	if attempt != nil {
		response.Header = attempt.Header().Clone()
		payload = attempt.Body()
	}
	passthrough := account != nil && (account.IsOpenAIPassthroughEnabled() || (account.IsGrok() && account.Type == AccountTypeAPIKey))
	return s.newOpenAICompactionV2FailoverError(c, account, response, payload, validationErr, passthrough)
}

func (s *OpenAIGatewayService) newOpenAICompactionV2FailoverError(
	c *gin.Context,
	account *Account,
	resp *http.Response,
	_ []byte,
	validationErr error,
	passthrough bool,
) *UpstreamFailoverError {
	message := "remote compaction v2 response is invalid"
	if validationErr != nil && strings.TrimSpace(validationErr.Error()) != "" {
		message += ": " + validationErr.Error()
	}
	requestID := ""
	if resp != nil {
		requestID = resp.Header.Get("x-request-id")
	}
	// Compaction payloads contain opaque encrypted history. The validation
	// reason is sufficient for diagnostics; never copy the ciphertext into
	// request logs even when generic upstream-body logging is enabled.
	return s.newOpenAIStreamFailoverError(c, account, passthrough, requestID, nil, message)
}
