// Code generated by ent, DO NOT EDIT.

package waitlistentry

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the waitlistentry type in the database.
	Label = "waitlist_entry"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldConfirmationAttemptedAt holds the string denoting the confirmation_attempted_at field in the database.
	FieldConfirmationAttemptedAt = "confirmation_attempted_at"
	// FieldConfirmationSentAt holds the string denoting the confirmation_sent_at field in the database.
	FieldConfirmationSentAt = "confirmation_sent_at"
	// FieldApprovedAt holds the string denoting the approved_at field in the database.
	FieldApprovedAt = "approved_at"
	// FieldApprovedBy holds the string denoting the approved_by field in the database.
	FieldApprovedBy = "approved_by"
	// FieldGrantedUserID holds the string denoting the granted_user_id field in the database.
	FieldGrantedUserID = "granted_user_id"
	// FieldApprovalNoticeAttemptedAt holds the string denoting the approval_notice_attempted_at field in the database.
	FieldApprovalNoticeAttemptedAt = "approval_notice_attempted_at"
	// FieldApprovalNoticeSentAt holds the string denoting the approval_notice_sent_at field in the database.
	FieldApprovalNoticeSentAt = "approval_notice_sent_at"
	// Table holds the table name of the waitlistentry in the database.
	Table = "waitlist_entries"
)

// Columns holds all SQL columns for waitlistentry fields.
var Columns = []string{
	FieldID,
	FieldEmail,
	FieldCreatedAt,
	FieldConfirmationAttemptedAt,
	FieldConfirmationSentAt,
	FieldApprovedAt,
	FieldApprovedBy,
	FieldGrantedUserID,
	FieldApprovalNoticeAttemptedAt,
	FieldApprovalNoticeSentAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the WaitlistEntry queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByConfirmationAttemptedAt orders the results by the confirmation_attempted_at field.
func ByConfirmationAttemptedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfirmationAttemptedAt, opts...).ToFunc()
}

// ByConfirmationSentAt orders the results by the confirmation_sent_at field.
func ByConfirmationSentAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfirmationSentAt, opts...).ToFunc()
}

// ByApprovedAt orders the results by the approved_at field.
func ByApprovedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldApprovedAt, opts...).ToFunc()
}

// ByApprovedBy orders the results by the approved_by field.
func ByApprovedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldApprovedBy, opts...).ToFunc()
}

// ByGrantedUserID orders the results by the granted_user_id field.
func ByGrantedUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGrantedUserID, opts...).ToFunc()
}

// ByApprovalNoticeAttemptedAt orders the results by the approval_notice_attempted_at field.
func ByApprovalNoticeAttemptedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldApprovalNoticeAttemptedAt, opts...).ToFunc()
}

// ByApprovalNoticeSentAt orders the results by the approval_notice_sent_at field.
func ByApprovalNoticeSentAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldApprovalNoticeSentAt, opts...).ToFunc()
}
