// Code generated by ent, DO NOT EDIT.

package waitlistentry

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldLTE(FieldID, id))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldEQ(FieldEmail, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldEQ(FieldCreatedAt, v))
}

// ConfirmationAttemptedAt applies equality check predicate on the "confirmation_attempted_at" field. It's identical to ConfirmationAttemptedAtEQ.
func ConfirmationAttemptedAt(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldEQ(FieldConfirmationAttemptedAt, v))
}

// ConfirmationSentAt applies equality check predicate on the "confirmation_sent_at" field. It's identical to ConfirmationSentAtEQ.
func ConfirmationSentAt(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldEQ(FieldConfirmationSentAt, v))
}

// ApprovedAt applies equality check predicate on the "approved_at" field. It's identical to ApprovedAtEQ.
func ApprovedAt(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldEQ(FieldApprovedAt, v))
}

// ApprovedBy applies equality check predicate on the "approved_by" field. It's identical to ApprovedByEQ.
func ApprovedBy(v int64) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldEQ(FieldApprovedBy, v))
}

// GrantedUserID applies equality check predicate on the "granted_user_id" field. It's identical to GrantedUserIDEQ.
func GrantedUserID(v int64) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldEQ(FieldGrantedUserID, v))
}

// ApprovalNoticeAttemptedAt applies equality check predicate on the "approval_notice_attempted_at" field. It's identical to ApprovalNoticeAttemptedAtEQ.
func ApprovalNoticeAttemptedAt(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldEQ(FieldApprovalNoticeAttemptedAt, v))
}

// ApprovalNoticeSentAt applies equality check predicate on the "approval_notice_sent_at" field. It's identical to ApprovalNoticeSentAtEQ.
func ApprovalNoticeSentAt(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldEQ(FieldApprovalNoticeSentAt, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldContainsFold(FieldEmail, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldLTE(FieldCreatedAt, v))
}

// ConfirmationAttemptedAtEQ applies the EQ predicate on the "confirmation_attempted_at" field.
func ConfirmationAttemptedAtEQ(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldEQ(FieldConfirmationAttemptedAt, v))
}

// ConfirmationAttemptedAtNEQ applies the NEQ predicate on the "confirmation_attempted_at" field.
func ConfirmationAttemptedAtNEQ(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldNEQ(FieldConfirmationAttemptedAt, v))
}

// ConfirmationAttemptedAtIn applies the In predicate on the "confirmation_attempted_at" field.
func ConfirmationAttemptedAtIn(vs ...time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldIn(FieldConfirmationAttemptedAt, vs...))
}

// ConfirmationAttemptedAtNotIn applies the NotIn predicate on the "confirmation_attempted_at" field.
func ConfirmationAttemptedAtNotIn(vs ...time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldNotIn(FieldConfirmationAttemptedAt, vs...))
}

// ConfirmationAttemptedAtGT applies the GT predicate on the "confirmation_attempted_at" field.
func ConfirmationAttemptedAtGT(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldGT(FieldConfirmationAttemptedAt, v))
}

// ConfirmationAttemptedAtGTE applies the GTE predicate on the "confirmation_attempted_at" field.
func ConfirmationAttemptedAtGTE(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldGTE(FieldConfirmationAttemptedAt, v))
}

// ConfirmationAttemptedAtLT applies the LT predicate on the "confirmation_attempted_at" field.
func ConfirmationAttemptedAtLT(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldLT(FieldConfirmationAttemptedAt, v))
}

// ConfirmationAttemptedAtLTE applies the LTE predicate on the "confirmation_attempted_at" field.
func ConfirmationAttemptedAtLTE(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldLTE(FieldConfirmationAttemptedAt, v))
}

// ConfirmationAttemptedAtIsNil applies the IsNil predicate on the "confirmation_attempted_at" field.
func ConfirmationAttemptedAtIsNil() predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldIsNull(FieldConfirmationAttemptedAt))
}

// ConfirmationAttemptedAtNotNil applies the NotNil predicate on the "confirmation_attempted_at" field.
func ConfirmationAttemptedAtNotNil() predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldNotNull(FieldConfirmationAttemptedAt))
}

// ConfirmationSentAtEQ applies the EQ predicate on the "confirmation_sent_at" field.
func ConfirmationSentAtEQ(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldEQ(FieldConfirmationSentAt, v))
}

// ConfirmationSentAtNEQ applies the NEQ predicate on the "confirmation_sent_at" field.
func ConfirmationSentAtNEQ(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldNEQ(FieldConfirmationSentAt, v))
}

// ConfirmationSentAtIn applies the In predicate on the "confirmation_sent_at" field.
func ConfirmationSentAtIn(vs ...time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldIn(FieldConfirmationSentAt, vs...))
}

// ConfirmationSentAtNotIn applies the NotIn predicate on the "confirmation_sent_at" field.
func ConfirmationSentAtNotIn(vs ...time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldNotIn(FieldConfirmationSentAt, vs...))
}

// ConfirmationSentAtGT applies the GT predicate on the "confirmation_sent_at" field.
func ConfirmationSentAtGT(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldGT(FieldConfirmationSentAt, v))
}

// ConfirmationSentAtGTE applies the GTE predicate on the "confirmation_sent_at" field.
func ConfirmationSentAtGTE(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldGTE(FieldConfirmationSentAt, v))
}

// ConfirmationSentAtLT applies the LT predicate on the "confirmation_sent_at" field.
func ConfirmationSentAtLT(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldLT(FieldConfirmationSentAt, v))
}

// ConfirmationSentAtLTE applies the LTE predicate on the "confirmation_sent_at" field.
func ConfirmationSentAtLTE(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldLTE(FieldConfirmationSentAt, v))
}

// ConfirmationSentAtIsNil applies the IsNil predicate on the "confirmation_sent_at" field.
func ConfirmationSentAtIsNil() predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldIsNull(FieldConfirmationSentAt))
}

// ConfirmationSentAtNotNil applies the NotNil predicate on the "confirmation_sent_at" field.
func ConfirmationSentAtNotNil() predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldNotNull(FieldConfirmationSentAt))
}

// ApprovedAtEQ applies the EQ predicate on the "approved_at" field.
func ApprovedAtEQ(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldEQ(FieldApprovedAt, v))
}

// ApprovedAtNEQ applies the NEQ predicate on the "approved_at" field.
func ApprovedAtNEQ(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldNEQ(FieldApprovedAt, v))
}

// ApprovedAtIn applies the In predicate on the "approved_at" field.
func ApprovedAtIn(vs ...time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldIn(FieldApprovedAt, vs...))
}

// ApprovedAtNotIn applies the NotIn predicate on the "approved_at" field.
func ApprovedAtNotIn(vs ...time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldNotIn(FieldApprovedAt, vs...))
}

// ApprovedAtGT applies the GT predicate on the "approved_at" field.
func ApprovedAtGT(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldGT(FieldApprovedAt, v))
}

// ApprovedAtGTE applies the GTE predicate on the "approved_at" field.
func ApprovedAtGTE(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldGTE(FieldApprovedAt, v))
}

// ApprovedAtLT applies the LT predicate on the "approved_at" field.
func ApprovedAtLT(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldLT(FieldApprovedAt, v))
}

// ApprovedAtLTE applies the LTE predicate on the "approved_at" field.
func ApprovedAtLTE(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldLTE(FieldApprovedAt, v))
}

// ApprovedAtIsNil applies the IsNil predicate on the "approved_at" field.
func ApprovedAtIsNil() predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldIsNull(FieldApprovedAt))
}

// ApprovedAtNotNil applies the NotNil predicate on the "approved_at" field.
func ApprovedAtNotNil() predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldNotNull(FieldApprovedAt))
}

// ApprovedByEQ applies the EQ predicate on the "approved_by" field.
func ApprovedByEQ(v int64) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldEQ(FieldApprovedBy, v))
}

// ApprovedByNEQ applies the NEQ predicate on the "approved_by" field.
func ApprovedByNEQ(v int64) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldNEQ(FieldApprovedBy, v))
}

// ApprovedByIn applies the In predicate on the "approved_by" field.
func ApprovedByIn(vs ...int64) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldIn(FieldApprovedBy, vs...))
}

// ApprovedByNotIn applies the NotIn predicate on the "approved_by" field.
func ApprovedByNotIn(vs ...int64) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldNotIn(FieldApprovedBy, vs...))
}

// ApprovedByGT applies the GT predicate on the "approved_by" field.
func ApprovedByGT(v int64) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldGT(FieldApprovedBy, v))
}

// ApprovedByGTE applies the GTE predicate on the "approved_by" field.
func ApprovedByGTE(v int64) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldGTE(FieldApprovedBy, v))
}

// ApprovedByLT applies the LT predicate on the "approved_by" field.
func ApprovedByLT(v int64) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldLT(FieldApprovedBy, v))
}

// ApprovedByLTE applies the LTE predicate on the "approved_by" field.
func ApprovedByLTE(v int64) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldLTE(FieldApprovedBy, v))
}

// ApprovedByIsNil applies the IsNil predicate on the "approved_by" field.
func ApprovedByIsNil() predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldIsNull(FieldApprovedBy))
}

// ApprovedByNotNil applies the NotNil predicate on the "approved_by" field.
func ApprovedByNotNil() predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldNotNull(FieldApprovedBy))
}

// GrantedUserIDEQ applies the EQ predicate on the "granted_user_id" field.
func GrantedUserIDEQ(v int64) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldEQ(FieldGrantedUserID, v))
}

// GrantedUserIDNEQ applies the NEQ predicate on the "granted_user_id" field.
func GrantedUserIDNEQ(v int64) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldNEQ(FieldGrantedUserID, v))
}

// GrantedUserIDIn applies the In predicate on the "granted_user_id" field.
func GrantedUserIDIn(vs ...int64) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldIn(FieldGrantedUserID, vs...))
}

// GrantedUserIDNotIn applies the NotIn predicate on the "granted_user_id" field.
func GrantedUserIDNotIn(vs ...int64) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldNotIn(FieldGrantedUserID, vs...))
}

// GrantedUserIDGT applies the GT predicate on the "granted_user_id" field.
func GrantedUserIDGT(v int64) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldGT(FieldGrantedUserID, v))
}

// GrantedUserIDGTE applies the GTE predicate on the "granted_user_id" field.
func GrantedUserIDGTE(v int64) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldGTE(FieldGrantedUserID, v))
}

// GrantedUserIDLT applies the LT predicate on the "granted_user_id" field.
func GrantedUserIDLT(v int64) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldLT(FieldGrantedUserID, v))
}

// GrantedUserIDLTE applies the LTE predicate on the "granted_user_id" field.
func GrantedUserIDLTE(v int64) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldLTE(FieldGrantedUserID, v))
}

// GrantedUserIDIsNil applies the IsNil predicate on the "granted_user_id" field.
func GrantedUserIDIsNil() predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldIsNull(FieldGrantedUserID))
}

// GrantedUserIDNotNil applies the NotNil predicate on the "granted_user_id" field.
func GrantedUserIDNotNil() predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldNotNull(FieldGrantedUserID))
}

// ApprovalNoticeAttemptedAtEQ applies the EQ predicate on the "approval_notice_attempted_at" field.
func ApprovalNoticeAttemptedAtEQ(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldEQ(FieldApprovalNoticeAttemptedAt, v))
}

// ApprovalNoticeAttemptedAtNEQ applies the NEQ predicate on the "approval_notice_attempted_at" field.
func ApprovalNoticeAttemptedAtNEQ(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldNEQ(FieldApprovalNoticeAttemptedAt, v))
}

// ApprovalNoticeAttemptedAtIn applies the In predicate on the "approval_notice_attempted_at" field.
func ApprovalNoticeAttemptedAtIn(vs ...time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldIn(FieldApprovalNoticeAttemptedAt, vs...))
}

// ApprovalNoticeAttemptedAtNotIn applies the NotIn predicate on the "approval_notice_attempted_at" field.
func ApprovalNoticeAttemptedAtNotIn(vs ...time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldNotIn(FieldApprovalNoticeAttemptedAt, vs...))
}

// ApprovalNoticeAttemptedAtGT applies the GT predicate on the "approval_notice_attempted_at" field.
func ApprovalNoticeAttemptedAtGT(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldGT(FieldApprovalNoticeAttemptedAt, v))
}

// ApprovalNoticeAttemptedAtGTE applies the GTE predicate on the "approval_notice_attempted_at" field.
func ApprovalNoticeAttemptedAtGTE(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldGTE(FieldApprovalNoticeAttemptedAt, v))
}

// ApprovalNoticeAttemptedAtLT applies the LT predicate on the "approval_notice_attempted_at" field.
func ApprovalNoticeAttemptedAtLT(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldLT(FieldApprovalNoticeAttemptedAt, v))
}

// ApprovalNoticeAttemptedAtLTE applies the LTE predicate on the "approval_notice_attempted_at" field.
func ApprovalNoticeAttemptedAtLTE(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldLTE(FieldApprovalNoticeAttemptedAt, v))
}

// ApprovalNoticeAttemptedAtIsNil applies the IsNil predicate on the "approval_notice_attempted_at" field.
func ApprovalNoticeAttemptedAtIsNil() predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldIsNull(FieldApprovalNoticeAttemptedAt))
}

// ApprovalNoticeAttemptedAtNotNil applies the NotNil predicate on the "approval_notice_attempted_at" field.
func ApprovalNoticeAttemptedAtNotNil() predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldNotNull(FieldApprovalNoticeAttemptedAt))
}

// ApprovalNoticeSentAtEQ applies the EQ predicate on the "approval_notice_sent_at" field.
func ApprovalNoticeSentAtEQ(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldEQ(FieldApprovalNoticeSentAt, v))
}

// ApprovalNoticeSentAtNEQ applies the NEQ predicate on the "approval_notice_sent_at" field.
func ApprovalNoticeSentAtNEQ(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldNEQ(FieldApprovalNoticeSentAt, v))
}

// ApprovalNoticeSentAtIn applies the In predicate on the "approval_notice_sent_at" field.
func ApprovalNoticeSentAtIn(vs ...time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldIn(FieldApprovalNoticeSentAt, vs...))
}

// ApprovalNoticeSentAtNotIn applies the NotIn predicate on the "approval_notice_sent_at" field.
func ApprovalNoticeSentAtNotIn(vs ...time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldNotIn(FieldApprovalNoticeSentAt, vs...))
}

// ApprovalNoticeSentAtGT applies the GT predicate on the "approval_notice_sent_at" field.
func ApprovalNoticeSentAtGT(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldGT(FieldApprovalNoticeSentAt, v))
}

// ApprovalNoticeSentAtGTE applies the GTE predicate on the "approval_notice_sent_at" field.
func ApprovalNoticeSentAtGTE(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldGTE(FieldApprovalNoticeSentAt, v))
}

// ApprovalNoticeSentAtLT applies the LT predicate on the "approval_notice_sent_at" field.
func ApprovalNoticeSentAtLT(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldLT(FieldApprovalNoticeSentAt, v))
}

// ApprovalNoticeSentAtLTE applies the LTE predicate on the "approval_notice_sent_at" field.
func ApprovalNoticeSentAtLTE(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldLTE(FieldApprovalNoticeSentAt, v))
}

// ApprovalNoticeSentAtIsNil applies the IsNil predicate on the "approval_notice_sent_at" field.
func ApprovalNoticeSentAtIsNil() predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldIsNull(FieldApprovalNoticeSentAt))
}

// ApprovalNoticeSentAtNotNil applies the NotNil predicate on the "approval_notice_sent_at" field.
func ApprovalNoticeSentAtNotNil() predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldNotNull(FieldApprovalNoticeSentAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WaitlistEntry) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WaitlistEntry) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WaitlistEntry) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.NotPredicates(p))
}
