// Code generated by ent, DO NOT EDIT.

package waitlistentry

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldLTE(FieldID, id))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldEQ(FieldEmail, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldEQ(FieldCreatedAt, v))
}

// ConfirmationAttemptedAt applies equality check predicate on the "confirmation_attempted_at" field. It's identical to ConfirmationAttemptedAtEQ.
func ConfirmationAttemptedAt(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldEQ(FieldConfirmationAttemptedAt, v))
}

// ConfirmationSentAt applies equality check predicate on the "confirmation_sent_at" field. It's identical to ConfirmationSentAtEQ.
func ConfirmationSentAt(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldEQ(FieldConfirmationSentAt, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldContainsFold(FieldEmail, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldLTE(FieldCreatedAt, v))
}

// ConfirmationAttemptedAtEQ applies the EQ predicate on the "confirmation_attempted_at" field.
func ConfirmationAttemptedAtEQ(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldEQ(FieldConfirmationAttemptedAt, v))
}

// ConfirmationAttemptedAtNEQ applies the NEQ predicate on the "confirmation_attempted_at" field.
func ConfirmationAttemptedAtNEQ(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldNEQ(FieldConfirmationAttemptedAt, v))
}

// ConfirmationAttemptedAtIn applies the In predicate on the "confirmation_attempted_at" field.
func ConfirmationAttemptedAtIn(vs ...time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldIn(FieldConfirmationAttemptedAt, vs...))
}

// ConfirmationAttemptedAtNotIn applies the NotIn predicate on the "confirmation_attempted_at" field.
func ConfirmationAttemptedAtNotIn(vs ...time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldNotIn(FieldConfirmationAttemptedAt, vs...))
}

// ConfirmationAttemptedAtGT applies the GT predicate on the "confirmation_attempted_at" field.
func ConfirmationAttemptedAtGT(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldGT(FieldConfirmationAttemptedAt, v))
}

// ConfirmationAttemptedAtGTE applies the GTE predicate on the "confirmation_attempted_at" field.
func ConfirmationAttemptedAtGTE(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldGTE(FieldConfirmationAttemptedAt, v))
}

// ConfirmationAttemptedAtLT applies the LT predicate on the "confirmation_attempted_at" field.
func ConfirmationAttemptedAtLT(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldLT(FieldConfirmationAttemptedAt, v))
}

// ConfirmationAttemptedAtLTE applies the LTE predicate on the "confirmation_attempted_at" field.
func ConfirmationAttemptedAtLTE(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldLTE(FieldConfirmationAttemptedAt, v))
}

// ConfirmationAttemptedAtIsNil applies the IsNil predicate on the "confirmation_attempted_at" field.
func ConfirmationAttemptedAtIsNil() predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldIsNull(FieldConfirmationAttemptedAt))
}

// ConfirmationAttemptedAtNotNil applies the NotNil predicate on the "confirmation_attempted_at" field.
func ConfirmationAttemptedAtNotNil() predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldNotNull(FieldConfirmationAttemptedAt))
}

// ConfirmationSentAtEQ applies the EQ predicate on the "confirmation_sent_at" field.
func ConfirmationSentAtEQ(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldEQ(FieldConfirmationSentAt, v))
}

// ConfirmationSentAtNEQ applies the NEQ predicate on the "confirmation_sent_at" field.
func ConfirmationSentAtNEQ(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldNEQ(FieldConfirmationSentAt, v))
}

// ConfirmationSentAtIn applies the In predicate on the "confirmation_sent_at" field.
func ConfirmationSentAtIn(vs ...time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldIn(FieldConfirmationSentAt, vs...))
}

// ConfirmationSentAtNotIn applies the NotIn predicate on the "confirmation_sent_at" field.
func ConfirmationSentAtNotIn(vs ...time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldNotIn(FieldConfirmationSentAt, vs...))
}

// ConfirmationSentAtGT applies the GT predicate on the "confirmation_sent_at" field.
func ConfirmationSentAtGT(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldGT(FieldConfirmationSentAt, v))
}

// ConfirmationSentAtGTE applies the GTE predicate on the "confirmation_sent_at" field.
func ConfirmationSentAtGTE(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldGTE(FieldConfirmationSentAt, v))
}

// ConfirmationSentAtLT applies the LT predicate on the "confirmation_sent_at" field.
func ConfirmationSentAtLT(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldLT(FieldConfirmationSentAt, v))
}

// ConfirmationSentAtLTE applies the LTE predicate on the "confirmation_sent_at" field.
func ConfirmationSentAtLTE(v time.Time) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldLTE(FieldConfirmationSentAt, v))
}

// ConfirmationSentAtIsNil applies the IsNil predicate on the "confirmation_sent_at" field.
func ConfirmationSentAtIsNil() predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldIsNull(FieldConfirmationSentAt))
}

// ConfirmationSentAtNotNil applies the NotNil predicate on the "confirmation_sent_at" field.
func ConfirmationSentAtNotNil() predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.FieldNotNull(FieldConfirmationSentAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WaitlistEntry) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WaitlistEntry) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WaitlistEntry) predicate.WaitlistEntry {
	return predicate.WaitlistEntry(sql.NotPredicates(p))
}
