// Code generated by ent, DO NOT EDIT.

package subscriptionconcurrencyentitlement

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldEQ(FieldUserID, v))
}

// SubscriptionID applies equality check predicate on the "subscription_id" field. It's identical to SubscriptionIDEQ.
func SubscriptionID(v int64) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldEQ(FieldSubscriptionID, v))
}

// SourceOrderID applies equality check predicate on the "source_order_id" field. It's identical to SourceOrderIDEQ.
func SourceOrderID(v int64) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldEQ(FieldSourceOrderID, v))
}

// Concurrency applies equality check predicate on the "concurrency" field. It's identical to ConcurrencyEQ.
func Concurrency(v int) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldEQ(FieldConcurrency, v))
}

// StartsAt applies equality check predicate on the "starts_at" field. It's identical to StartsAtEQ.
func StartsAt(v time.Time) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldEQ(FieldStartsAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldNotIn(FieldUserID, vs...))
}

// SubscriptionIDEQ applies the EQ predicate on the "subscription_id" field.
func SubscriptionIDEQ(v int64) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldEQ(FieldSubscriptionID, v))
}

// SubscriptionIDNEQ applies the NEQ predicate on the "subscription_id" field.
func SubscriptionIDNEQ(v int64) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldNEQ(FieldSubscriptionID, v))
}

// SubscriptionIDIn applies the In predicate on the "subscription_id" field.
func SubscriptionIDIn(vs ...int64) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldIn(FieldSubscriptionID, vs...))
}

// SubscriptionIDNotIn applies the NotIn predicate on the "subscription_id" field.
func SubscriptionIDNotIn(vs ...int64) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldNotIn(FieldSubscriptionID, vs...))
}

// SourceOrderIDEQ applies the EQ predicate on the "source_order_id" field.
func SourceOrderIDEQ(v int64) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldEQ(FieldSourceOrderID, v))
}

// SourceOrderIDNEQ applies the NEQ predicate on the "source_order_id" field.
func SourceOrderIDNEQ(v int64) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldNEQ(FieldSourceOrderID, v))
}

// SourceOrderIDIn applies the In predicate on the "source_order_id" field.
func SourceOrderIDIn(vs ...int64) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldIn(FieldSourceOrderID, vs...))
}

// SourceOrderIDNotIn applies the NotIn predicate on the "source_order_id" field.
func SourceOrderIDNotIn(vs ...int64) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldNotIn(FieldSourceOrderID, vs...))
}

// SourceOrderIDGT applies the GT predicate on the "source_order_id" field.
func SourceOrderIDGT(v int64) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldGT(FieldSourceOrderID, v))
}

// SourceOrderIDGTE applies the GTE predicate on the "source_order_id" field.
func SourceOrderIDGTE(v int64) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldGTE(FieldSourceOrderID, v))
}

// SourceOrderIDLT applies the LT predicate on the "source_order_id" field.
func SourceOrderIDLT(v int64) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldLT(FieldSourceOrderID, v))
}

// SourceOrderIDLTE applies the LTE predicate on the "source_order_id" field.
func SourceOrderIDLTE(v int64) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldLTE(FieldSourceOrderID, v))
}

// SourceOrderIDIsNil applies the IsNil predicate on the "source_order_id" field.
func SourceOrderIDIsNil() predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldIsNull(FieldSourceOrderID))
}

// SourceOrderIDNotNil applies the NotNil predicate on the "source_order_id" field.
func SourceOrderIDNotNil() predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldNotNull(FieldSourceOrderID))
}

// ConcurrencyEQ applies the EQ predicate on the "concurrency" field.
func ConcurrencyEQ(v int) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldEQ(FieldConcurrency, v))
}

// ConcurrencyNEQ applies the NEQ predicate on the "concurrency" field.
func ConcurrencyNEQ(v int) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldNEQ(FieldConcurrency, v))
}

// ConcurrencyIn applies the In predicate on the "concurrency" field.
func ConcurrencyIn(vs ...int) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldIn(FieldConcurrency, vs...))
}

// ConcurrencyNotIn applies the NotIn predicate on the "concurrency" field.
func ConcurrencyNotIn(vs ...int) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldNotIn(FieldConcurrency, vs...))
}

// ConcurrencyGT applies the GT predicate on the "concurrency" field.
func ConcurrencyGT(v int) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldGT(FieldConcurrency, v))
}

// ConcurrencyGTE applies the GTE predicate on the "concurrency" field.
func ConcurrencyGTE(v int) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldGTE(FieldConcurrency, v))
}

// ConcurrencyLT applies the LT predicate on the "concurrency" field.
func ConcurrencyLT(v int) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldLT(FieldConcurrency, v))
}

// ConcurrencyLTE applies the LTE predicate on the "concurrency" field.
func ConcurrencyLTE(v int) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldLTE(FieldConcurrency, v))
}

// StartsAtEQ applies the EQ predicate on the "starts_at" field.
func StartsAtEQ(v time.Time) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldEQ(FieldStartsAt, v))
}

// StartsAtNEQ applies the NEQ predicate on the "starts_at" field.
func StartsAtNEQ(v time.Time) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldNEQ(FieldStartsAt, v))
}

// StartsAtIn applies the In predicate on the "starts_at" field.
func StartsAtIn(vs ...time.Time) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldIn(FieldStartsAt, vs...))
}

// StartsAtNotIn applies the NotIn predicate on the "starts_at" field.
func StartsAtNotIn(vs ...time.Time) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldNotIn(FieldStartsAt, vs...))
}

// StartsAtGT applies the GT predicate on the "starts_at" field.
func StartsAtGT(v time.Time) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldGT(FieldStartsAt, v))
}

// StartsAtGTE applies the GTE predicate on the "starts_at" field.
func StartsAtGTE(v time.Time) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldGTE(FieldStartsAt, v))
}

// StartsAtLT applies the LT predicate on the "starts_at" field.
func StartsAtLT(v time.Time) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldLT(FieldStartsAt, v))
}

// StartsAtLTE applies the LTE predicate on the "starts_at" field.
func StartsAtLTE(v time.Time) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldLTE(FieldStartsAt, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.FieldLTE(FieldExpiresAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSubscription applies the HasEdge predicate on the "subscription" edge.
func HasSubscription() predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SubscriptionTable, SubscriptionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSubscriptionWith applies the HasEdge predicate on the "subscription" edge with a given conditions (other predicates).
func HasSubscriptionWith(preds ...predicate.UserSubscription) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(func(s *sql.Selector) {
		step := newSubscriptionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SubscriptionConcurrencyEntitlement) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SubscriptionConcurrencyEntitlement) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SubscriptionConcurrencyEntitlement) predicate.SubscriptionConcurrencyEntitlement {
	return predicate.SubscriptionConcurrencyEntitlement(sql.NotPredicates(p))
}
